/**
 * @author Junaid Atari <mj.atari@gmail.com>
 * @copyright 2025 Junaid Atari
 * @see https://github.com/blacksmoke26
 */

import axios, {AxiosInstance} from 'axios';

// types
import {ConfigMeta, EnhancementType, UserRole} from '~/database/models';
import type {PromptRequest, PromptResponse, AIModel} from '~/types';
import {toEnhancementTypes, toUserRoles} from '~/utils/prompts';

/**
 * Abstract base class for AI provider implementations.
 * Provides common functionality for API client initialization and processing time calculation.
 *
 * @example
 * class CustomProvider extends BaseAIProvider {
 *   async getModels() { return []; }
 *   async enhancePrompt(req) { return { enhancedPrompt: req.prompt }; }
 *   async isAvailable() { return true; }
 * }
 *
 * @developer_notes
 * Extend this class to implement new AI providers with custom API integrations.
 */
export default abstract class BaseAIProvider {
  /** HTTP client instance for making API requests */
  protected client: AxiosInstance;
  /** Provider name */
  protected name: string;

  /**
   * Creates an instance of BaseAIProvider with HTTP client configuration.
   * @param name - Provider identifier for logging/tracking purposes
   * @param config - Configuration object
   *
   * @example
   * const provider = new BaseAIProvider('openai', 'https://api.openai.com', 10000);
   */
  constructor(name: string, config: ConfigMeta) {
    this.name = name;
    this.client = axios.create({
      baseURL: config?.baseUrl,
      timeout: config?.timeout ?? 30000,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  }

  /**
   * Retrieves available AI models from the provider.
   * @returns Promise resolving to array of available model configurations
   *
   * @example
   * const models = await provider.getModels();
   * console.log(models[0].id); // "gpt-4"
   */
  abstract getModels(): Promise<AIModel[]>;

  /**
   * Enhances a prompt using the provider's AI capabilities.
   * @param request - Prompt enhancement request with input text and options
   * @returns Promise resolving to enhanced prompt response
   *
   * @example
   * const response = await provider.enhancePrompt({
   *   prompt: "What is the weather?",
   *   context: "user in Tokyo"
   * });
   */
  abstract enhancePrompt(request: PromptRequest): Promise<PromptResponse>;

  /**
   * Checks provider availability and connectivity.
   * @returns Promise resolving to boolean indicating service status
   *
   * @example
   * if (await provider.isAvailable()) {
   *   // proceed with API calls
   * }
   */
  abstract isAvailable(): Promise<boolean>;

  /**
   * Calculates processing time in milliseconds from start timestamp.
   * @param startTime - Epoch timestamp when operation began
   * @returns Elapsed time in milliseconds
   *
   * @example
   * const start = Date.now();
   * await operation();
   * console.log(calculateProcessingTime(start)); // 123
   *
   * @developer_notes
   * Use for performance monitoring and timeout handling.
   */
  protected calculateProcessingTime(startTime: number): number {
    return Date.now() - startTime;
  }

  /**
   * Formats a full prompt with system message, user input, and enhanced prompt section.
   *
   * @param userPrompt - The user's original input prompt
   * @returns A formatted string containing all prompt components
   *
   * @example
   * formatFullPrompt("Explain quantum physics")
   * // Returns:
   * // "You are an AI assistant\n\nOriginal prompt: Explain quantum physics\n\nEnhanced prompt:"
   *
   * Developer Note: This method serves as a template for prompt formatting and
   * should be used for logging or display purposes when generating prompts.
   */
  public formatPrompt(userPrompt: string): string {
    return `Original prompt: ${userPrompt}\n\nOutput Format: Markdown:`;
  }

  /**
   * Formats the system prompt (placeholder implementation; returns input as-is).
   * @param systemPrompt - The raw system prompt string to be formatted.
   * @returns The formatted system prompt (identical to input in this implementation).
   * @example
   * const formattedPrompt = formatSystemPrompt("You are a helpful assistant.");
   * // Output: "You are a helpful assistant."
   * @note This method is a no-op by default and should be overridden in subclasses to implement custom formatting logic.
   */
  public formatSystemPrompt(systemPrompt: string): string {
    return systemPrompt;
  }

  /**
   * Extracts the response content from a model's response object.
   * Returns the trimmed response content or the original user prompt if no response is found.
   *
   * @param enhancedResponse - The enhanced response generated by the provider
   * @param userPrompt - The original user input prompt as fallback
   * @returns The extracted response content or the user prompt
   *
   * @example
   * toPromptResponse( "Hello, world!", "Ask about AI")
   * // Returns: "Hello, world!"
   *
   * toPromptResponse('', "Ask about AI")
   * // Returns: "Ask about AI"
   *
   * Developer Note: This method ensures consistent handling of empty responses
   * and provides a fallback mechanism for cases where the model's response is missing.
   */
  public toPromptResponse(enhancedResponse: string, userPrompt: string): string {
    return String(enhancedResponse || '')?.trim?.() || userPrompt;
  }

  /**
   * Builds the system prompt by combining role-specific and enhancement-based prompts.
   * Combines `rolePrompt` and `systemPrompt` from the request, with fallbacks if fields are missing.
   * @param request - The request object containing prompt configuration.
   * @returns The constructed system prompt string.
   * @example
   * const request = {
   *   enhancementType: 'enhance',
   *   userRole: 'admin'
   * };
   * const prompt = buildSystemPrompt(request);
   * // Output: "Admin role prompt. Enhance system prompt."
   * @note
   * - Falls back to default prompts if `systemPrompt` or `enhancementType` is missing.
   * - Uses `toEnhancementTypes()` and `toUserRoles()` for prompt mapping.
   * - Override this method for custom prompt construction logic.
   */
  public async buildSystemPrompt(request: PromptRequest): Promise<string> {
    const typeRecord = await EnhancementType.findOne({
      attributes: ['systemPrompt'],
      where: {key: request.enhancementType},
      raw: true,
    });

    const userRecord = await UserRole.findOne({
      attributes: ['systemPrompt'],
      where: {key: request.userRole},
      raw: true,
    });

    const systemPrompt = typeRecord?.systemPrompt || 'You are a grammar and spelling expert. Correct any grammatical errors, spelling mistakes, and improve the clarity of the given prompt while preserving the original intent.';
    const rolePrompt = userRecord?.systemPrompt || 'You are a helpful AI assistant. Provide clear, accurate, and useful responses to enhance the user\'s prompt.';

    return `${rolePrompt} ${systemPrompt}`;
  }
}
