/**
 * @author Junaid Atari <mj.atari@gmail.com>
 * @copyright 2025 Junaid Atari
 * @see https://github.com/blacksmoke26
 */

import React from 'react';
import {Star} from 'lucide-react';
import {Progress} from '@radix-ui/themes';

// constants
import {SmartSuggestion} from '~/constants/prompt-suggestions';

// helpers
import {cn} from '~/utils/helpers';

// ui components
import {Card} from '~/components/ui/Card';
import {Badge, BadgeVariant} from '~/components/ui/Badge';
import {Tooltip, TooltipContent, TooltipProvider, TooltipTrigger} from '~/components/ui/Tooltip';

/**
 * Renders a smart suggestion panel with adaptive scoring, AI recommendation status, and customizable tag rendering.
 * Used to display prioritized suggestions with interactive elements and dynamic UI updates.
 *
 * Example:
 * <SmartSuggestionsPanel
 *   aiRecommended={true}
 *   caption="Top Recommendations"
 *   suggestion={{ content: "Suggested action", metadata: { type: "action" } }}
 *   adaptiveScore={0.92}
 *   priorityBadgeVariant="primary"
 *   onTagChange={(tag, index) => <span>{tag}</span>}
 *   onApplySuggestionClick={() => console.log("Suggestion applied")}
 * />
 */
export interface SmartSuggestionsPanelProps {
  /** Indicates whether the suggestion was generated by AI recommendation systems */
  aiRecommended: boolean;
  /** Caption/title displayed above the suggestion panel */
  caption: string;
  /** The smart suggestion data to display */
  suggestion: SmartSuggestion;
  /** A score (0-1) indicating the adaptive confidence level of the suggestion */
  adaptiveScore: number;
  /** Variant for the priority badge styling (e.g., 'primary', 'secondary', 'warning') */
  priorityBadgeVariant: string;
  /** Custom renderer for tags, receives (tag, index) and returns JSX */
  onTagChange(tag: string, index: number): React.JSX.Element;
  /** Callback triggered when the user applies the suggestion */
  onApplySuggestionClick(): void;
}

/**
 * A reusable smart suggestion panel component that displays prioritized recommendations
 * with adaptive scoring, AI status, and customizable UI elements.
 *
 * Developer Notes:
 * - Requires `suggestion` and `caption` props to be functional
 * - `adaptiveScore` should be between 0 and 1 for proper UI visualization
 * - `onTagChange` allows full customization of tag rendering
 * - `priorityBadgeVariant` should match system-defined badge variants for consistent styling
 * - Ensure `onApplySuggestionClick` handles the suggestion application logic
 */
const FilteredSuggestion: React.FC<SmartSuggestionsPanelProps> = (props) => {
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Card
            className={cn(
              'group transition-all duration-300 cursor-pointer hover:shadow-lg border-2',
              props.aiRecommended
                ? 'border-purple-500/30 hover:border-purple-500/50'
                : 'border-border hover:border-primary/50',
              'hover:scale-[1.01]',
            )}
            onClick={props.onApplySuggestionClick}
          >
            <div className="p-3">
              <div className="flex items-start justify-between">
                <div className="space-y-1 flex-1">
                  <div className="flex items-center gap-2">
                    {props.aiRecommended && (
                      <div
                        className="flex-shrink-0 w-4 h-4 rounded-full bg-gradient-to-r from-purple-500 to-indigo-600 flex items-center justify-center">
                        <Star className="h-2.5 w-2.5 text-white"/>
                      </div>
                    )}
                    <h3 className={cn(
                      'font-semibold text-sm transition-colors duration-200',
                      props.aiRecommended ? 'text-purple-700 dark:text-purple-400' : 'text-foreground',
                    )}>
                      {props.suggestion.title}
                    </h3>
                  </div>

                  <div className="flex flex-wrap gap-1 mt-1">
                    {props.aiRecommended && props.adaptiveScore > 0.8 && (
                      <Badge variant="destructive" className="text-[10px] px-1.5 py-0.5">
                        TOP RECOMMENDATION
                      </Badge>
                    )}
                    <Badge
                      variant={props.priorityBadgeVariant as BadgeVariant}
                      className="text-[10px] px-1.5 py-0.5"
                    >
                      {props.suggestion.priority.toUpperCase()}
                    </Badge>
                    <Badge
                      variant={props.suggestion.complexity === 'beginner' ? 'default' :
                        props.suggestion.complexity === 'intermediate' ? 'secondary' :
                          props.suggestion.complexity === 'advanced' ? 'outline' : 'destructive'}
                      className="text-[10px] px-1.5 py-0.5"
                    >
                      {props.suggestion.complexity}
                    </Badge>
                  </div>
                </div>

                {props.aiRecommended && (
                  <div className="flex-shrink-0 ml-2">
                    <div
                      className="w-6 h-6 rounded-full bg-gradient-to-r from-purple-500 to-indigo-600 flex items-center justify-center text-white text-[10px] font-bold">
                      AI
                    </div>
                  </div>
                )}
              </div>

              <p className="text-xs mt-2 text-muted-foreground line-clamp-2">
                {props.suggestion.description}
              </p>

              {(props.suggestion as any).relevance && (
                <div className="mt-2 flex flex-wrap gap-1">
                  {(props.suggestion as any).relevance.context && (
                    <Badge variant="secondary" className="text-[10px] bg-green-50/50">
                      Context Match
                    </Badge>
                  )}
                  {(props.suggestion as any).relevance.domain && (
                    <Badge variant="secondary" className="text-[10px] bg-blue-50/50">
                      Domain Match
                    </Badge>
                  )}
                  {(props.suggestion as any).relevance.complexity && (
                    <Badge variant="secondary" className="text-[10px] bg-purple-50/50">
                      Complexity Match
                    </Badge>
                  )}
                </div>
              )}

              {props.suggestion.example && props.suggestion.example.trim() && (
                <div
                  className="mt-3 p-2 bg-muted/40 rounded text-[11px] border border-border min-h-[60px] max-h-[80px] overflow-hidden text-ellipsis">
                  <div className="flex items-start gap-1">
                    <span className="font-medium flex-shrink-0">Example:</span>
                    <span className="text-muted-foreground line-clamp-2">
                                        {props.suggestion.example}
                                      </span>
                  </div>
                </div>
              )}

              {Array.isArray(props.suggestion.tags) && props.suggestion.tags.length > 0 && (
                <div className="mt-2 flex flex-wrap gap-1 max-h-[40px] overflow-hidden">
                  {props.suggestion.tags.slice(0, 4).map(props.onTagChange)}
                  {props.suggestion.tags.length > 4 && (
                    <Badge variant="outline" className="text-[10px] px-1.5 py-0">
                      +{props.suggestion.tags.length - 4}
                    </Badge>
                  )}
                </div>
              )}
            </div>

            <div className={cn(
              'h-1 transition-all duration-500',
              props.aiRecommended
                ? 'bg-gradient-to-r from-purple-500 to-indigo-600'
                : 'bg-primary/20',
            )}/>
          </Card>
        </TooltipTrigger>
        <TooltipContent className="max-w-md p-3">
          <div className="space-y-2">
            <p className="font-medium">{props.suggestion.title}</p>
            <p>{props.suggestion.description}</p>

            {props.aiRecommended && (
              <div className="space-y-1 pt-1 border-t border-border mt-1">
                <div className="flex justify-between text-xs">
                  <span>AI Confidence Score</span>
                  <span className={cn(
                    props.adaptiveScore > 0.8 ? 'text-green-500 font-medium' :
                      props.adaptiveScore > 0.6 ? 'text-yellow-500' : 'text-red-500',
                  )}>
                                      {(props.adaptiveScore * 100).toFixed(1)}%
                                    </span>
                </div>
                <Progress
                  value={props.adaptiveScore * 100}
                  className={cn(
                    props.adaptiveScore > 0.8 && 'bg-green-500 [&>div]:bg-green-600',
                    props.adaptiveScore > 0.6 && props.adaptiveScore <= 0.8 && 'bg-yellow-500 [&>div]:bg-yellow-600',
                    props.adaptiveScore <= 0.6 && 'bg-red-500 [&>div]:bg-red-600',
                  )}
                />
              </div>
            )}

            <div className="mt-2 text-xs space-y-1">
              <div className="flex justify-between">
                <span className="font-medium">Category:</span>
                <span>{props.suggestion.category}</span>
              </div>
              <div className="flex justify-between">
                <span className="font-medium">Domain:</span>
                <span>{props.suggestion.domain}</span>
              </div>
              <div className="flex justify-between">
                <span className="font-medium">Intelligence:</span>
                <span>{props.caption}</span>
              </div>
              <div className="flex justify-between">
                <span className="font-medium">Effectiveness:</span>
                <span>{(props.suggestion.effectiveness * 100).toFixed(1)}%</span>
              </div>
            </div>
          </div>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
};

export default FilteredSuggestion;
