/**
 * @author Junaid Atari <mj.atari@gmail.com>
 * @copyright 2025 Junaid Atari
 * @see https://github.com/blacksmoke26
 */

export const bodyProperties = {
  text: {
    type: 'string',
    description:
      'The main input text to be processed or enhanced. This is the core content that the model will work with.',
    examples: ['Analyze the dataset and generate a summary'],
  },
  systemPrompt: {
    type: 'string',
    description:
      "The system message that sets the context or rules for the model's behavior. This is typically used to define the model's role or constraints.",
    examples: ['You are a data analyst specializing in financial trends.'],
  },
  format: {
    type: 'string',
    description:
      'The desired format of the output. Supported formats include JSON, Markdown, plain text, HTML, XML, YAML, and CSV.',
    enum: ['json', 'markdown', 'text', 'html', 'xml', 'yaml', 'csv'],
    examples: ['markdown'],
  },
  userRole: {
    type: 'string',
    description:
      'The role the user is playing in the interaction. This defines the context for how the model should interpret and respond to the input.',
    examples: ['data scientist'],
  },
  enhancementType: {
    type: 'string',
    description:
      'The type of enhancement or transformation to apply to the input text. This could include summarization, translation, formatting, etc.',
    examples: ['summarize'],
  },
  provider: {
    type: 'string',
    description:
      "Optional: The AI provider to use (e.g., 'OpenAI', 'Anthropic', 'Google').",
    examples: ['Anthropic'],
  },
  model: {
    type: 'string',
    description: 'Optional: The specific model name or identifier to use.',
    examples: ['claude-3-5-sonnet'],
  },
  targetAudience: {
    type: 'string',
    description:
      'Optional: The target audience for the output content. This influences tone, complexity, and language choices.',
    examples: ['technical audience'],
  },
  tone: {
    type: 'string',
    description:
      'Optional: The tone of the output (e.g., formal, casual, professional).',
    examples: ['professional'],
  },
  responseLength: {
    type: 'string',
    description:
      "Optional: The desired length of the output response. Common values: 'short', 'medium', 'long', 'extensive'.",
    examples: ['medium'],
  },
  customInstructions: {
    type: 'string',
    description:
      'Optional: Custom instructions to supplement the main prompt. These are additional guidelines for the model to follow.',
    examples: ['Include a table of key findings'],
  },
  temperature: {
    type: 'number',
    description:
      'Optional: Controls the randomness of the output. Lower values make the output more deterministic.',
    minimum: 0,
    maximum: 2,
    default: 0.7,
    examples: [0.5],
  },
  maxTokens: {
    type: 'integer',
    description:
      'Optional: Maximum number of tokens (words) to generate in the output.',
    minimum: 1,
    examples: [1024],
  },
  topP: {
    type: 'number',
    description:
      'Optional: Controls the diversity of the generated text. Higher values allow for more diverse outputs.',
    minimum: 0,
    maximum: 1,
    examples: [0.95],
  },
  topK: {
    type: 'integer',
    description:
      'Optional: Controls the diversity of the generated text based on token probabilities.',
    minimum: 1,
    examples: [50],
  },
  frequencyPenalty: {
    type: 'number',
    description:
      'Optional: Penalizes frequent token usage to reduce repetition.',
    minimum: -2,
    maximum: 2,
    examples: [0.2],
  },
  presencePenalty: {
    type: 'number',
    description:
      'Optional: Penalizes new topic introduction to keep the response focused.',
    minimum: -2,
    maximum: 2,
    examples: [0.1],
  },
  stopSequences: {
    type: 'array',
    items: {
      type: 'string',
    },
    description: 'Optional: Sequences to stop token generation at.',
    examples: [['<END>', '<STOP>']],
  },
  timestamp: {
    type: 'string',
    format: 'date-time',
    description:
      'Optional: Timestamp for tracking when the prompt was created.',
    examples: ['2023-10-05T14:30:00Z'],
  },
  conversationId: {
    type: 'string',
    description: 'Optional: Unique identifier for the conversation or session.',
    examples: ['chat_12345'],
  },
  offTheRecord: {
    type: 'boolean',
    description:
      'Optional: If true, the response will not be tied to previous interactions.',
    examples: [true],
  },
  enhancementParameters: {
    type: 'object',
    additionalProperties: true,
    description:
      'Optional: Custom parameters for the enhancement process. This allows passing arbitrary metadata or configuration.',
    examples: [{ theme: 'dark', version: '2.1' }],
  },
  cognitiveLoad: {
    type: 'string',
    enum: ['low', 'medium', 'high'],
    description:
      "The cognitive load required to understand the content. Options: 'low' (simple concepts), 'medium', 'high' (complex analysis).",
    examples: ['medium'],
  },
  informationDensity: {
    type: 'string',
    enum: ['sparse', 'balanced', 'dense'],
    description:
      "The density of information per concept in the output. Options: 'sparse' (brief), 'balanced', 'dense' (detailed).",
    examples: ['balanced'],
  },
  abstractionLevel: {
    type: 'string',
    enum: ['concrete', 'abstract', 'mixed'],
    description:
      "The level of abstraction in the content. Options: 'concrete' (specific examples), 'abstract', 'mixed'.",
    examples: ['mixed'],
  },
  metaphorUsage: {
    type: 'string',
    enum: ['none', 'light', 'heavy'],
    description:
      "The use of metaphors in the output. Options: 'none', 'light' (occasional), 'heavy' (figurative language).",
    examples: ['light'],
  },
  ambiguityTolerance: {
    type: 'string',
    enum: ['low', 'medium', 'high'],
    description:
      "The tolerance for ambiguity in the content. Options: 'low' (precise), 'medium', 'high' (open-ended).",
    examples: ['medium'],
  },
  sentenceStructure: {
    type: 'string',
    enum: ['simple', 'compound', 'complex', 'varied'],
    description:
      "The complexity of sentence structures in the output. Options: 'simple', 'compound', 'complex', 'varied'.",
    examples: ['varied'],
  },
  paragraphFlow: {
    type: 'string',
    enum: ['linear', 'circular', 'pyramidal'],
    description:
      "The flow pattern of paragraphs in the output. Options: 'linear' (sequential), 'circular' (repetitive), 'pyramidal'.",
    examples: ['linear'],
  },
  listStyle: {
    type: 'string',
    enum: ['bulleted', 'numbered', 'inline', 'none'],
    description:
      "The style of lists used in the output. Options: 'bulleted', 'numbered', 'inline', 'none'.",
    examples: ['bulleted'],
  },
  headingHierarchy: {
    type: 'boolean',
    description:
      'Whether to include a hierarchical structure of headings in the output.',
    examples: [true],
  },
  culturalContext: {
    type: 'string',
    description:
      'The cultural context to consider when generating the content.',
    examples: ['US-West'],
  },
  domainSpecificity: {
    type: 'string',
    description: 'The specific domain or subject area of the content.',
    examples: ['Quantum Physics'],
  },
  technicalJargonLevel: {
    type: 'string',
    enum: ['none', 'layman', 'professional', 'academic'],
    description:
      "The level of technical jargon to use. Options: 'none', 'layman', 'professional', 'academic'.",
    examples: ['professional'],
  },
  regulatoryCompliance: {
    type: 'array',
    items: {
      type: 'string',
    },
    description: 'Regulatory compliance requirements for the output.',
    examples: [['GDPR', 'HIPAA']],
  },
  emotionalIntensity: {
    type: 'integer',
    minimum: 1,
    maximum: 10,
    description:
      'The intensity of emotional expression in the output. Range: 1 (flat) to 10 (passionate).',
    examples: [7],
  },
  persuasionTechnique: {
    type: 'string',
    enum: ['ethos', 'pathos', 'logos', 'kairos'],
    description:
      "The persuasion technique to use. Options: 'ethos' (credibility), 'pathos' (emotion), 'logos' (logic), 'kairos' (timing).",
    examples: ['logos'],
  },
  empathyLevel: {
    type: 'integer',
    minimum: 1,
    maximum: 10,
    description:
      'The level of empathy to express in the output. Range: 1 (neutral) to 10 (deep empathy).',
    examples: [5],
  },
  strictness: {
    type: 'integer',
    minimum: 1,
    maximum: 10,
    description:
      'The strictness of output formatting constraints. Range: 1 (loose) to 10 (rigid).',
    examples: [6],
  },
  minimalOutput: {
    type: 'boolean',
    description:
      'If true, removes all conversational filler and focuses on core content.',
    examples: [true],
  },
  includeMetadata: {
    type: 'boolean',
    description:
      'If true, appends metadata about the reasoning process to the output.',
    examples: [false],
  },
  language: {
    type: 'string',
    pattern: '^[a-z]{2}(-[A-Z]{2})?$',
    description: 'The language code for the output (ISO 639-1 standard).',
    examples: ['en'],
  },
  encoding: {
    type: 'string',
    enum: ['utf-8', 'ascii'],
    description: 'The character encoding to use for the output.',
    examples: ['utf-8'],
  },
  experience: {
    type: 'string',
    enum: [
      '1 day',
      '1 week',
      '1 month',
      '3 months',
      '6 months',
      '1 year',
      '3 years',
      '5 years',
      '10 years',
      '30 years',
      '50 years',
      '100 years',
      'expert',
      'master',
      'nexus',
    ],
    description:
      'The amount of practical experience the persona should demonstrate.',
    examples: ['1 year'],
  },
  experienceLevel: {
    type: 'number',
    minimum: 0,
    description:
      'The current experience level as a number (for more granular control). Combined with experience, this determines the depth of knowledge and reasoning patterns.',
    examples: [5.7],
  },
  timeHorizon: {
    type: 'string',
    enum: [
      'short-term',
      'medium-term',
      'long-term',
      'enterprise',
      'centennial',
    ],
    description:
      'The time horizon for considering long-term consequences and future implications.',
    examples: ['short-term'],
  },
  domainExpertise: {
    type: 'string',
    description: 'The type of domain expertise to focus on.',
    examples: ['quantum_computing'],
  },
  skills: {
    type: 'array',
    items: {
      type: 'string',
    },
    description:
      "Specific skills or capabilities that define the persona's expertise.",
    examples: [['data_analysis', 'machine_learning', 'statistics']],
  },
  skillProficiency: {
    type: 'object',
    additionalProperties: {
      type: 'number',
      minimum: 0,
      maximum: 10,
    },
    description: 'The proficiency level for each skill (0-10 scale).',
    examples: [{ data_analysis: 9, machine_learning: 8.5 }],
  },
  learningCurve: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The learning curve adjustment (0.0-1.0). Higher values mean the model learns new concepts faster.',
    examples: [0.7],
  },
  retentionRate: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The retention rate for knowledge (0.0-1.0). Higher values mean information sticks better.',
    examples: [0.85],
  },
  acquisitionSpeed: {
    type: 'integer',
    minimum: 1,
    maximum: 100,
    description: 'The speed of knowledge acquisition (1-100).',
    examples: [45],
  },
  knowledgeDepth: {
    type: 'integer',
    minimum: 1,
    maximum: 10,
    description:
      'The depth of knowledge (1-10). Determines how thoroughly the model understands concepts.',
    examples: [8],
  },
  knowledgeBreadth: {
    type: 'integer',
    minimum: 1,
    maximum: 10,
    description:
      'The breadth of knowledge (1-10). Determines how many related topics the model is familiar with.',
    examples: [7],
  },
  reasoningDepth: {
    type: 'integer',
    minimum: 1,
    maximum: 10,
    description:
      'The experience-based reasoning depth (1-10). Higher values indicate more sophisticated reasoning patterns.',
    examples: [6],
  },
  thinkingPattern: {
    type: 'string',
    enum: [
      'linear',
      'synthetic',
      'hierarchical',
      'network',
      'holistic',
      'combinatorial',
      'differential',
      'evolutionary',
    ],
    description: 'The type of thinking patterns the persona employs.',
    examples: ['synthetic'],
  },
  problemSolvingApproach: {
    type: 'string',
    enum: [
      'analytical',
      'intuitive',
      'empirical',
      'theoretical',
      'heuristic',
      'algorithmic',
      'adaptive',
    ],
    description: 'The problem-solving approach preference.',
    examples: ['analytical'],
  },
  patternRecognitionSensitivity: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The pattern recognition sensitivity (0.0-1.0). Higher values mean the model recognizes patterns more quickly.',
    examples: [0.8],
  },
  contextSensitivity: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The experience-based context sensitivity (0.0-1.0). Higher values mean the model adapts better to context.',
    examples: [0.75],
  },
  adaptability: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The adaptability to new information (0.0-1.0). Higher values mean the model updates knowledge better.',
    examples: [0.9],
  },
  crossDomainTransfer: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The cross-domain knowledge transfer capability (0.0-1.0). Higher values mean the model can apply knowledge across domains.',
    examples: [0.65],
  },
  historicalDepth: {
    type: 'string',
    enum: [
      'none',
      'brief',
      'thorough',
      'historical',
      'mythological',
      'shallow',
      'moderate',
      'deep',
      'encyclopedic',
      'archival',
    ],
    description: 'The depth of historical knowledge to draw upon.',
    examples: ['deep'],
  },
  expertiseFocus: {
    type: 'string',
    enum: ['generalist', 'specialist', 'expertise_dominant', 'comprehensive'],
    description: 'The focus of expertise (specific domain vs generalist).',
    examples: ['specialist'],
  },
  domainSpecialization: {
    type: 'integer',
    minimum: 0,
    maximum: 10,
    description:
      'The level of domain specialization (0-10). Higher values mean deeper specialization.',
    examples: [9],
  },
  lateralThinking: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The level of lateral thinking capability (0.0-1.0). Higher values mean the model can think outside conventional patterns.',
    examples: [0.85],
  },
  systemsThinking: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The level of systems thinking capability (0.0-1.0). Higher values mean the model can see interconnected systems.',
    examples: [0.8],
  },
  criticalThinking: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The level of critical thinking capability (0.0-1.0). Higher values mean the model can critically evaluate information.',
    examples: [0.9],
  },
  creativeThinking: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The level of creative thinking capability (0.0-1.0). Higher values mean the model can generate novel ideas.',
    examples: [0.75],
  },
  analyticalThinking: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The level of analytical thinking capability (0.0-1.0). Higher values mean the model can break down complex problems.',
    examples: [0.85],
  },
  experientialLearning: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The level of experiential learning capability (0.0-1.0). Higher values mean the model learns from experience effectively.',
    examples: [0.9],
  },
  theoreticalUnderstanding: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The level of theoretical understanding (0.0-1.0). Higher values mean the model has deeper theoretical knowledge.',
    examples: [0.8],
  },
  practicalApplication: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The level of practical application skill (0.0-1.0). Higher values mean the model applies knowledge effectively.',
    examples: [0.85],
  },
  synthesisCapability: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The level of synthesis capability (0.0-1.0). Higher values mean the model can combine ideas effectively.',
    examples: [0.8],
  },
  evaluationCapability: {
    type: 'number',
    minimum: 0,
    maximum: 1,
    description:
      'The level of evaluation capability (0.0-1.0). Higher values mean the model can assess information effectively.',
    examples: [0.85],
  },
  writingStyle: {
    type: 'string',
    description:
      'The writing style of the output. Options include: formal, casual, academic, technical, creative, analytical, and many others.',
    examples: ['analytical'],
  },
  detailLevel: {
    type: 'string',
    enum: [
      'ultra-minimal',
      'minimal',
      'concise',
      'moderate',
      'detailed',
      'comprehensive',
      'ultra-detailed',
    ],
    description: 'The level of detail in explanations.',
    examples: ['detailed'],
  },
  narrativePerspective: {
    type: 'string',
    enum: [
      'first-person',
      'third-person',
      'second-person',
      'omniscient',
      'limited',
      'objective',
    ],
    description: 'The narrative perspective to use.',
    examples: ['third-person'],
  },
  exampleSpecificity: {
    type: 'string',
    enum: [
      'none',
      'general',
      'specific',
      'concrete',
      'hypothetical',
      'real-world',
    ],
    description: 'The level of specificity in examples.',
    examples: ['concrete'],
  },
  dataGranularity: {
    type: 'string',
    enum: ['aggregated', 'summary', 'detailed', 'comprehensive', 'raw'],
    description: 'The level of detail in data presentations.',
    examples: ['detailed'],
  },
  technicalDepth: {
    type: 'string',
    enum: [
      'layman',
      'basic',
      'intermediate',
      'advanced',
      'expert',
      'academic',
      'proprietary',
    ],
    description: 'The level of technical detail in explanations.',
    examples: ['intermediate'],
  },
  geographicScope: {
    type: 'string',
    enum: [
      'global',
      'regional',
      'national',
      'local',
      'hyper-local',
      'specific-venue',
    ],
    description: 'The level of geographic specificity.',
    examples: ['regional'],
  },
  temporalScope: {
    type: 'string',
    enum: [
      'eternal',
      'historical',
      'contemporary',
      'immediate',
      'future',
      'archived',
    ],
    description: 'The level of temporal specificity.',
    examples: ['contemporary'],
  },
  argumentationStyle: {
    type: 'string',
    enum: [
      'deductive',
      'inductive',
      'abductive',
      'rhetorical',
      'dialectical',
      'heuristic',
      'heuristic_dialectical',
    ],
    description: 'The style of argumentation.',
    examples: ['inductive'],
  },
  outputFormat: {
    type: 'string',
    enum: [
      'code',
      'inline_code',
      'markdown',
      'plaintext',
      'json',
      'yaml',
      'xml',
      'csv',
      'tsv',
      'binary',
      'html',
      'markdown_code',
      'markdown_inline',
      'markdown_text',
      'markdown_yaml',
      'markdown_xml',
    ],
    description: 'The format of code or structured output.',
    examples: ['code'],
  },
  visualComplexity: {
    type: 'string',
    enum: [
      'minimal',
      'moderate',
      'complex',
      'elaborate',
      'schematic',
      'diagrammatic',
      'graphical',
      'charted',
      'map-based',
      'flow-based',
      'tree-based',
      'network-based',
      'grid-based',
      'spatial',
      '3d',
      'multidimensional',
      'holographic',
      'augmented',
    ],
    description: 'The level of visual complexity in explanations.',
    examples: ['moderate'],
  },
  mathematicalDetail: {
    type: 'string',
    enum: [
      'none',
      'conceptual',
      'simplified',
      'formal',
      'detailed',
      'step-by-step',
      'proof-based',
      'derivation-based',
      'numerical',
      'theoretical',
      'computational',
      'statistical',
      'analytical',
      'graph-theoretic',
      'logic-based',
      'probability-based',
      'differential',
      'integral',
      'matrix',
      'tensor',
      'linear-algebra',
      'dynamical-systems',
      'chaos-theory',
      'quantum',
      'relativistic',
      'field-theory',
    ],
    description: 'The level of mathematical detail.',
    examples: ['detailed'],
  },
  biologicalDetail: {
    type: 'string',
    enum: [
      'none',
      'conceptual',
      'simplified',
      'detailed',
      'cellular',
      'molecular',
      'genetic',
      'epigenetic',
      'systems-biology',
      'neuro-biological',
      'immunological',
      'ecological',
      'evolutionary',
      'developmental',
      'physiological',
      'pathological',
      'pharmacological',
      'biotechnological',
      'bioethical',
    ],
    description: 'The level of biological detail.',
    examples: ['detailed'],
  },
  chemicalDetail: {
    type: 'string',
    enum: [
      'none',
      'conceptual',
      'simplified',
      'detailed',
      'elemental',
      'molecular',
      'organic',
      'inorganic',
      'biochemical',
      'pharmaceutical',
      'industrial',
      'environmental',
      'nanotechnology',
      'molecular-chemistry',
      'spectroscopy',
      'thermodynamics',
      'kinetics',
      'catalysis',
      'materials-science',
      'surface-chemistry',
    ],
    description: 'The level of chemical detail.',
    examples: ['detailed'],
  },
  physicsDetail: {
    type: 'string',
    enum: [
      'none',
      'conceptual',
      'simplified',
      'detailed',
      'classical',
      'mechanics',
      'electromagnetism',
      'thermodynamics',
      'quantum',
      'relativistic',
      'astrophysics',
      'cosmology',
      'particle',
      'nuclear',
      'condensed-matter',
      'statistical',
      'fluid',
      'optical',
      'acoustic',
      'thermal',
      'magnetic',
      'electronic',
      'superconducting',
      'nano-physics',
      'field-theory',
      'string-theory',
      'quantum-gravity',
      'high-energy',
    ],
    description: 'The level of physics detail.',
    examples: ['detailed'],
  },
  environmentalDetail: {
    type: 'string',
    enum: [
      'none',
      'conceptual',
      'simplified',
      'detailed',
      'ecosystem',
      'biotic',
      'abiotic',
      'climatic',
      'geographic',
      'hydrological',
      'atmospheric',
      'oceanic',
      'terrestrial',
      'wildlife',
      'pollution',
      'conservation',
      'sustainability',
      'climate-change',
      'greenhouse',
      'carbon-cycle',
      'ozone',
      'acid-rain',
      'deforestation',
      'desertification',
      'biodiversity',
      'ecosystem-services',
      'ecosystem-restoration',
    ],
    description: 'The level of environmental detail.',
    examples: ['detailed'],
  },
  economicDetail: {
    type: 'string',
    enum: [
      'none',
      'conceptual',
      'simplified',
      'detailed',
      'micro',
      'macro',
      'developmental',
      'international',
      'monetary',
      'fiscal',
      'trade',
      'industrial',
      'financial',
      'labor',
      'resource',
      'environmental',
      'public',
      'public-works',
      'urban',
      'rural',
      'agricultural',
      'market',
      'capital',
      'entrepreneurship',
      'innovation',
      'digital',
      'knowledge',
      'global',
      'regional',
      'local',
      'sectoral',
      'financial-institutions',
      'central-banking',
      'monetary-policy',
      'fiscal-policy',
    ],
    description: 'The level of economic detail.',
    examples: ['detailed'],
  },
  socialDetail: {
    type: 'string',
    enum: [
      'none',
      'conceptual',
      'simplified',
      'detailed',
      'demographic',
      'social-structures',
      'social-interaction',
      'social-identity',
      'social-dynamics',
      'social-network',
      'social-change',
      'social-problem',
      'social-policy',
      'social-movement',
      'social-media',
      'digital-culture',
      'subculture',
      'counter-culture',
      'culture',
      'cultural-studies',
      'anthropology',
      'sociology',
      'psychology',
      'neuroscience',
      'cognitive',
      'behavioral',
      'psychological',
      'emotional',
      'emotional-intelligence',
      'emotional-regulation',
      'emotional-expression',
      'emotional-awareness',
      'emotional-integrity',
      'emotional-stability',
      'emotional-harmony',
      'emotional-balance',
      'emotional-resilience',
    ],
    description: 'The level of social detail.',
    examples: ['detailed'],
  },
  technologicalDetail: {
    type: 'string',
    enum: [
      'none',
      'conceptual',
      'simplified',
      'detailed',
      'computer-science',
      'software',
      'hardware',
      'ai',
      'machine-learning',
      'deep-learning',
      'neural-network',
      'nlp',
      'computer-vision',
      'robotics',
      'cybersecurity',
      'network',
      'communication',
      'storage',
      'processing',
      'data',
      'database',
      'algorithm',
      'programming',
      'coding',
      'web',
      'mobile',
      'iot',
      'embedded',
      'wearable',
      'biotech',
      'biomedical',
      'nanotech',
      'space',
      'energy',
      'transportation',
      'telecommunications',
      'information-technology',
      'digital',
      'smart',
      'connected',
      'autonomous',
      'blockchain',
      'distributed',
      'cloud',
      'edge',
      'quantum',
      'quantum-computing',
      'quantum-simulation',
      'quantum-optimization',
      'quantum-cryptography',
    ],
    description: 'The level of technological detail.',
    examples: ['detailed'],
  },
  psychologicalDetail: {
    type: 'string',
    enum: [
      'none',
      'conceptual',
      'simplified',
      'detailed',
      'cognitive',
      'emotional',
      'behavioral',
      'social',
      'developmental',
      'clinical',
      'health',
      'abnormal',
      'personality',
      'neuropsychology',
      'consciousness',
      'awareness',
      'attention',
      'memory',
      'language',
      'perception',
      'motivation',
      'emotion',
      'value',
      'belief',
      'concept',
      'attitude',
      'behavior',
      'cognition',
      'learning',
      'stress',
      'anxiety',
      'depression',
      'resilience',
      'well-being',
      'happiness',
      'satisfaction',
      'fulfillment',
      'meaning',
      'purpose',
      'growth',
      'development',
      'maturation',
      'aging',
      'lifespan',
      'life-course',
      'adolescence',
      'adulthood',
      'midlife',
      'old-age',
      'end-of-life',
      'death',
      'spirituality',
      'religious',
      'transpersonal',
      'self',
      'self-concept',
      'self-esteem',
      'self-awareness',
      'self-determination',
      'self-regulation',
      'self-efficacy',
    ],
    description: 'The level of psychological detail.',
    examples: ['detailed'],
  },
  artisticDetail: {
    type: 'string',
    enum: [
      'none',
      'conceptual',
      'simplified',
      'detailed',
      'visual',
      'musical',
      'literary',
      'performing',
      'cinematic',
      'photographic',
      'digital',
      'traditional',
      'contemporary',
      'classical',
      'modern',
      'abstract',
      'realistic',
      'surreal',
      'expressionist',
      'impressionist',
      'minimalist',
      'maximalist',
      'installation',
      'performance',
      'mixed-media',
      'digital-art',
      'generative',
      'algorithmic',
      'procedural',
      'interactive',
      'immersive',
      'experiential',
    ],
    description: 'The level of artistic detail.',
    examples: ['detailed'],
  },
  philosophicalDetail: {
    type: 'string',
    enum: [
      'none',
      'conceptual',
      'simplified',
      'detailed',
      'metaphysics',
      'epistemology',
      'ontology',
      'ethics',
      'aesthetics',
      'logic',
      'mind',
      'philosophy-of-mind',
      'philosophy-of-language',
      'philosophy-of-science',
      'philosophy-of-technology',
      'philosophy-of-religion',
      'philosophy-of-politics',
      'philosophy-of-law',
      'philosophy-of-art',
      'philosophy-of-culture',
      'philosophy-of-history',
      'philosophy-of-nature',
      'philosophy-of-society',
      'philosophy-of-humanity',
      'philosophy-of-life',
      'philosophy-of-consciousness',
      'philosophy-of-wisdom',
      'philosophy-of-knowing',
      'philosophy-of-understanding',
      'philosophy-of-believing',
      'philosophy-of-trusting',
      'philosophy-of-expecting',
      'philosophy-of-hoping',
      'philosophy-of-praying',
      'philosophy-of-worshiping',
      'philosophy-of-sacrificing',
      'philosophy-of-suffering',
      'philosophy-of-death',
      'philosophy-of-spirituality',
      'philosophy-of-mysticism',
      'philosophy-of-magic',
      'philosophy-of-transformation',
      'philosophy-of-evolution',
      'philosophy-of-creation',
      'philosophy-of-destruction',
      'philosophy-of-the-universe',
      'philosophy-of-existence',
      'philosophy-of-being',
      'philosophy-of-becoming',
      'philosophy-of-time',
      'philosophy-of-space',
      'philosophy-of-cosmos',
      'philosophy-of-the-absolute',
      'philosophy-of-the-infinite',
      'philosophy-of-the-eternal',
    ],
    description: 'The level of philosophical detail.',
    examples: ['detailed'],
  },
};
