/**
 * @author Junaid Atari <mj.atari@gmail.com>
 * @copyright 2025 Junaid Atari
 * @see https://github.com/blacksmoke26
 */

import type { PromptTemplate } from './types';

const promptTemplates: PromptTemplate[] = [
  {
    title: 'Patient Discharge Summary',
    description: 'Generate medical discharge summaries',
    category: 'healthcare',
    tags: ['medical', 'clinical', 'documentation'],
    content:
      'Generate a professional discharge summary for a patient.\n\nPatient Name: {{patient_name}}\nAdmission Date: {{admission_date}}\nDischarge Date: {{discharge_date}}\nDiagnosis: {{diagnosis}}\nProcedures Performed: {{procedures}}\n\nInclude:\n1. History of Present Illness\n2. Hospital Course\n3. Discharge Medications\n4. Discharge Diet: {{diet}}\n5. Activity Level: {{activity_level}}\n6. Follow-up Instructions\n7. Red Flags (when to return to ER)\n\nSpecialist Consults: {{consults}}',
    variables: [
      {
        name: 'patient_name',
        description: 'Patient Name (Use generic or "Patient X")',
        type: 'string',
        required: true,
      },
      {
        name: 'admission_date',
        description: 'Admission Date',
        type: 'string',
        required: true,
      },
      {
        name: 'discharge_date',
        description: 'Discharge Date',
        type: 'string',
        required: true,
      },
      {
        name: 'diagnosis',
        description: 'Primary Diagnosis',
        type: 'string',
        required: true,
      },
      {
        name: 'procedures',
        description: 'Surgeries or procedures performed',
        type: 'string',
        required: true,
      },
      {
        name: 'diet',
        description: 'Prescribed Diet',
        type: 'select',
        options: ['Regular', 'Low Sodium', 'Diabetic', 'Renal', 'Full Liquid'],
        defaultValue: 'Regular',
      },
      {
        name: 'activity_level',
        description: 'Prescribed Activity',
        type: 'select',
        options: ['As Tolerated', 'Bed Rest', 'Ad Lib', 'Light Activity'],
        defaultValue: 'As Tolerated',
      },
      {
        name: 'consults',
        description: 'Consulting specialists',
        type: 'string',
        required: false,
      },
    ],
  },
  {
    title: 'Dietary Meal Plan',
    description: 'Generate personalized meal plans',
    category: 'healthcare',
    tags: ['nutrition', 'diet', 'health'],
    content:
      'Create a {{duration}} meal plan.\n\nCalories: {{calories}}\nDietary Restrictions: {{restrictions}}\nAllergies: {{allergies}}\nGoal: {{goal}}\n\nProvide:\n1. Daily Macro Breakdown (Protein/Carbs/Fats)\n2. Meal Prep Schedule\n3. Grocery List\n4. {{num_meals}} meals per day\n5. Snack options\n\nCuisine Preference: {{cuisine}}',
    variables: [
      {
        name: 'duration',
        description: 'Plan Duration',
        type: 'select',
        options: ['1 Day', '1 Week', '2 Weeks', '1 Month'],
        defaultValue: '1 Week',
      },
      {
        name: 'calories',
        description: 'Daily Calorie Target',
        type: 'number',
        required: true,
      },
      {
        name: 'restrictions',
        description: 'Diet Type',
        type: 'select',
        options: [
          'None',
          'Keto',
          'Vegan',
          'Paleo',
          'Low Carb',
          'Mediterranean',
        ],
        defaultValue: 'None',
      },
      {
        name: 'allergies',
        description: 'Food Allergies',
        type: 'string',
        required: false,
      },
      {
        name: 'goal',
        description: 'Health Goal',
        type: 'select',
        options: ['Weight Loss', 'Muscle Gain', 'Maintenance', 'Energy Boost'],
        defaultValue: 'Maintenance',
      },
      {
        name: 'num_meals',
        description: 'Meals per day',
        type: 'number',
        defaultValue: 3,
      },
      {
        name: 'cuisine',
        description: 'Preferred Cuisine',
        type: 'select',
        options: [
          'Italian',
          'Asian',
          'Mexican',
          'American',
          'Mediterranean',
          'Mix',
        ],
        defaultValue: 'Mix',
      },
    ],
  },
  {
    title: 'Physics Problem Solver',
    description: 'Solve physics problems step-by-step',
    category: 'science',
    tags: ['physics', 'stem', 'education'],
    content:
      'Solve this physics problem:\n\n{{problem_statement}}\n\nGiven Variables:\n- {{var1_name}} = {{var1_value}}\n- {{var2_name}} = {{var2_value}}\n\nRequired Output: {{unknown_variable}}\n\nProvide:\n1. Identification of Physics Principles/Laws\n2. Knowns and Unknowns list\n3. Formula selection\n4. Step-by-step derivation\n5. Final Answer with Units\n6. Significant figures check\n\nTopic: {{topic}}',
    variables: [
      {
        name: 'problem_statement',
        description: 'Description of the problem',
        type: 'string',
        required: true,
      },
      {
        name: 'var1_name',
        description: 'First variable name',
        type: 'string',
        required: true,
      },
      {
        name: 'var1_value',
        description: 'First variable value',
        type: 'string',
        required: true,
      },
      {
        name: 'var2_name',
        description: 'Second variable name',
        type: 'string',
        required: true,
      },
      {
        name: 'var2_value',
        description: 'Second variable value',
        type: 'string',
        required: true,
      },
      {
        name: 'unknown_variable',
        description: 'What needs to be solved',
        type: 'string',
        required: true,
      },
      {
        name: 'topic',
        description: 'Physics Topic',
        type: 'select',
        options: [
          'Kinematics',
          'Dynamics',
          'Energy',
          'Momentum',
          'Waves',
          'Electromagnetism',
          'Thermodynamics',
        ],
        defaultValue: 'Kinematics',
      },
    ],
  },
  {
    title: 'Lab Report Structure',
    description: 'Generate structure for scientific lab reports',
    category: 'science',
    tags: ['lab', 'research', 'chemistry'],
    content:
      'Create a structure for a lab report on {{experiment_title}}.\n\nCourse: {{course}}\n\nInclude sections:\n1. Abstract\n2. Introduction\n   - Background\n   - Hypothesis: {{hypothesis}}\n3. Materials and Methods\n4. Results\n   - Data Tables\n   - Graphs description\n5. Discussion\n   - Analysis of {{results_summary}}\n   - Sources of Error\n6. Conclusion\n7. References\n\nData Type: {{data_type}}',
    variables: [
      {
        name: 'experiment_title',
        description: 'Title of Experiment',
        type: 'string',
        required: true,
      },
      {
        name: 'course',
        description: 'Course Name',
        type: 'string',
        required: true,
      },
      {
        name: 'hypothesis',
        description: 'Initial Hypothesis',
        type: 'string',
        required: true,
      },
      {
        name: 'results_summary',
        description: 'Brief summary of findings',
        type: 'string',
        required: true,
      },
      {
        name: 'data_type',
        description: 'Type of data collected',
        type: 'select',
        options: ['Quantitative', 'Qualitative', 'Both'],
        defaultValue: 'Quantitative',
      },
    ],
  },
  {
    title: 'Standard Operating Procedure (SOP)',
    description: 'Generate industrial/engineering SOPs',
    category: 'engineering',
    tags: ['manufacturing', 'safety', 'process'],
    content:
      'Create a Standard Operating Procedure for: {{process_name}}.\n\nDepartment: {{department}}\nEquipment: {{equipment}}\n\nStructure:\n1. Purpose\n2. Scope\n3. Responsibilities\n4. PPE Requirements: {{ppe}}\n5. Pre-Operation Checks\n6. Step-by-Step Instructions ({{num_steps}} steps)\n7. Troubleshooting\n8. Emergency Shutdown\n9. Clean-up\n\nRisk Level: {{risk_level}}',
    variables: [
      {
        name: 'process_name',
        description: 'Name of the process',
        type: 'string',
        required: true,
      },
      {
        name: 'department',
        description: 'Department',
        type: 'string',
        required: true,
      },
      {
        name: 'equipment',
        description: 'Machinery/Equipment involved',
        type: 'string',
        required: true,
      },
      {
        name: 'ppe',
        description: 'Required PPE',
        type: 'string',
        required: true,
      },
      {
        name: 'num_steps',
        description: 'Number of procedural steps',
        type: 'number',
        defaultValue: 10,
      },
      {
        name: 'risk_level',
        description: 'Risk Assessment Level',
        type: 'select',
        options: ['Low', 'Medium', 'High', 'Critical'],
        defaultValue: 'Medium',
      },
    ],
  },
  {
    title: '3D Printing Slicer Settings',
    description: 'Generate G-Code or Slicer settings',
    category: 'engineering',
    tags: ['3d-printing', 'manufacturing', 'cnc'],
    content:
      'Generate Slicer settings for {{model_name}}.\n\nPrinter: {{printer_model}}\nFilament: {{filament_type}}\n\nApplication: {{application}}\n\nSettings to define:\n1. Layer Height: {{layer_height}}\n2. Infill Percentage: {{infill}}%\n3. Infill Pattern: {{infill_pattern}}\n4. Print Speed\n5. Support Settings ({{supports}})\n6. Bed Temperature\n7. Nozzle Temperature\n8. Cooling Fan\n9. Adhesion Type\n\nPost-Processing: {{post_processing}}',
    variables: [
      {
        name: 'model_name',
        description: 'Name of the model',
        type: 'string',
        required: true,
      },
      {
        name: 'printer_model',
        description: '3D Printer Model',
        type: 'string',
        required: true,
      },
      {
        name: 'filament_type',
        description: 'Filament Material',
        type: 'select',
        options: ['PLA', 'PETG', 'ABS', 'TPU', 'ASA', 'Nylon'],
        defaultValue: 'PLA',
      },
      {
        name: 'application',
        description: 'Use case',
        type: 'select',
        options: [
          'Visual Prototype',
          'Functional Part',
          'Flexible Part',
          'High Temp',
        ],
        defaultValue: 'Visual Prototype',
      },
      {
        name: 'layer_height',
        description: 'Layer Height (mm)',
        type: 'select',
        options: ['0.12 (Fine)', '0.2 (Standard)', '0.28 (Draft)'],
        defaultValue: '0.2 (Standard)',
      },
      {
        name: 'infill',
        description: 'Infill %',
        type: 'number',
        defaultValue: 20,
      },
      {
        name: 'infill_pattern',
        description: 'Infill Pattern',
        type: 'select',
        options: ['Grid', 'Gyroid', 'Triangular', 'Honeycomb'],
        defaultValue: 'Gyroid',
      },
      {
        name: 'supports',
        description: 'Support Type',
        type: 'select',
        options: ['None', 'Tree Supports', 'Linear Supports'],
        defaultValue: 'Tree Supports',
      },
      {
        name: 'post_processing',
        description: 'Required cleanup',
        type: 'string',
        required: false,
      },
    ],
  },
  {
    title: 'Circuit Design Specification',
    description: 'Generate electronic circuit specs',
    category: 'engineering',
    tags: ['electronics', 'hardware', 'pcb'],
    content:
      'Generate specifications for a circuit board.\n\nFunction: {{function}}\nInput Voltage: {{input_voltage}}\nOutput Requirements: {{output_requirements}}\n\nInclude:\n1. Block Diagram Description\n2. Component List (Microcontroller, Sensors, Power Reg)\n3. Communication Protocols: {{protocols}}\n4. PCB Constraints (Size: {{pcb_size}})\n5. Power Consumption Estimates\n6. Heat Dissipation Strategy\n7. Safety Features\n\nEnvironment: {{environment}}',
    variables: [
      {
        name: 'function',
        description: 'Primary function of the circuit',
        type: 'string',
        required: true,
      },
      {
        name: 'input_voltage',
        description: 'Input Voltage',
        type: 'string',
        required: true,
      },
      {
        name: 'output_requirements',
        description: 'What does it drive or output?',
        type: 'string',
        required: true,
      },
      {
        name: 'protocols',
        description: 'Communication needed',
        type: 'select',
        options: ['I2C', 'SPI', 'UART', 'USB', 'WiFi', 'BLE'],
        defaultValue: 'I2C',
      },
      {
        name: 'pcb_size',
        description: 'Max PCB dimensions',
        type: 'string',
        required: true,
      },
      {
        name: 'environment',
        description: 'Operating environment',
        type: 'select',
        options: ['Indoor', 'Outdoor', 'Industrial', 'Harsh'],
        defaultValue: 'Indoor',
      },
    ],
  },
  {
    title: 'Travel Itinerary Planner',
    description: 'Generate detailed travel plans',
    category: 'lifestyle',
    tags: ['travel', 'vacation', 'planning'],
    content:
      'Plan a {{duration}} trip to {{destination}}.\n\nBudget: {{budget}}\nTravelers: {{num_travelers}}\nInterests: {{interests}}\n\nInclude:\n1. Day-by-Day Schedule\n2. Accommodation recommendations ({{accommodation_type}})\n3. Must-see attractions\n4. Hidden gems (off the beaten path)\n5. Restaurant suggestions ({{food_type}})\n6. Transportation tips\n7. Estimated daily costs\n\nPace: {{pace}}',
    variables: [
      {
        name: 'destination',
        description: 'City or Country',
        type: 'string',
        required: true,
      },
      {
        name: 'duration',
        description: 'Duration',
        type: 'string',
        required: true,
      },
      {
        name: 'budget',
        description: 'Total Budget',
        type: 'string',
        required: true,
      },
      {
        name: 'num_travelers',
        description: 'Number of People',
        type: 'number',
        defaultValue: 2,
      },
      {
        name: 'interests',
        description: 'Activities/Interests',
        type: 'string',
        required: true,
      },
      {
        name: 'accommodation_type',
        description: 'Lodging Style',
        type: 'select',
        options: ['Hostel', 'Boutique Hotel', 'Luxury', 'Airbnb', 'Camping'],
        defaultValue: 'Boutique Hotel',
      },
      {
        name: 'food_type',
        description: 'Dining preference',
        type: 'select',
        options: ['Street Food', 'Fine Dining', 'Mix', 'Vegetarian'],
        defaultValue: 'Mix',
      },
      {
        name: 'pace',
        description: 'Trip Pace',
        type: 'select',
        options: ['Relaxed', 'Balanced', 'Packed'],
        defaultValue: 'Balanced',
      },
    ],
  },
  {
    title: 'Real Estate Listing',
    description: 'Generate MLS listing descriptions',
    category: 'realestate',
    tags: ['real-estate', 'selling', 'marketing'],
    content:
      'Write a compelling MLS listing for:\n\nProperty Type: {{property_type}}\nLocation: {{location}}\nKey Features:\n{{features}}\n\nSpecs:\n- Beds: {{beds}}\n- Baths: {{baths}}\n- Sq Ft: {{sqft}}\n\nTone: {{tone}}\n\nInclude:\n1. Catchy Headline\n2. Emotional hook\n3. Feature highlights\n4. Neighborhood description\n5. Call to Action',
    variables: [
      {
        name: 'property_type',
        description: 'Type',
        type: 'select',
        options: ['Single Family', 'Condo', 'Townhouse', 'Multifamily', 'Land'],
        defaultValue: 'Single Family',
      },
      {
        name: 'location',
        description: 'Address/Neighborhood',
        type: 'string',
        required: true,
      },
      {
        name: 'features',
        description: 'Top 3 features (e.g., Pool, Updated Kitchen)',
        type: 'string',
        required: true,
      },
      {
        name: 'beds',
        description: 'Bedrooms',
        type: 'number',
        required: true,
      },
      {
        name: 'baths',
        description: 'Bathrooms',
        type: 'number',
        required: true,
      },
      {
        name: 'sqft',
        description: 'Square Footage',
        type: 'number',
        required: true,
      },
      {
        name: 'tone',
        description: 'Copy Tone',
        type: 'select',
        options: ['Luxurious', 'Cozy', 'Modern', 'Professional'],
        defaultValue: 'Professional',
      },
    ],
  },
  {
    title: 'Workout Routine',
    description: 'Generate fitness plans',
    category: 'lifestyle',
    tags: ['fitness', 'health', 'workout'],
    content:
      'Create a {{workout_type}} workout plan.\n\nExperience Level: {{level}}\nDuration: {{duration}} minutes\nEquipment: {{equipment}}\nGoal: {{goal}}\n\nProvide:\n1. Warm-up routine\n2. Main workout ({{num_exercises}} exercises)\n3. Sets and Reps\n4. Rest times\n5. Cool-down stretches\n\nDays per week: {{days}}',
    variables: [
      {
        name: 'workout_type',
        description: 'Focus',
        type: 'select',
        options: [
          'Full Body',
          'Upper Body',
          'Lower Body',
          'Cardio',
          'HIIT',
          'Yoga',
        ],
        defaultValue: 'Full Body',
      },
      {
        name: 'level',
        description: 'Fitness Level',
        type: 'select',
        options: ['Beginner', 'Intermediate', 'Advanced'],
        defaultValue: 'Intermediate',
      },
      {
        name: 'duration',
        description: 'Time available',
        type: 'number',
        defaultValue: 45,
      },
      {
        name: 'equipment',
        description: 'Equipment',
        type: 'select',
        options: ['None', 'Dumbbells', 'Barbell', 'Full Gym', 'Kettlebells'],
        defaultValue: 'None',
      },
      {
        name: 'goal',
        description: 'Primary Goal',
        type: 'select',
        options: ['Strength', 'Hypertrophy (Muscle)', 'Endurance', 'Fat Loss'],
        defaultValue: 'Strength',
      },
      {
        name: 'num_exercises',
        description: 'Number of exercises',
        type: 'number',
        defaultValue: 6,
      },
      {
        name: 'days',
        description: 'Frequency',
        type: 'number',
        defaultValue: 3,
      },
    ],
  },
  {
    title: 'Rental Lease Agreement',
    description: 'Generate residential lease terms',
    category: 'realestate',
    tags: ['real-estate', 'legal', 'rental'],
    content:
      'Draft a Lease Agreement for {{property_address}}.\n\nLandlord: {{landlord}}\nTenant: {{tenant}}\nTerm: {{term}}\nRent: {{rent}}\n\nInclude:\n1. Parties and Property\n2. Term and Rent\n3. Security Deposit: {{deposit}}\n4. Utilities Responsibility\n5. Pet Policy ({{pet_policy}})\n6. Maintenance Obligations\n7. Access Rights\n8. Termination Clause\n9. Late Fee Policy: {{late_fee}}',
    variables: [
      {
        name: 'property_address',
        description: 'Rental Property Address',
        type: 'string',
        required: true,
      },
      {
        name: 'landlord',
        description: 'Landlord Name',
        type: 'string',
        required: true,
      },
      {
        name: 'tenant',
        description: 'Tenant Name',
        type: 'string',
        required: true,
      },
      {
        name: 'term',
        description: 'Lease Duration',
        type: 'string',
        required: true,
      },
      {
        name: 'rent',
        description: 'Monthly Rent Amount',
        type: 'string',
        required: true,
      },
      {
        name: 'deposit',
        description: 'Security Deposit Amount',
        type: 'string',
        required: true,
      },
      {
        name: 'pet_policy',
        description: 'Are pets allowed?',
        type: 'boolean',
        defaultValue: false,
      },
      {
        name: 'late_fee',
        description: 'Late Fee Amount',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'Cold Email Outreach',
    description: 'Generate personalized cold emails',
    category: 'sales',
    tags: ['sales', 'email', 'outreach'],
    content:
      'Write a cold email to {{prospect_name}} at {{company_name}}.\n\nValue Prop: {{value_proposition}}\nPain Point: {{pain_point}}\n\nGoal: {{goal}}\n\nStructure:\n1. Subject Line ({{num_subjects}} options)\n2. Personalized Opening (Reference {{personalization}})\n3. The "Hook" (Addressing Pain Point)\n4. Social Proof ({{social_proof}})\n5. Soft Call to Action ({{cta}})\n\nTone: {{tone}}\nLength: {{length}}',
    variables: [
      {
        name: 'prospect_name',
        description: 'Prospect Name',
        type: 'string',
        required: true,
      },
      {
        name: 'company_name',
        description: 'Company Name',
        type: 'string',
        required: true,
      },
      {
        name: 'value_proposition',
        description: 'What do you offer?',
        type: 'string',
        required: true,
      },
      {
        name: 'pain_point',
        description: 'Problem to solve',
        type: 'string',
        required: true,
      },
      {
        name: 'goal',
        description: 'Desired outcome',
        type: 'select',
        options: ['Meeting', 'Call', 'Demo', 'Reply'],
        defaultValue: 'Reply',
      },
      {
        name: 'num_subjects',
        description: 'Subject line options',
        type: 'number',
        defaultValue: 3,
      },
      {
        name: 'personalization',
        description: 'Specific detail to mention (Recent post, etc.)',
        type: 'string',
        required: false,
      },
      {
        name: 'social_proof',
        description: 'Clients/Case studies to mention',
        type: 'string',
        required: false,
      },
      {
        name: 'cta',
        description: 'Call to Action',
        type: 'string',
        required: true,
      },
      {
        name: 'tone',
        description: 'Email Tone',
        type: 'select',
        options: ['Professional', 'Casual', 'Direct', 'Friendly'],
        defaultValue: 'Professional',
      },
      {
        name: 'length',
        description: 'Length',
        type: 'select',
        options: ['Short (50 words)', 'Medium (100 words)', 'Long'],
        defaultValue: 'Short (50 words)',
      },
    ],
  },
  {
    title: 'Sales Objection Handling',
    description: 'Generate responses to sales objections',
    category: 'sales',
    tags: ['sales', 'training', 'negotiation'],
    content:
      'Provide responses to the objection: "{{objection}}".\n\nProduct/Service: {{product}}\nPrice Point: {{price_point}}\n\nProvide 3 distinct approaches:\n1. The Empathy Approach (Validate and Pivot)\n2. The Question Approach (Dig Deeper)\n3. The Value Approach (Reframe Cost)\n\nInclude:\n- The specific script for each approach\n- When to use each approach\n- The follow-up question',
    variables: [
      {
        name: 'objection',
        description: 'Customer Objection (e.g., Too expensive)',
        type: 'string',
        required: true,
      },
      {
        name: 'product',
        description: 'What are you selling?',
        type: 'string',
        required: true,
      },
      {
        name: 'price_point',
        description: 'Price Tier',
        type: 'select',
        options: ['Low', 'Medium', 'High', 'Enterprise'],
        defaultValue: 'Medium',
      },
    ],
  },
  {
    title: 'LinkedIn Connection Message',
    description: 'Generate connection requests',
    category: 'sales',
    tags: ['linkedin', 'networking', 'sales'],
    content:
      'Write a LinkedIn connection request to {{prospect_role}}.\n\nReason for connecting: {{reason}}\n\nLimit to 300 characters.\n\nTone: {{tone}}\n\nProvide 5 variations:\n1. Direct Approach\n2. Compliment Approach\n3. Common Ground Approach\n4. Value-First Approach\n5. Event/Holiday Approach',
    variables: [
      {
        name: 'prospect_role',
        description: 'Target Role',
        type: 'string',
        required: true,
      },
      {
        name: 'reason',
        description: 'Why connect?',
        type: 'string',
        required: true,
      },
      {
        name: 'tone',
        description: 'Tone',
        type: 'select',
        options: ['Professional', 'Friendly', 'Inquisitive'],
        defaultValue: 'Professional',
      },
    ],
  },
  {
    title: 'Regex Generator',
    description: 'Generate Regular Expressions',
    category: 'development',
    tags: ['regex', 'code-generation', 'validation'],
    content:
      'Generate a Regular Expression for {{language}}.\n\nGoal: {{goal}}\n\nPattern Requirements:\n{{requirements}}\n\nInclude:\n1. The Regex Pattern\n2. Explanation of each component\n3. Test strings that match\n4. Test strings that fail\n\nFlags: {{flags}}',
    variables: [
      {
        name: 'language',
        description: 'Target Language',
        type: 'select',
        options: ['JavaScript', 'Python', 'Go', 'Java', 'PHP', 'Ruby'],
        defaultValue: 'JavaScript',
      },
      {
        name: 'goal',
        description: 'What to match',
        type: 'string',
        required: true,
      },
      {
        name: 'requirements',
        description:
          'Specific constraints (e.g., start with digit, special chars)',
        type: 'string',
        required: true,
      },
      {
        name: 'flags',
        description: 'Regex Flags (e.g., g, i, m)',
        type: 'string',
        required: false,
      },
    ],
  },
  {
    title: 'Cron Job Generator',
    description: 'Generate Cron expressions',
    category: 'devops',
    tags: ['cron', 'scheduling', 'linux'],
    content:
      'Generate a Cron expression for:\n\nTask: {{task_description}}\n\nSchedule Requirements:\n- Frequency: {{frequency}}\n- Specific Times: {{times}}\n- Days: {{days}}\n\nProvide:\n1. The Cron Expression (Standard 5-part)\n2. Human-readable explanation\n3. Example command execution line\n\nTimezone: {{timezone}}',
    variables: [
      {
        name: 'task_description',
        description: 'What is the task?',
        type: 'string',
        required: true,
      },
      {
        name: 'frequency',
        description: 'How often?',
        type: 'select',
        options: [
          'Every Minute',
          'Hourly',
          'Daily',
          'Weekly',
          'Monthly',
          'Yearly',
          'Custom',
        ],
        defaultValue: 'Daily',
      },
      {
        name: 'times',
        description: 'Specific time (if applicable)',
        type: 'string',
        required: false,
      },
      {
        name: 'days',
        description: 'Specific days (if applicable)',
        type: 'string',
        required: false,
      },
      {
        name: 'timezone',
        description: 'Server Timezone',
        type: 'string',
        required: false,
      },
    ],
  },
  {
    title: 'SQL Migration Script',
    description: 'Generate database migration SQL',
    category: 'database',
    tags: ['sql', 'migration', 'database'],
    content:
      'Generate a migration script for {{database_type}}.\n\nObjective: {{objective}}\n\nChanges Required:\n{{changes}}\n\nInclude:\n1. ALTER TABLE statements\n2. CREATE INDEX statements (if {{create_indexes}})\n3. Data update queries (if modifying data)\n4. Rollback script (down migration)\n\nTable Name: {{table_name}}',
    variables: [
      {
        name: 'database_type',
        description: 'SQL Dialect',
        type: 'select',
        options: ['PostgreSQL', 'MySQL', 'SQLite', 'SQL Server'],
        defaultValue: 'PostgreSQL',
      },
      {
        name: 'objective',
        description: 'What is the change?',
        type: 'string',
        required: true,
      },
      {
        name: 'changes',
        description: 'Detailed column or structure changes',
        type: 'string',
        required: true,
      },
      {
        name: 'create_indexes',
        description: 'Need new indexes?',
        type: 'boolean',
        defaultValue: false,
      },
      {
        name: 'table_name',
        description: 'Target Table',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'Git Commit Message',
    description: 'Generate conventional commit messages',
    category: 'development',
    tags: ['git', 'workflow', 'commit'],
    content:
      'Generate a Conventional Commit message for:\n\nChange Description: {{change}}\n\nType: {{type}}\nScope: {{scope}}\nBreaking Change: {{breaking}}\n\nFormat:\n<type>(<scope>): <subject>\n\n<body>\n\n<footer>',
    variables: [
      {
        name: 'change',
        description: 'What changed?',
        type: 'string',
        required: true,
      },
      {
        name: 'type',
        description: 'Commit Type',
        type: 'select',
        options: ['feat', 'fix', 'docs', 'style', 'refactor', 'test', 'chore'],
        defaultValue: 'feat',
      },
      {
        name: 'scope',
        description: 'Scope (module affected)',
        type: 'string',
        required: false,
      },
      {
        name: 'breaking',
        description: 'Is this a breaking change?',
        type: 'boolean',
        defaultValue: false,
      },
    ],
  },
  {
    title: 'RPG Quest Generator',
    description: 'Generate RPG game quests',
    category: 'gaming',
    tags: ['rpg', 'game-design', 'creative'],
    content:
      'Design a quest for {{game_genre}}.\n\nQuest Giver: {{giver}}\nLocation: {{location}}\n\nQuest Details:\n- Title: {{title}}\n- Difficulty: {{difficulty}}\n- Main Objective: {{objective}}\n- Twist/Conflict: {{twist}}\n\nInclude:\n1. Quest Dialogue (Introduction)\n2. Objectives List ({{num_objectives}} steps)\n3. Enemy Encounters (if applicable)\n4. Reward: {{reward}}',
    variables: [
      {
        name: 'game_genre',
        description: 'Genre',
        type: 'select',
        options: ['Fantasy', 'Sci-Fi', 'Cyberpunk', 'Horror'],
        defaultValue: 'Fantasy',
      },
      {
        name: 'giver',
        description: 'NPC Name/Role',
        type: 'string',
        required: true,
      },
      {
        name: 'location',
        description: 'Setting',
        type: 'string',
        required: true,
      },
      {
        name: 'title',
        description: 'Quest Title',
        type: 'string',
        required: true,
      },
      {
        name: 'difficulty',
        description: 'Difficulty',
        type: 'select',
        options: ['Tutorial', 'Easy', 'Medium', 'Hard', 'Boss'],
        defaultValue: 'Medium',
      },
      {
        name: 'objective',
        description: 'Main Goal',
        type: 'string',
        required: true,
      },
      {
        name: 'twist',
        description: 'Plot Twist',
        type: 'string',
        required: false,
      },
      {
        name: 'num_objectives',
        description: 'Number of steps',
        type: 'number',
        defaultValue: 3,
      },
      {
        name: 'reward',
        description: 'Item or XP',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'NPC Dialogue Generator',
    description: 'Generate game character dialogue',
    category: 'gaming',
    tags: ['rpg', 'writing', 'dialogue'],
    content:
      'Write dialogue for an NPC named {{name}}.\n\nRole: {{role}}\nPersonality: {{personality}}\nTone: {{tone}}\n\nContext: {{context}}\n\nWrite:\n1. Greeting\n2. 3 Random idle lines\n3. A line when offered a trade\n4. A line when attacked\n5. Farewell',
    variables: [
      {
        name: 'name',
        description: 'Character Name',
        type: 'string',
        required: true,
      },
      {
        name: 'role',
        description: 'Role (Merchant, Guard, Villager)',
        type: 'select',
        options: ['Merchant', 'Guard', 'Villager', 'King', 'Thief'],
        defaultValue: 'Merchant',
      },
      {
        name: 'personality',
        description: 'Personality Traits',
        type: 'string',
        required: true,
      },
      {
        name: 'tone',
        description: 'Tone',
        type: 'select',
        options: ['Aggressive', 'Friendly', 'Mysterious', 'Sarcastic'],
        defaultValue: 'Friendly',
      },
      {
        name: 'context',
        description: 'Game Setting Context',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'D&D Encounter Builder',
    description: 'Generate D&D encounters',
    category: 'gaming',
    tags: ['dnd', 'tabletop', 'rpg'],
    content:
      'Design a D&D 5e encounter for {{party_level}} adventurers.\n\nParty Size: {{party_size}}\nEnvironment: {{environment}}\n\nTheme: {{theme}}\n\nInclude:\n1. Monster Selection (CR appropriate)\n2. Terrain features\n3. Tactics for enemies\n4. Loot/Treasure\n5. Sensory details (Smell, Sound, Sight)\n\nSetting: {{setting}}',
    variables: [
      {
        name: 'party_level',
        description: 'Average Party Level',
        type: 'number',
        required: true,
      },
      {
        name: 'party_size',
        description: 'Number of players',
        type: 'number',
        defaultValue: 4,
      },
      {
        name: 'environment',
        description: 'Terrain',
        type: 'select',
        options: ['Dungeon', 'Wilderness', 'Urban', 'Underwater', 'Airborne'],
        defaultValue: 'Dungeon',
      },
      {
        name: 'theme',
        description: 'Monster Type/Theme',
        type: 'string',
        required: true,
      },
      {
        name: 'setting',
        description: 'Specific location',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'Personal Budget Planner',
    description: 'Generate monthly budget plans',
    category: 'finance',
    tags: ['budget', 'personal-finance', 'planning'],
    content:
      'Create a monthly budget plan.\n\nIncome: {{monthly_income}}\nLocation: {{location}}\nFamily Size: {{family_size}}\n\nCategorize expenses into:\n1. Housing (Rent/Mortgage, Utilities)\n2. Food (Groceries, Dining Out)\n3. Transportation (Car, Public Transit)\n4. Savings (Emergency Fund, Investments)\n5. Debt Payments (Credit Cards, Loans)\n6. Entertainment\n7. Miscellaneous\n\nBudgeting Method: {{method}}',
    variables: [
      {
        name: 'monthly_income',
        description: 'Net Monthly Income',
        type: 'string',
        required: true,
      },
      {
        name: 'location',
        description: 'City/Country (Cost of Living context)',
        type: 'string',
        required: true,
      },
      {
        name: 'family_size',
        description: 'People in household',
        type: 'number',
        defaultValue: 1,
      },
      {
        name: 'method',
        description: 'Strategy',
        type: 'select',
        options: ['50/30/20 Rule', 'Zero-Based Budget', 'Envelope System'],
        defaultValue: '50/30/20 Rule',
      },
    ],
  },
  {
    title: 'Will & Testament (Draft)',
    description: 'Draft a basic Last Will',
    category: 'legal',
    tags: ['legal', 'will', 'estate'],
    content:
      'Draft a Last Will and Testament for {{name}}.\n\nJurisdiction: {{jurisdiction}}\nBeneficiaries: {{beneficiaries}}\nExecutor: {{executor}}\n\nAssets:\n{{assets}}\n\nInclude:\n1. Declaration\n2. Appointment of Executor\n3. Disposition of Property\n4. Guardianship (if {{has_children}})\n5. Signatures and Witnesses clause\n\nDisclaimer: {{disclaimer}}',
    variables: [
      {
        name: 'name',
        description: 'Testator Name',
        type: 'string',
        required: true,
      },
      {
        name: 'jurisdiction',
        description: 'State/Country',
        type: 'string',
        required: true,
      },
      {
        name: 'beneficiaries',
        description: 'Who inherits?',
        type: 'string',
        required: true,
      },
      {
        name: 'executor',
        description: 'Executor Name',
        type: 'string',
        required: true,
      },
      {
        name: 'assets',
        description: 'Major assets listed',
        type: 'string',
        required: true,
      },
      {
        name: 'has_children',
        description: 'Minor children?',
        type: 'boolean',
        defaultValue: false,
      },
      {
        name: 'disclaimer',
        description: 'Note: This is a template, consult a lawyer',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'SEO Product Description',
    description: 'Generate SEO-friendly product descriptions',
    category: 'ecommerce',
    tags: ['ecommerce', 'seo', 'copywriting'],
    content:
      'Write an SEO-optimized product description for {{product_name}}.\n\nProduct Details:\n{{product_details}}\n\nTarget Audience: {{audience}}\nKeywords: {{keywords}}\nTone: {{tone}}\n\nInclude:\n1. Compelling H1 Heading\n2. Bullet points for key features\n3. Product benefits (not just features)\n4. Specifications section\n5. Call to Action\n\nLength: {{length}}',
    variables: [
      {
        name: 'product_name',
        description: 'Name of Product',
        type: 'string',
        required: true,
      },
      {
        name: 'product_details',
        description: 'Key features, materials, uses',
        type: 'string',
        required: true,
      },
      {
        name: 'audience',
        description: 'Buyer Persona',
        type: 'string',
        required: true,
      },
      {
        name: 'keywords',
        description: 'SEO Keywords',
        type: 'string',
        required: true,
      },
      {
        name: 'tone',
        description: 'Brand Tone',
        type: 'select',
        options: ['Professional', 'Exciting', 'Friendly', 'Luxury'],
        defaultValue: 'Professional',
      },
      {
        name: 'length',
        description: 'Word count target',
        type: 'select',
        options: [
          'Short (100 words)',
          'Medium (250 words)',
          'Long (500 words)',
        ],
        defaultValue: 'Medium (250 words)',
      },
    ],
  },
  {
    title: 'Abandoned Cart Email',
    description: 'Recover lost sales with targeted emails',
    category: 'ecommerce',
    tags: ['ecommerce', 'email', 'marketing'],
    content:
      'Write an abandoned cart email sequence for {{customer_name}}.\n\nItems left in cart: {{cart_items}}\nTotal Value: {{total_value}}\nDiscount Offer: {{discount}}\n\nEmail 1 (1 hour later): Gentle Reminder\nEmail 2 (24 hours later): Social Proof/Reviews\nEmail 3 (48 hours later): Final Discount/Incentive\n\nEach email should include:\n- Engaging Subject Line\n- Personalized Greeting\n- Image of product\n- Clear "Return to Cart" button\n- Store Contact Info',
    variables: [
      {
        name: 'customer_name',
        description: 'Customer Name',
        type: 'string',
        required: true,
      },
      {
        name: 'cart_items',
        description: 'List of items',
        type: 'string',
        required: true,
      },
      {
        name: 'total_value',
        description: 'Cart total',
        type: 'string',
        required: true,
      },
      {
        name: 'discount',
        description: 'Offer code or percentage',
        type: 'string',
        required: false,
      },
    ],
  },
  {
    title: 'Return & Refund Policy',
    description: 'Generate e-commerce policy pages',
    category: 'ecommerce',
    tags: ['ecommerce', 'legal', 'policy'],
    content:
      'Draft a Return & Refund Policy for {{store_name}}.\n\nReturn Window: {{return_days}} days\nCondition of Items: {{condition}}\nRefund Method: {{refund_method}}\n\nInclude clauses for:\n1. Eligibility for returns\n2. Return process (Step-by-step)\n3. Restocking fees (if {{restocking_fee}})\n4. Shipping costs responsibility\n5. Exchange vs Refund options\n6. Damaged/Defective items policy\n7. Contact information',
    variables: [
      {
        name: 'store_name',
        description: 'Store Name',
        type: 'string',
        required: true,
      },
      {
        name: 'return_days',
        description: 'Days allowed for return',
        type: 'number',
        required: true,
      },
      {
        name: 'condition',
        description: 'Required condition (tags on, original packaging)',
        type: 'string',
        required: true,
      },
      {
        name: 'refund_method',
        description: 'Refund type',
        type: 'select',
        options: ['Original Payment', 'Store Credit', 'Exchange Only'],
        defaultValue: 'Original Payment',
      },
      {
        name: 'restocking_fee',
        description: 'Is there a restocking fee?',
        type: 'boolean',
        defaultValue: false,
      },
    ],
  },
  {
    title: 'Product FAQ Generator',
    description: 'Generate FAQs for product pages',
    category: 'ecommerce',
    tags: ['ecommerce', 'support', 'content'],
    content:
      'Generate {{num_questions}} FAQs for {{product_name}}.\n\nProduct Type: {{product_type}}\nTarget Audience: {{audience}}\n\nFocus on common concerns:\n- Sizing/Dimensions\n- Material/Durability\n- Usage/Care instructions\n- Shipping/Delivery\n- Warranty\n\nFormat:\nQ: [Question]\nA: [Clear, concise answer]',
    variables: [
      {
        name: 'product_name',
        description: 'Product Name',
        type: 'string',
        required: true,
      },
      {
        name: 'num_questions',
        description: 'Number of FAQs',
        type: 'number',
        defaultValue: 5,
      },
      {
        name: 'product_type',
        description: 'Category (Apparel, Electronics, Digital)',
        type: 'select',
        options: ['Apparel', 'Electronics', 'Digital Goods', 'Home Goods'],
        defaultValue: 'Apparel',
      },
      {
        name: 'audience',
        description: 'Target Customer',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'Customer Support Reply',
    description: 'Draft empathetic support responses',
    category: 'support',
    tags: ['support', 'email', 'customer-service'],
    content:
      'Draft a reply to a customer ticket.\n\nCustomer Issue: {{issue}}\nCustomer Sentiment: {{sentiment}}\n\nResolution: {{resolution}}\n\nStructure:\n1. Empathetic Opening\n2. Acknowledge the specific issue\n3. Explanation of what happened (if applicable)\n4. Solution/Next Steps\n5. Closing with offer for further help\n\nTone: {{tone}}',
    variables: [
      {
        name: 'issue',
        description: 'Customer complaint or question',
        type: 'string',
        required: true,
      },
      {
        name: 'sentiment',
        description: 'Customer Mood',
        type: 'select',
        options: ['Angry', 'Frustrated', 'Neutral', 'Happy'],
        defaultValue: 'Neutral',
      },
      {
        name: 'resolution',
        description: 'What are you offering/doing?',
        type: 'string',
        required: true,
      },
      {
        name: 'tone',
        description: 'Brand Voice',
        type: 'select',
        options: ['Professional', 'Warm', 'Formal'],
        defaultValue: 'Professional',
      },
    ],
  },
  {
    title: 'Knowledge Base Article',
    description: 'Create self-help documentation',
    category: 'support',
    tags: ['support', 'documentation', 'tech-writing'],
    content:
      'Write a Knowledge Base article for: {{topic}}.\n\nTarget Audience: {{audience}}\nTool/Feature: {{tool}}\n\nFormat:\n1. Clear Title\n2. Brief Introduction\n3. Prerequisites\n4. Step-by-Step Instructions ({{num_steps}} steps)\n5. Screenshots/Visuals placeholders\n6. Troubleshooting section\n7. Related Articles links\n\nStyle: {{style}}',
    variables: [
      {
        name: 'topic',
        description: 'Problem or Task',
        type: 'string',
        required: true,
      },
      {
        name: 'audience',
        description: 'User level',
        type: 'select',
        options: ['Beginner', 'Intermediate', 'Advanced'],
        defaultValue: 'Beginner',
      },
      {
        name: 'tool',
        description: 'Software or Feature name',
        type: 'string',
        required: true,
      },
      {
        name: 'num_steps',
        description: 'Approx steps',
        type: 'number',
        defaultValue: 5,
      },
      {
        name: 'style',
        description: 'Writing Style',
        type: 'select',
        options: ['Direct', 'Friendly', 'Technical'],
        defaultValue: 'Direct',
      },
    ],
  },
  {
    title: 'Customer Onboarding Email',
    description: 'Welcome new users effectively',
    category: 'support',
    tags: ['support', 'email', 'onboarding'],
    content:
      'Write a welcome email for new user {{username}}.\n\nProduct: {{product_name}}\nKey Feature to Highlight: {{feature}}\n\nInclude:\n1. Warm welcome message\n2. One clear "Next Action" (e.g., Complete Profile)\n3. Link to Video Tutorial ({{tutorial_link}})\n4. Link to Documentation\n5. Contact Support info\n\nGoal: {{goal}}',
    variables: [
      {
        name: 'username',
        description: 'User Name',
        type: 'string',
        required: true,
      },
      {
        name: 'product_name',
        description: 'Product Name',
        type: 'string',
        required: true,
      },
      {
        name: 'feature',
        description: 'Main selling point',
        type: 'string',
        required: true,
      },
      {
        name: 'tutorial_link',
        description: 'Placeholder link',
        type: 'string',
        required: false,
      },
      {
        name: 'goal',
        description: 'Desired outcome (Activation, Trial start)',
        type: 'select',
        options: ['Activation', 'Upgrade', 'Engagement'],
        defaultValue: 'Activation',
      },
    ],
  },
  {
    title: 'Brand Identity Guidelines',
    description: 'Generate brand style guides',
    category: 'design',
    tags: ['branding', 'design', 'identity'],
    content:
      "Generate Brand Identity Guidelines for {{brand_name}}.\n\nBrand Values: {{values}}\nTarget Audience: {{audience}}\n\nSections:\n1. Brand Story/Mission Statement\n2. Logo Usage\n   - Clear space\n   - Minimum size\n   - Don'ts\n3. Color Palette\n   - Primary: {{primary_color}}\n   - Secondary: {{secondary_color}}\n4. Typography\n   - Headers: {{header_font}}\n   - Body: {{body_font}}\n5. Voice & Tone guidelines\n6. Imagery Style (photography/illustration)",
    variables: [
      {
        name: 'brand_name',
        description: 'Brand Name',
        type: 'string',
        required: true,
      },
      {
        name: 'values',
        description: 'Core values (e.g., Innovative, Reliable)',
        type: 'string',
        required: true,
      },
      {
        name: 'audience',
        description: 'Target Market',
        type: 'string',
        required: true,
      },
      {
        name: 'primary_color',
        description: 'Primary Brand Color',
        type: 'string',
        required: true,
      },
      {
        name: 'secondary_color',
        description: 'Secondary Brand Color',
        type: 'string',
        required: true,
      },
      {
        name: 'header_font',
        description: 'Heading Font',
        type: 'string',
        required: true,
      },
      {
        name: 'body_font',
        description: 'Body Copy Font',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'Color Palette Generator',
    description: 'Generate color schemes',
    category: 'design',
    tags: ['design', 'color', 'ui'],
    content:
      'Generate a color palette based on {{mood}}.\n\nApplication: {{application}}\n\nProvide:\n1. Primary Color (Hex)\n2. Secondary Color (Hex)\n3. Accent Color (Hex)\n4. Background Color (Hex)\n5. Text Color (Hex)\n\nInclude:\n- Color Codes (HEX, RGB)\n- Accessibility check (Contrast Ratio)\n- Usage suggestions',
    variables: [
      {
        name: 'mood',
        description: 'Desired Vibe',
        type: 'select',
        options: [
          'Trustworthy',
          'Playful',
          'Minimalist',
          'Energetic',
          'Luxury',
          'Dark Mode',
        ],
        defaultValue: 'Trustworthy',
      },
      {
        name: 'application',
        description: 'Usage Context',
        type: 'select',
        options: ['Web App', 'Mobile App', 'Print', 'E-commerce'],
        defaultValue: 'Web App',
      },
    ],
  },
  {
    title: 'UI Microcopy',
    description: 'Generate button text and error messages',
    category: 'design',
    tags: ['design', 'ux', 'writing'],
    content:
      'Generate UI microcopy for {{app_name}}.\n\nAction: {{action}}\nContext: {{context}}\n\nProvide:\n1. Button Text (Short & Actionable)\n2. Hover State Text\n3. Success Message\n4. Error Message (if action fails)\n5. Tooltip/Help Text\n\nStyle: {{style}}',
    variables: [
      {
        name: 'app_name',
        description: 'Application Name',
        type: 'string',
        required: true,
      },
      {
        name: 'action',
        description: 'What is the user doing?',
        type: 'string',
        required: true,
      },
      {
        name: 'context',
        description: 'Specific screen/flow',
        type: 'string',
        required: true,
      },
      {
        name: 'style',
        description: 'Copy Style',
        type: 'select',
        options: ['Friendly', 'Professional', 'Minimal', 'Witty'],
        defaultValue: 'Friendly',
      },
    ],
  },
  {
    title: 'Project Charter',
    description: 'Formal project initiation document',
    category: 'project-management',
    tags: ['pmp', 'charter', 'planning'],
    content:
      'Draft a Project Charter for {{project_name}}.\n\nSponsor: {{sponsor}}\n\nInclude:\n1. Business Case/Justification\n2. Project Scope (In-Scope & Out-of-Scope)\n3. Key Deliverables\n4. Milestones & Timeline\n5. Budget Estimate: {{budget}}\n6. Key Stakeholders\n7. Risks & Constraints\n8. Success Criteria (KPIs)',
    variables: [
      {
        name: 'project_name',
        description: 'Project Title',
        type: 'string',
        required: true,
      },
      {
        name: 'sponsor',
        description: 'Executive Sponsor',
        type: 'string',
        required: true,
      },
      {
        name: 'budget',
        description: 'Estimated Cost',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'Risk Register',
    description: 'Track and mitigate project risks',
    category: 'project-management',
    tags: ['risk', 'management', 'pmp'],
    content:
      'Create a Risk Register for {{project_name}}.\n\nCategory: {{category}}\n\nProvide table entries for {{num_risks}} risks.\n\nColumns required:\n1. Risk ID\n2. Risk Description\n3. Risk Owner\n4. Probability (Low/Med/High)\n5. Impact (Low/Med/High)\n6. Risk Score (PxI)\n7. Mitigation Strategy\n8. Contingency Plan',
    variables: [
      {
        name: 'project_name',
        description: 'Project Name',
        type: 'string',
        required: true,
      },
      {
        name: 'category',
        description: 'Risk Category (Technical, External, Org)',
        type: 'select',
        options: [
          'Technical',
          'External',
          'Organizational',
          'Project Management',
        ],
        defaultValue: 'Technical',
      },
      {
        name: 'num_risks',
        description: 'Number of entries',
        type: 'number',
        defaultValue: 5,
      },
    ],
  },
  {
    title: 'Meeting Minutes (Detailed)',
    description: 'Structured meeting notes template',
    category: 'project-management',
    tags: ['meeting', 'documentation', 'agile'],
    content:
      'Document minutes for meeting titled: {{meeting_title}}.\n\nDate: {{date}}\nAttendees: {{attendees}}\nAbsent: {{absent}}\n\nAgenda Items:\n{{agenda}}\n\nDocument:\n1. Decisions Made\n2. Action Items (Who, What, By When)\n3. Key Discussion Points\n4. Issues Raised\n5. Next Meeting Date\n\nAction Owner: {{action_owner_default}}',
    variables: [
      {
        name: 'meeting_title',
        description: 'Meeting Topic',
        type: 'string',
        required: true,
      },
      {
        name: 'date',
        description: 'Date',
        type: 'string',
        required: true,
      },
      {
        name: 'attendees',
        description: 'List of attendees',
        type: 'string',
        required: true,
      },
      {
        name: 'absent',
        description: 'List of absentees',
        type: 'string',
        required: false,
      },
      {
        name: 'agenda',
        description: 'Agenda points',
        type: 'string',
        required: true,
      },
      {
        name: 'action_owner_default',
        description: 'Default owner if unassigned',
        type: 'string',
        required: false,
      },
    ],
  },
  {
    title: 'SQL Reporting Query',
    description: 'Generate SQL for business reports',
    category: 'data-science',
    tags: ['sql', 'analytics', 'reporting'],
    content:
      'Write a SQL query for {{database}}.\n\nReport Goal: {{goal}}\n\nTables Involved:\n{{tables}}\n\nRequired Metrics:\n{{metrics}}\n\nGroup By: {{group_by}}\nDate Range: {{date_range}}\n\nRequirements:\n1. Handle NULLs appropriately\n2. Filter for active records ({{is_active}})\n3. Order by most significant metric',
    variables: [
      {
        name: 'database',
        description: 'DB Type',
        type: 'select',
        options: ['PostgreSQL', 'MySQL', 'SQL Server', 'Snowflake', 'BigQuery'],
        defaultValue: 'PostgreSQL',
      },
      {
        name: 'goal',
        description: 'What is the report measuring?',
        type: 'string',
        required: true,
      },
      {
        name: 'tables',
        description: 'Table names',
        type: 'string',
        required: true,
      },
      {
        name: 'metrics',
        description: 'KPIs (SUM, AVG, COUNT)',
        type: 'string',
        required: true,
      },
      {
        name: 'group_by',
        description: 'Grouping columns',
        type: 'string',
        required: true,
      },
      {
        name: 'date_range',
        description: 'Time period',
        type: 'string',
        required: true,
      },
      {
        name: 'is_active',
        description: 'Active flag column name',
        type: 'string',
        required: false,
      },
    ],
  },
  {
    title: 'Dashboard Requirement Doc',
    description: 'Define BI dashboard requirements',
    category: 'data-science',
    tags: ['bi', 'tableau', 'powerbi'],
    content:
      'Create a requirement document for a {{tool}} Dashboard.\n\nDashboard Name: {{dashboard_name}}\nAudience: {{audience}}\n\nKey Questions to Answer:\n{{questions}}\n\nRequired:\n1. List of KPI Cards (Top numbers)\n2. Charts needed (Bar, Line, Pie, Map)\n3. Filters/Parameters (Date, Region, Product)\n4. Refresh Rate\n5. Data Sources',
    variables: [
      {
        name: 'tool',
        description: 'Visualization Tool',
        type: 'select',
        options: ['Power BI', 'Tableau', 'Looker', 'Google Data Studio'],
        defaultValue: 'Power BI',
      },
      {
        name: 'dashboard_name',
        description: 'Dashboard Title',
        type: 'string',
        required: true,
      },
      {
        name: 'audience',
        description: 'Who uses this?',
        type: 'string',
        required: true,
      },
      {
        name: 'questions',
        description: 'What business questions to answer?',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'Smart Contract (Solidity)',
    description: 'Generate Solidity code templates',
    category: 'blockchain',
    tags: ['solidity', 'smart-contract', 'web3'],
    content:
      'Generate a Solidity smart contract.\n\nContract Type: {{type}}\nPurpose: {{purpose}}\n\nInclude:\n1. SPDX License Identifier\n2. Pragma solidity version\n3. State Variables\n4. Events\n5. Functions (Constructor, Read, Write)\n6. Modifiers (if {{needs_access_control}})\n\nOpenZeppelin Version: {{oz_version}}',
    variables: [
      {
        name: 'type',
        description: 'Contract Type',
        type: 'select',
        options: [
          'ERC20 Token',
          'ERC721 NFT',
          'Voting',
          'Storage',
          'Crowdfund',
        ],
        defaultValue: 'ERC20 Token',
      },
      {
        name: 'purpose',
        description: 'Description of functionality',
        type: 'string',
        required: true,
      },
      {
        name: 'needs_access_control',
        description: 'OnlyOwner modifier?',
        type: 'boolean',
        defaultValue: true,
      },
      {
        name: 'oz_version',
        description: 'OpenZeppelin version',
        type: 'string',
        defaultValue: '^4.8.0',
      },
    ],
  },
  {
    title: 'NFT Metadata JSON',
    description: 'Generate metadata for NFT collections',
    category: 'blockchain',
    tags: ['nft', 'json', 'metadata'],
    content:
      'Generate JSON metadata for NFT #{{token_id}}.\n\nCollection Name: {{collection}}\nAttributes:\n{{attributes}}\n\nStructure:\n{\n  "name": "...",\n  "description": "...",\n  "image": "...",\n  "attributes": [ { "trait_type": "...", "value": "..." } ]\n}',
    variables: [
      {
        name: 'token_id',
        description: 'Token ID',
        type: 'number',
        required: true,
      },
      {
        name: 'collection',
        description: 'Collection Name',
        type: 'string',
        required: true,
      },
      {
        name: 'attributes',
        description: 'Traits and values',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'Wedding Planner Checklist',
    description: 'Comprehensive wedding planning list',
    category: 'lifestyle',
    tags: ['wedding', 'event', 'planning'],
    content:
      'Generate a wedding checklist for a wedding in {{month}}.\n\nVenue: {{venue}}\nGuest Count: {{guests}}\nBudget: {{budget}}\n\nTimeline: {{timeline}}\n\nCategories:\n1. Venue & Catering\n2. Attire & Beauty\n3. Flowers & Decor\n4. Entertainment\n5. Invitations\n6. Photography\n\nPrioritize items for {{timeline}}.',
    variables: [
      {
        name: 'month',
        description: 'Wedding Month',
        type: 'string',
        required: true,
      },
      {
        name: 'venue',
        description: 'Venue Type',
        type: 'string',
        required: true,
      },
      {
        name: 'guests',
        description: 'Number of guests',
        type: 'number',
        required: true,
      },
      {
        name: 'budget',
        description: 'Budget Tier',
        type: 'select',
        options: ['Low', 'Medium', 'High', 'Luxury'],
        defaultValue: 'Medium',
      },
      {
        name: 'timeline',
        description: 'Planning Horizon',
        type: 'select',
        options: ['12 Months', '6 Months', '3 Months'],
        defaultValue: '12 Months',
      },
    ],
  },
  {
    title: 'Conference Agenda',
    description: 'Create conference schedules',
    category: 'business',
    tags: ['conference', 'event', 'agenda'],
    content:
      'Create an agenda for {{conference_name}}.\n\nDuration: {{days}} Days\nTheme: {{theme}}\nTarget Audience: {{audience}}\n\nStructure:\n1. Keynote Speakers ({{num_keynotes}})\n2. Breakout Sessions\n3. Workshops\n4. Networking Breaks\n5. Lunch/Catering\n\nInclude start/end times and track names.',
    variables: [
      {
        name: 'conference_name',
        description: 'Event Name',
        type: 'string',
        required: true,
      },
      {
        name: 'days',
        description: 'Number of days',
        type: 'number',
        defaultValue: 1,
      },
      {
        name: 'theme',
        description: 'Main Topic',
        type: 'string',
        required: true,
      },
      {
        name: 'audience',
        description: 'Attendees',
        type: 'string',
        required: true,
      },
      {
        name: 'num_keynotes',
        description: 'Keynote speakers',
        type: 'number',
        defaultValue: 2,
      },
    ],
  },
  {
    title: 'Elevator Pitch',
    description: 'Create a 30-second intro',
    category: 'career',
    tags: ['networking', 'pitch', 'interview'],
    content:
      'Write an elevator pitch for {{profession}}.\n\nExperience: {{experience}}\nKey Achievement: {{achievement}}\nGoal of Pitch: {{goal}}\n\nProvide 3 versions:\n1. The "Professional" Pitch (Formal)\n2. The "Story" Pitch (Narrative)\n3. The "Casual" Pitch (Networking event)\n\nTime limit: 30 seconds spoken.',
    variables: [
      {
        name: 'profession',
        description: 'Job Title/Field',
        type: 'string',
        required: true,
      },
      {
        name: 'experience',
        description: 'Years of experience or background',
        type: 'string',
        required: true,
      },
      {
        name: 'achievement',
        description: 'Biggest win',
        type: 'string',
        required: true,
      },
      {
        name: 'goal',
        description: 'Job seeking, partnership, sales?',
        type: 'select',
        options: ['Job Seeking', 'Networking', 'Sales', 'Investor Pitch'],
        defaultValue: 'Job Seeking',
      },
    ],
  },
  {
    title: 'Resignation Letter',
    description: 'Professional resignation letter',
    category: 'career',
    tags: ['resignation', 'hr', 'letter'],
    content:
      'Draft a resignation letter for {{role}} at {{company}}.\n\nLast Working Day: {{last_day}}\nReason to give (optional): {{reason}}\n\nTone: {{tone}}\n\nInclude:\n1. Statement of resignation\n2. Gratitude for opportunities\n3. Offer to assist with transition ({{transition_weeks}} weeks)\n4. Best wishes for the company',
    variables: [
      {
        name: 'role',
        description: 'Current Job Title',
        type: 'string',
        required: true,
      },
      {
        name: 'company',
        description: 'Company Name',
        type: 'string',
        required: true,
      },
      {
        name: 'last_day',
        description: 'Final Date',
        type: 'string',
        required: true,
      },
      {
        name: 'reason',
        description: 'Reason (e.g., New opportunity)',
        type: 'string',
        required: false,
      },
      {
        name: 'tone',
        description: 'Tone',
        type: 'select',
        options: ['Professional', 'Warm', 'Brief', 'Grateful'],
        defaultValue: 'Professional',
      },
      {
        name: 'transition_weeks',
        description: 'Notice period weeks',
        type: 'number',
        defaultValue: 2,
      },
    ],
  },
  {
    title: 'LinkedIn Summary',
    description: 'Optimize LinkedIn About section',
    category: 'career',
    tags: ['linkedin', 'profile', 'social'],
    content:
      'Write a LinkedIn "About" section for a {{role}}.\n\nSkills: {{skills}}\nIndustry: {{industry}}\nPersonality: {{personality}}\n\nStructure:\n1. Hook (First sentence)\n2. Current role & Expertise\n3. Key Achievements/Projects\n4. Passion/Why I do this\n5. Call to Action (Contact info)',
    variables: [
      {
        name: 'role',
        description: 'Target Job Title',
        type: 'string',
        required: true,
      },
      {
        name: 'skills',
        description: 'Top 3 skills',
        type: 'string',
        required: true,
      },
      {
        name: 'industry',
        description: 'Sector',
        type: 'string',
        required: true,
      },
      {
        name: 'personality',
        description: 'Voice (e.g., Analytical, Creative)',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'Next.js API Route Generator',
    description: 'Generate Next.js API route handlers',
    category: 'web-dev',
    tags: ['nextjs', 'api', 'typescript'],
    content:
      'Generate a Next.js API Route for {{endpoint_path}}.\n\nMethod: {{method}}\nAuthentication: {{auth_method}}\nDatabase: {{database}}\n\nInclude:\n1. Request validation ({{validation_lib}})\n2. Database connection logic\n3. Error handling (try/catch)\n4. Status codes (200, 400, 401, 500)\n5. CORS configuration (if needed)\n6. Response JSON structure',
    variables: [
      {
        name: 'endpoint_path',
        description: 'API Path (e.g., /api/users)',
        type: 'string',
        required: true,
      },
      {
        name: 'method',
        description: 'HTTP Method',
        type: 'select',
        options: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'],
        defaultValue: 'GET',
      },
      {
        name: 'auth_method',
        description: 'Auth Strategy',
        type: 'select',
        options: ['None', 'NextAuth', 'Custom Header', 'JWT'],
        defaultValue: 'NextAuth',
      },
      {
        name: 'database',
        description: 'DB Adapter',
        type: 'select',
        options: ['Prisma', 'Mongoose', 'Postgres Client', 'Direct SQL'],
        defaultValue: 'Prisma',
      },
      {
        name: 'validation_lib',
        description: 'Validation Library',
        type: 'select',
        options: ['Zod', 'Yup', 'Joi', 'Manual'],
        defaultValue: 'Zod',
      },
    ],
  },
  {
    title: 'Custom React Hook Generator',
    description: 'Generate reusable React Hooks',
    category: 'web-dev',
    tags: ['react', 'hooks', 'typescript'],
    content:
      'Generate a custom React hook called use{{hook_name}}.\n\nFunctionality: {{functionality}}\n\nParameters:\n{{params}}\n\nInclude:\n1. TypeScript interfaces for params and return\n2. useEffect dependencies\n3. State management\n4. Cleanup functions (if {{needs_cleanup}})\n5. Loading and Error states\n6. Example usage component',
    variables: [
      {
        name: 'hook_name',
        description: 'Hook Name (e.g. FetchData)',
        type: 'string',
        required: true,
      },
      {
        name: 'functionality',
        description: 'What does the hook do?',
        type: 'string',
        required: true,
      },
      {
        name: 'params',
        description: 'Input parameters',
        type: 'string',
        required: true,
      },
      {
        name: 'needs_cleanup',
        description: 'Requires cleanup function?',
        type: 'boolean',
        defaultValue: false,
      },
    ],
  },
  {
    title: 'React Native Component',
    description: 'Generate cross-platform mobile components',
    category: 'mobile',
    tags: ['react-native', 'mobile', 'ios', 'android'],
    content:
      'Generate a React Native component: {{component_name}}.\n\nUI Library: {{ui_library}}\n\nPurpose: {{purpose}}\n\nInclude:\n1. Props interface (TypeScript)\n2. StyleSheet object ({{style_approach}})\n3. Platform specific code (iOS/Android check) (if {{platform_specific}})\n4. Accessibility labels\n5. Touch handling (if interactive)',
    variables: [
      {
        name: 'component_name',
        description: 'Component Name',
        type: 'string',
        required: true,
      },
      {
        name: 'ui_library',
        description: 'UI Lib',
        type: 'select',
        options: ['None', 'React Native Paper', 'NativeBase', 'Tamagui'],
        defaultValue: 'None',
      },
      {
        name: 'purpose',
        description: 'Component Description',
        type: 'string',
        required: true,
      },
      {
        name: 'style_approach',
        description: 'Styling',
        type: 'select',
        options: ['StyleSheet', 'Styled-Components', 'NativeWind', 'Tailwind'],
        defaultValue: 'StyleSheet',
      },
      {
        name: 'platform_specific',
        description: 'Needs Platform checks?',
        type: 'boolean',
        defaultValue: false,
      },
    ],
  },
  {
    title: 'Tailwind CSS Snippet',
    description: 'Generate Tailwind utility classes',
    category: 'web-dev',
    tags: ['tailwind', 'css', 'ui'],
    content:
      'Generate Tailwind CSS classes for: {{element}}.\n\nDesign Specs:\n- Spacing: {{spacing}}\n- Colors: {{colors}}\n- Typography: {{typography}}\n- State: {{state}}\n\nProvide:\n1. Full class string\n2. Breakdown by category\n3. Responsive variant (Mobile first -> Desktop)',
    variables: [
      {
        name: 'element',
        description: 'UI Element (e.g. Card, Button)',
        type: 'string',
        required: true,
      },
      {
        name: 'spacing',
        description: 'Padding/Margin',
        type: 'string',
        required: true,
      },
      {
        name: 'colors',
        description: 'Background/Text colors',
        type: 'string',
        required: true,
      },
      {
        name: 'typography',
        description: 'Font size/weight',
        type: 'string',
        required: true,
      },
      {
        name: 'state',
        description: 'Hover/Focus/Active styles',
        type: 'string',
        required: false,
      },
    ],
  },
  {
    title: 'Terraform AWS S3 Module',
    description: 'Terraform module for secure S3 buckets',
    category: 'cloud',
    tags: ['terraform', 'aws', 's3', 'iac'],
    content:
      'Generate a Terraform module for an S3 Bucket.\n\nBucket Name Prefix: {{prefix}}\nEnvironment: {{environment}}\n\nConfiguration:\n1. Versioning: {{versioning}}\n2. Server Side Encryption: {{encryption}}\n3. Block Public Access: {{block_public}}\n4. Lifecycle Rules ({{lifecycle_days}} days to glacier)\n5. Logging (if {{logging}})\n6. Tags',
    variables: [
      {
        name: 'prefix',
        description: 'Bucket naming prefix',
        type: 'string',
        required: true,
      },
      {
        name: 'environment',
        description: 'Env (dev/prod)',
        type: 'string',
        required: true,
      },
      {
        name: 'versioning',
        description: 'Enable Versioning',
        type: 'boolean',
        defaultValue: true,
      },
      {
        name: 'encryption',
        description: 'Encryption Type',
        type: 'select',
        options: ['AES256', 'aws:kms'],
        defaultValue: 'AES256',
      },
      {
        name: 'block_public',
        description: 'Block All Public Access',
        type: 'boolean',
        defaultValue: true,
      },
      {
        name: 'lifecycle_days',
        description: 'Days to Glacier',
        type: 'number',
        defaultValue: 90,
      },
      {
        name: 'logging',
        description: 'Enable Access Logging',
        type: 'boolean',
        defaultValue: false,
      },
    ],
  },
  {
    title: 'AWS IAM Policy Generator',
    description: 'Generate least-privilege IAM policies',
    category: 'cloud',
    tags: ['aws', 'security', 'iam', 'json'],
    content:
      'Generate an IAM Policy JSON.\n\nService: {{service}}\nActions: {{actions}}\nResources: {{resources}}\nCondition (Optional): {{condition}}\n\nStructure:\n1. Version ("2012-10-17")\n2. Statement block\n3. Effect: Allow\n4. Principal (if {{assume_role}})\n5. Condition keys',
    variables: [
      {
        name: 'service',
        description: 'AWS Service (e.g. s3, dynamodb)',
        type: 'string',
        required: true,
      },
      {
        name: 'actions',
        description: 'List of actions (e.g. GetObject, PutObject)',
        type: 'string',
        required: true,
      },
      {
        name: 'resources',
        description: 'ARN pattern',
        type: 'string',
        required: true,
      },
      {
        name: 'condition',
        description: 'Condition (e.g. IpAddress, StringEquals)',
        type: 'string',
        required: false,
      },
      {
        name: 'assume_role',
        description: 'Is this a Trust Policy?',
        type: 'boolean',
        defaultValue: false,
      },
    ],
  },
  {
    title: 'Docker Security Config',
    description: 'Generate secure Dockerfile configs',
    category: 'devops',
    tags: ['docker', 'security', 'containers'],
    content:
      'Generate a secure Dockerfile for {{app_type}}.\n\nBase Image: {{base_image}}\n\nInclude:\n1. Non-root user setup\n2. Minimal layers (combine commands)\n3. Specific version tags (no latest)\n4. Scan for vulnerabilities logic\n5. Expose only necessary ports\n6. Healthcheck command',
    variables: [
      {
        name: 'app_type',
        description: 'App Runtime (Node, Python, Go)',
        type: 'string',
        required: true,
      },
      {
        name: 'base_image',
        description: 'Image Source (Alpine, Debian, Distroless)',
        type: 'select',
        options: ['Alpine', 'Distroless', 'Debian Slim', 'Ubuntu'],
        defaultValue: 'Alpine',
      },
    ],
  },
  {
    title: 'Kubernetes ConfigMap Generator',
    description: 'Generate K8s ConfigMaps',
    category: 'devops',
    tags: ['kubernetes', 'k8s', 'configuration'],
    content:
      'Generate a Kubernetes ConfigMap for {{app_name}}.\n\nData Source: {{source_type}}\n\nInclude:\n1. ConfigMap manifest\n2. Key-Value pairs or Files\n3. Reference to Secret (if {{secret_ref}})\n4. Labels for selector',
    variables: [
      {
        name: 'app_name',
        description: 'Application Name',
        type: 'string',
        required: true,
      },
      {
        name: 'source_type',
        description: 'Type of config',
        type: 'select',
        options: ['Env Vars', 'Config Files', 'Command Args'],
        defaultValue: 'Env Vars',
      },
      {
        name: 'secret_ref',
        description: 'Reference a Secret?',
        type: 'boolean',
        defaultValue: false,
      },
    ],
  },
  {
    title: 'Google Ads Responsive Copy',
    description: 'Generate Google Search Ad headlines/descriptions',
    category: 'marketing',
    tags: ['ppc', 'google-ads', 'sem'],
    content:
      'Generate Google Responsive Search Ad copy for {{product}}.\n\nKeywords: {{keywords}}\nUSP: {{usp}}\nLanding Page: {{landing_page}}\n\nGenerate:\n1. 5 Headlines (30 chars max)\n2. 4 Descriptions (90 chars max)\n3. Call to Extensions (Sitelinks, Callouts)',
    variables: [
      {
        name: 'product',
        description: 'Product/Service',
        type: 'string',
        required: true,
      },
      {
        name: 'keywords',
        description: 'Target Keywords',
        type: 'string',
        required: true,
      },
      {
        name: 'usp',
        description: 'Unique Selling Proposition',
        type: 'string',
        required: true,
      },
      {
        name: 'landing_page',
        description: 'Destination URL context',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'Blog SEO Outline',
    description: 'Structure blog posts for SEO',
    category: 'content',
    tags: ['seo', 'blog', 'content'],
    content:
      'Create an SEO outline for target keyword: "{{keyword}}".\n\nSearch Intent: {{intent}}\nCompetitors: {{competitors}}\n\nStructure:\n1. H1 Title (Click-worthy, includes keyword)\n2. Introduction (Hook)\n3. H2s (LSI Keywords variations)\n4. H3s (Long-tail details)\n5. FAQ Section (People Also Ask)\n6. Internal Linking suggestions\n7. External Link suggestions',
    variables: [
      {
        name: 'keyword',
        description: 'Target Keyword',
        type: 'string',
        required: true,
      },
      {
        name: 'intent',
        description: 'User Intent',
        type: 'select',
        options: [
          'Informational',
          'Transactional',
          'Navigational',
          'Commercial Investigation',
        ],
        defaultValue: 'Informational',
      },
      {
        name: 'competitors',
        description: 'Top 3 competitor URLs',
        type: 'string',
        required: false,
      },
    ],
  },
  {
    title: 'YouTube Metadata Pack',
    description: 'Generate titles, tags, and descriptions',
    category: 'marketing',
    tags: ['youtube', 'video', 'seo'],
    content:
      'Generate metadata for a video about {{video_topic}}.\n\nAudience: {{audience}}\n\nDeliverables:\n1. 5 Title Options (High CTR)\n2. Video Description (Formatted, 2000 chars)\n3. 15 Tags (Mix of broad and long-tail)\n4. Hashtags (3-5)\n5. Thumbnail Text suggestions',
    variables: [
      {
        name: 'video_topic',
        description: 'Video Subject',
        type: 'string',
        required: true,
      },
      {
        name: 'audience',
        description: 'Viewer Demographic',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'LinkedIn Carousel Post',
    description: 'Create swipeable LinkedIn content',
    category: 'marketing',
    tags: ['linkedin', 'social-media', 'content'],
    content:
      'Design a 10-slide LinkedIn Carousel about {{topic}}.\n\nGoal: {{goal}}\nTone: {{tone}}\n\nSlide Breakdown:\n1. Hook Slide\n2. Problem/Agitation Slides ({{problem_slides}})\n3. Solution Slides ({{solution_slides}})\n4. Value Proposition\n5. Summary Slide\n6. CTA Slide\n\nCaption: {{caption_length}} words.',
    variables: [
      {
        name: 'topic',
        description: 'Subject Matter',
        type: 'string',
        required: true,
      },
      {
        name: 'goal',
        description: 'Engagement/Leads/Education',
        type: 'select',
        options: ['Engagement', 'Lead Gen', 'Education', 'Brand Awareness'],
        defaultValue: 'Engagement',
      },
      {
        name: 'tone',
        description: 'Voice',
        type: 'select',
        options: ['Professional', 'Casual', 'Provocative', 'Educational'],
        defaultValue: 'Professional',
      },
      {
        name: 'problem_slides',
        description: 'Slides dedicated to the problem',
        type: 'number',
        defaultValue: 3,
      },
      {
        name: 'solution_slides',
        description: 'Slides dedicated to the solution',
        type: 'number',
        defaultValue: 4,
      },
      {
        name: 'caption_length',
        description: 'Word count for caption',
        type: 'number',
        defaultValue: 50,
      },
    ],
  },
  {
    title: 'Penetration Test Report',
    description: 'Structure a security assessment report',
    category: 'security',
    tags: ['pentest', 'reporting', 'vulnerability'],
    content:
      'Generate a Penetration Test Report for {{target_scope}}.\n\nDate: {{date}}\nTester: {{tester}}\n\nExecutive Summary:\n1. Overview\n2. Risk Rating (High/Med/Low)\n3. Critical Vulnerabilities Summary\n\nTechnical Findings:\nFor each finding include:\n- CVSS Score\n- Affected Asset\n- Vulnerability Description\n- Proof of Concept (PoC) concept\n- Remediation Steps\n\nFindings: {{findings_list}}',
    variables: [
      {
        name: 'target_scope',
        description: 'Target IP/Domain/App',
        type: 'string',
        required: true,
      },
      {
        name: 'date',
        description: 'Test Date',
        type: 'string',
        required: true,
      },
      {
        name: 'tester',
        description: 'Penetration Tester Name',
        type: 'string',
        required: true,
      },
      {
        name: 'findings_list',
        description: 'List of vulnerabilities found',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'Phishing Simulation Email',
    description: 'Generate internal security training emails',
    category: 'security',
    tags: ['security', 'phishing', 'training'],
    content:
      'Create a simulated phishing email for training.\n\nScenario: {{scenario}}\nTarget Role: {{target_role}}\n\nElements:\n1. Urgency indicator\n2. Plausible "From" address\n3. Malicious Link Placeholder\n4. Attachment (if {{attachment}})\n5. Grammatical errors (optional, for realism)\n\nContext: {{context}}',
    variables: [
      {
        name: 'scenario',
        description: 'Phish type (Password reset, Invoice, Gift card)',
        type: 'select',
        options: [
          'Password Reset',
          'Invoice Update',
          'Urgent Transfer',
          'HR Policy Change',
        ],
        defaultValue: 'Password Reset',
      },
      {
        name: 'target_role',
        description: 'Target Employee',
        type: 'select',
        options: ['Exec', 'Finance', 'IT', 'General'],
        defaultValue: 'General',
      },
      {
        name: 'attachment',
        description: 'Include attachment?',
        type: 'boolean',
        defaultValue: false,
      },
      {
        name: 'context',
        description: 'Current company events to leverage',
        type: 'string',
        required: false,
      },
    ],
  },
  {
    title: 'Incident Response Ticket',
    description: 'Generate security incident tickets',
    category: 'security',
    tags: ['incident-response', 'security', 'jira'],
    content:
      'Generate a Jira ticket for an Incident Response.\n\nIncident Type: {{type}}\nSeverity: {{severity}}\n\nTicket Fields:\n1. Summary\n2. Description (Timeline of events)\n3. Affected Assets\n4. Impact Assessment\n5. Immediate Actions Taken\n6. Containment Status\n7. Assignee ({{team}})\n8. SLA Breach Risk',
    variables: [
      {
        name: 'type',
        description: 'Incident Type',
        type: 'select',
        options: [
          'Malware',
          'DDoS',
          'Data Breach',
          'Phishing',
          'Account Compromise',
        ],
        defaultValue: 'Malware',
      },
      {
        name: 'severity',
        description: 'Severity Level',
        type: 'select',
        options: ['P1 (Critical)', 'P2 (High)', 'P3 (Med)', 'P4 (Low)'],
        defaultValue: 'P2 (High)',
      },
      {
        name: 'team',
        description: 'Assigned Team',
        type: 'string',
        required: true,
      },
    ],
  },
  {
    title: 'Recipe Generator',
    description: 'Create detailed cooking recipes',
    category: 'lifestyle',
    tags: ['cooking', 'recipe', 'food'],
    content:
      'Generate a recipe for {{dish_name}}.\n\nCuisine: {{cuisine}}\nDietary Restriction: {{diet}}\n\nInclude:\n1. Prep Time ({{prep_time}} mins)\n2. Cook Time ({{cook_time}} mins)\n3. Ingredients List (with quantities)\n4. Step-by-Step Instructions\n5. Equipment Needed\n6. Serving Suggestion\n7. Nutritional Estimate (per serving)',
    variables: [
      {
        name: 'dish_name',
        description: 'Name of dish',
        type: 'string',
        required: true,
      },
      {
        name: 'cuisine',
        description: 'Cuisine Type',
        type: 'select',
        options: [
          'Italian',
          'Mexican',
          'Indian',
          'Chinese',
          'American',
          'Mediterranean',
        ],
        defaultValue: 'Italian',
      },
      {
        name: 'diet',
        description: 'Dietary needs',
        type: 'select',
        options: ['None', 'Vegetarian', 'Vegan', 'GF', 'Keto', 'Paleo'],
        defaultValue: 'None',
      },
      {
        name: 'prep_time',
        description: 'Prep Time',
        type: 'number',
        defaultValue: 15,
      },
      {
        name: 'cook_time',
        description: 'Cook Time',
        type: 'number',
        defaultValue: 30,
      },
    ],
  },
  {
    title: 'Woodworking Project Plan',
    description: 'DIY Woodworking blueprints',
    category: 'lifestyle',
    tags: ['diy', 'woodworking', 'craft'],
    content:
      'Create a plan for a {{project_type}}.\n\nSkill Level: {{skill}}\nTools Available: {{tools}}\n\nInclude:\n1. Cut List (Lumber dimensions)\n2. Materials List (Wood, Screws, Glue, Finish)\n3. Step-by-step Assembly\n4. Diagram descriptions (Joinery methods)\n5. Finishing tips\n\nBudget: {{budget}}',
    variables: [
      {
        name: 'project_type',
        description: 'Item to build',
        type: 'string',
        required: true,
      },
      {
        name: 'skill',
        description: 'Builder Skill',
        type: 'select',
        options: ['Beginner', 'Intermediate', 'Advanced'],
        defaultValue: 'Intermediate',
      },
      {
        name: 'tools',
        description: 'Tools available (Saw, Drill, Router, etc)',
        type: 'string',
        required: true,
      },
      {
        name: 'budget',
        description: 'Max Cost',
        type: 'string',
        required: false,
      },
    ],
  },
  {
    title: 'Cocktail Recipe',
    description: 'Create mixed drink recipes',
    category: 'lifestyle',
    tags: ['cocktails', 'drinks', 'party'],
    content:
      'Create a recipe for {{drink_name}}.\n\nBase Spirit: {{spirit}}\nFlavor Profile: {{flavor}}\nGlassware: {{glass}}\n\nInclude:\n1. Ingredients (Ounces/ml)\n2. Garnish\n3. Preparation Method (Shake, Stir, Build)\n4. Ice Type\n5. History/Origin',
    variables: [
      {
        name: 'drink_name',
        description: 'Name of drink (or "Surprise me")',
        type: 'string',
        required: true,
      },
      {
        name: 'spirit',
        description: 'Primary Alcohol',
        type: 'select',
        options: [
          'Vodka',
          'Gin',
          'Rum',
          'Whiskey',
          'Tequila',
          'None (Mocktail)',
        ],
        defaultValue: 'Gin',
      },
      {
        name: 'flavor',
        description: 'Taste profile',
        type: 'select',
        options: ['Sour', 'Sweet', 'Bitter', 'Refreshing', 'Spicy'],
        defaultValue: 'Sour',
      },
      {
        name: 'glass',
        description: 'Glass Type',
        type: 'select',
        options: ['Rocks', 'Highball', 'Coupe', 'Martini', 'Collins'],
        defaultValue: 'Rocks',
      },
    ],
  },
  {
    title: 'Gardening Schedule',
    description: 'Seasonal gardening tasks',
    category: 'lifestyle',
    tags: ['gardening', 'plants', 'outdoor'],
    content:
      'Create a gardening plan for {{season}}.\n\nRegion/Hardiness Zone: {{zone}}\nGarden Type: {{type}}\n\nInclude:\n1. Planting List (Seeds/Seedlings)\n2. Fertilization Schedule\n3. Pest Prevention tips\n4. Watering frequency\n5. Pruning/Harvesting tasks',
    variables: [
      {
        name: 'season',
        description: 'Current Season',
        type: 'select',
        options: ['Spring', 'Summer', 'Fall', 'Winter'],
        defaultValue: 'Spring',
      },
      {
        name: 'zone',
        description: 'USDA Hardiness Zone',
        type: 'string',
        required: true,
      },
      {
        name: 'type',
        description: 'Garden Type',
        type: 'select',
        options: ['Vegetable', 'Flower', 'Herb', 'Indoor'],
        defaultValue: 'Vegetable',
      },
    ],
  },
];

export default promptTemplates;
