/**
 * @author Junaid Atari <mj.atari@gmail.com>
 * @copyright 2025 Junaid Atari
 * @see https://github.com/blacksmoke26
 */

/**
 * Defines a categorization system for tones with their associated properties and metadata.
 * Used to organize and describe different tone styles with configurable parameters and metadata.
 * @example
 * {
 *   category: "Professional",
 *   tones: [
 *     {
 *       key: "formal",
 *       label: "Formal",
 *       shortDescription: "Professional and respectful tone",
 *       sixWordSummary: "Precise, respectful, and authoritative language",
 *       formality: "high"
 *     }
 *   ]
 * }
 * @developerNotes
 * Ensure unique `key` values within each category. Maintain consistent `formality` levels across related tones.
 * Use `sixWordSummary` for quick reference and `tags` for enhanced filtering capabilities.
 */
export interface ToneItem {
  /**
   * Category name grouping related tones (e.g., "Professional", "Creative")
   */
  category: string;

  /**
   * Array of tone definitions with their properties and metadata
   */
  tones: {
    /**
     * Unique identifier for the tone within its category
     */
    key: string;

    /**
     * Display name for the tone (user-facing)
     */
    label: string;

    /**
     * Brief summary of the tone's characteristics
     */
    shortDescription: string;

    /**
     * Concise six-word summary capturing the tone's essence
     */
    summary: string;

    /**
     * Detailed description of the tone's purpose and usage
     */
    description: string;

    /**
     * Configuration parameters specific to the tone
     */
    parameters: Record<string, any>;

    /**
     * Keywords for filtering and categorization
     */
    tags: string[];

    /**
     * Level of formality associated with the tone
     */
    formality: 'high' | 'medium' | 'low' | 'variable';
  }[];
}

/**
 * Generates a JSON Schema for the ToneItem interface.
 * Each property includes descriptions and an examples array.
 */
 export const getTonesSchema = (): object => ({
  $schema: 'http://json-schema.org/draft-07/schema#',
  title: 'ToneItem',
  description: 'Defines a categorization system for tones with their associated properties and metadata.',
  type: 'array',
  items: {
    type: 'object',
    properties: {
      category: {
        type: 'string',
        description: 'Category name grouping related tones (e.g., "Professional", "Creative")',
        examples: ['Professional', 'Creative', 'Emotional & Relational'],
      },
      tones: {
        type: 'array',
        description: 'Array of tone definitions with their properties and metadata',
        items: {
          type: 'object',
          properties: {
            key: {
              type: 'string',
              description: 'Unique identifier for the tone within its category',
              examples: ['formal', 'casual', 'empathetic'],
            },
            label: {
              type: 'string',
              description: 'Display name for the tone (user-facing)',
              examples: ['Formal', 'Casual', 'Empathetic'],
            },
            shortDescription: {
              type: 'string',
              description: 'Brief summary of the tone\'s characteristics',
              examples: ['Adheres to strict grammatical and etiquette standards.', 'Relaxed and conversational language.'],
            },
            summary: {
              type: 'string',
              description: 'Concise six-word summary capturing the tone\'s essence',
              examples: ['Strict, professional, and grammatically correct.', 'Relaxed, conversational, and everyday language.'],
            },
            description: {
              type: 'string',
              description: 'Detailed description of the tone\'s purpose and usage',
              examples: ['Uses standard grammar, complex sentence structures, and avoids slang or contractions to convey authority and respect.'],
            },
            parameters: {
              type: 'object',
              description: 'Configuration parameters specific to the tone',
              examples: [{ grammar: 'strict', contractions: false, vocabulary: 'elevated' }],
            },
            tags: {
              type: 'array',
              description: 'Keywords for filtering and categorization',
              items: { type: 'string' },
              examples: [['professional', 'polite', 'standard']],
            },
            formality: {
              type: 'string',
              enum: ['high', 'medium', 'low', 'variable'],
              description: 'Level of formality associated with the tone',
              examples: ['high', 'medium', 'low'],
            },
          },
          required: ['key', 'label', 'shortDescription', 'summary', 'description', 'parameters', 'tags', 'formality'],
        },
      },
    },
    required: ['category', 'tones'],
  },
});

export const TONES_GROUPED: ToneItem[] = [
  {
    category: 'Original core tones',
    tones: [
      {
        key: 'formal',
        label: 'Formal',
        shortDescription: 'Adheres to strict grammatical and etiquette standards.',
        summary: 'Strict, professional, and grammatically correct.',
        description: 'Uses standard grammar, complex sentence structures, and avoids slang or contractions to convey authority and respect.',
        parameters: { grammar: 'strict', contractions: false, vocabulary: 'elevated' },
        tags: ['professional', 'polite', 'standard'],
        formality: 'high',
      },
      {
        key: 'casual',
        label: 'Casual',
        shortDescription: 'Relaxed and conversational language.',
        summary: 'Relaxed, conversational, and everyday language.',
        description: 'Mimics everyday speech, including slang, contractions, and a relaxed sentence structure suitable for friends or peers.',
        parameters: { grammar: 'loose', slang: true, contractions: true },
        tags: ['relaxed', 'informal', 'friendly'],
        formality: 'low',
      },
      {
        key: 'professional',
        label: 'Professional',
        shortDescription: 'Business-appropriate and respectful language.',
        summary: 'Work-appropriate and respectful communication style.',
        description: 'Balances politeness with efficiency, using clear language suitable for workplace interactions without being overly stiff.',
        parameters: { context: 'work', respect: 'high', jargon: 'moderate' },
        tags: ['business', 'workplace', 'polite'],
        formality: 'high',
      },
      {
        key: 'friendly',
        label: 'Friendly',
        shortDescription: 'Warm and approachable tone.',
        summary: 'Warm, approachable, and inviting.',
        description: 'Uses positive language, greetings, and an inviting demeanor to make the reader feel welcome and valued.',
        parameters: { sentiment: 'positive', distance: 'close', empathy: 'high' },
        tags: ['warm', 'welcoming', 'positive'],
        formality: 'medium',
      },
      {
        key: 'academic',
        label: 'Academic',
        shortDescription: 'Scholarly tone with citations and precision.',
        summary: 'Scholarly, precise, and evidence-based language.',
        description: 'Employs objective language, precise terminology, and often references established research or theoretical frameworks.',
        parameters: { vocabulary: 'specialized', objectivity: 'high', structure: 'logical' },
        tags: ['scholarly', 'university', 'research'],
        formality: 'high',
      },
      {
        key: 'creative',
        label: 'Creative',
        shortDescription: 'Inventive and imaginative expression.',
        summary: 'Inventive, original, and imaginative expression.',
        description: 'Breaks away from standard conventions to use metaphors, unique word choices, and artistic flair.',
        parameters: { originality: 'high', convention: 'low', metaphor: 'frequent' },
        tags: ['artistic', 'innovative', 'unique'],
        formality: 'variable',
      },
      {
        key: 'technical',
        label: 'Technical',
        shortDescription: 'Specialized jargon for specific fields.',
        summary: 'Specialized jargon for specific fields.',
        description: 'Uses industry-specific terminology and acronyms to communicate complex information precisely to experts.',
        parameters: { jargon: 'high', precision: 'max', audience: 'expert' },
        tags: ['engineering', 'specialized', 'precise'],
        formality: 'high',
      },
    ],
  },
  {
    category: 'Formality & Professional Contexts',
    tones: [
      {
        key: 'business',
        label: 'Business',
        shortDescription: 'Efficient and goal-oriented corporate language.',
        summary: 'Efficient, goal-oriented, and corporate.',
        description: 'Focuses on clarity, results, and ROI, avoiding unnecessary flourish while maintaining professional etiquette.',
        parameters: { focus: 'results', style: 'corporate', efficiency: 'high' },
        tags: ['corporate', 'results', 'efficiency'],
        formality: 'high',
      },
      {
        key: 'corporate',
        label: 'Corporate',
        shortDescription: 'Standard language used within large companies.',
        summary: 'Standardized large-company language and buzzwords.',
        description: 'Often uses buzzwords, euphemisms, and polished language typical of internal communications in large enterprises.',
        parameters: { buzzwords: 'moderate', polish: 'high', structure: 'standard' },
        tags: ['enterprise', 'buzzwords', 'internal'],
        formality: 'high',
      },
      {
        key: 'legal',
        label: 'Legal',
        shortDescription: 'Precise and binding contractual language.',
        summary: 'Precise, binding, and unambiguous terminology.',
        description: 'Uses archaic terms and specific phrasing to ensure that meaning is interpreted exactly as intended in a legal context.',
        parameters: { ambiguity: 'zero', terminology: 'archaic', precision: 'max' },
        tags: ['contractual', 'binding', 'precise'],
        formality: 'high',
      },
      {
        key: 'diplomatic',
        label: 'Diplomatic',
        shortDescription: 'Tactful and politically sensitive language.',
        summary: 'Tactful, sensitive, and carefully worded.',
        description: 'Prioritizes nuance and politeness to avoid offense, often using softening language when delivering difficult messages.',
        parameters: { tact: 'max', offense: 'avoid', nuance: 'high' },
        tags: ['tactful', 'political', 'sensitive'],
        formality: 'high',
      },
      {
        key: 'authoritative',
        label: 'Authoritative',
        shortDescription: 'Commanding tone conveying expertise and power.',
        summary: 'Commanding, expert, and confident.',
        description: 'Speaks with confidence and certainty, establishing a clear hierarchy of knowledge or power.',
        parameters: { confidence: 'max', hierarchy: 'established', certainty: 'high' },
        tags: ['commanding', 'expert', 'leader'],
        formality: 'high',
      },
      {
        key: 'objective',
        label: 'Objective',
        shortDescription: 'Unbiased and fact-focused language.',
        summary: 'Unbiased, neutral, and fact-focused.',
        description: 'Presents information without personal feelings or opinion, relying strictly on verifiable data.',
        parameters: { bias: 'none', sentiment: 'neutral', perspective: 'detached' },
        tags: ['neutral', 'factual', 'detached'],
        formality: 'high',
      },
      {
        key: 'neutral',
        label: 'Neutral',
        shortDescription: 'Balanced tone lacking strong emotion.',
        summary: 'Balanced, emotionless, and impartial.',
        description: 'Avoids taking sides or showing strong emotions, serving as a balanced conveyor of information.',
        parameters: { emotion: 'low', stance: 'center', tone: 'flat' },
        tags: ['impartial', 'balanced', 'plain'],
        formality: 'medium',
      },
      {
        key: 'official',
        label: 'Official',
        shortDescription: 'Language appropriate for government or institutions.',
        summary: 'Institutional, administrative, and procedural.',
        description: 'Stiff, procedural language often used by governments or large institutions to denote policy and procedure.',
        parameters: { style: 'administrative', source: 'institution', flexibility: 'low' },
        tags: ['government', 'administrative', 'policy'],
        formality: 'high',
      },
      {
        key: 'bureaucratic',
        label: 'Bureaucratic',
        shortDescription: 'Complex administrative language involving red tape.',
        summary: 'Complex, procedural, and administrative.',
        description: 'Characterized by complex phrasing and adherence to rules, often resulting in wordy and rigid text.',
        parameters: { complexity: 'high', rigidity: 'high', efficiency: 'low' },
        tags: ['administrative', 'rigid', 'complex'],
        formality: 'high',
      },
      {
        key: 'executive',
        label: 'Executive',
        shortDescription: 'High-level strategic language for leadership.',
        summary: 'Strategic, high-level, and leadership-focused.',
        description: 'Concise, big-picture language used by C-suite executives to discuss strategy, vision, and direction.',
        parameters: { level: 'c-suite', focus: 'vision', brevity: 'high' },
        tags: ['leadership', 'strategy', 'c-suite'],
        formality: 'high',
      },
      {
        key: 'boardroom',
        label: 'Boardroom',
        shortDescription: 'Sophisticated language for strategic governance.',
        summary: 'Sophisticated governance and strategic language.',
        description: 'Polished, formal, and discreet language used for high-stakes decision making and governance.',
        parameters: { setting: 'board', discretion: 'high', stakes: 'high' },
        tags: ['governance', 'sophisticated', 'discreet'],
        formality: 'high',
      },
      {
        key: 'compliance-oriented',
        label: 'Compliance-Oriented',
        shortDescription: 'Strict adherence to rules and regulations.',
        summary: 'Strict adherence to rules and regulations.',
        description: 'Focuses heavily on ensuring all statements and actions align with legal and internal standards.',
        parameters: { compliance: 'strict', risk: 'low', verification: 'high' },
        tags: ['regulatory', 'safe', 'strict'],
        formality: 'high',
      },
      {
        key: 'regulatory',
        label: 'Regulatory',
        shortDescription: 'Language focused on enforcing standards.',
        summary: 'Enforcing standards and legal requirements.',
        description: 'Uses prescriptive language to define boundaries and requirements for regulated industries.',
        parameters: { function: 'enforce', strictness: 'max', scope: 'industry' },
        tags: ['enforcement', 'standards', 'legal'],
        formality: 'high',
      },
    ],
  },
  {
    category: 'Emotional & Relational',
    tones: [
      {
        key: 'empathetic',
        label: 'Empathetic',
        shortDescription: 'Demonstrates understanding and shared feelings.',
        summary: 'Understanding and sharing feelings deeply.',
        description: 'Validates the reader\'s emotions and shows a deep understanding of their perspective and struggles.',
        parameters: { emotion: 'high', validation: 'active', perspective: 'shared' },
        tags: ['understanding', 'caring', 'validation'],
        formality: 'variable',
      },
      {
        key: 'compassionate',
        label: 'Compassionate',
        shortDescription: 'Shows deep sympathy and concern.',
        summary: 'Deep sympathy and concern for others.',
        description: 'Expresses sorrow for someone\'s misfortune and a sincere desire to alleviate their suffering.',
        parameters: { sympathy: 'high', kindness: 'active', support: 'offered' },
        tags: ['kind', 'sympathetic', 'caring'],
        formality: 'low',
      },
      {
        key: 'supportive',
        label: 'Supportive',
        shortDescription: 'Encourages and provides backing to the reader.',
        summary: 'Encouraging and backing the reader.',
        description: 'Acts as a cheerleader, offering encouragement and confidence to help the reader proceed.',
        parameters: { encouragement: 'high', role: 'ally', positivity: 'active' },
        tags: ['encouraging', 'ally', 'helpful'],
        formality: 'low',
      },
      {
        key: 'encouraging',
        label: 'Encouraging',
        shortDescription: 'Inspires confidence and action.',
        summary: 'Inspiring confidence and positive action.',
        description: 'Uses positive reinforcement to motivate the reader to attempt tasks or overcome challenges.',
        parameters: { motivation: 'positive', confidence: 'boosting', focus: 'potential' },
        tags: ['motivating', 'positive', 'uplifting'],
        formality: 'low',
      },
      {
        key: 'uplifting',
        label: 'Uplifting',
        shortDescription: 'Makes the reader feel better and hopeful.',
        summary: 'Makes the reader feel positive hope.',
        description: 'Focuses on positivity, optimism, and bright outlooks to improve the reader\'s mood.',
        parameters: { mood: 'elevated', optimism: 'high', sentiment: 'positive' },
        tags: ['positive', 'happy', 'optimistic'],
        formality: 'low',
      },
      {
        key: 'reassuring',
        label: 'Reassuring',
        shortDescription: 'Removes doubt and anxiety.',
        summary: 'Removes doubt and calms anxiety.',
        description: 'Provides comforting words and certainties to help the reader feel safe and secure.',
        parameters: { safety: 'psychological', doubt: 'removed', calm: 'projected' },
        tags: ['calming', 'safe', 'comforting'],
        formality: 'low',
      },
      {
        key: 'sincere',
        label: 'Sincere',
        shortDescription: 'Genuine and honest expression.',
        summary: 'Genuine, honest, and heartfelt expression.',
        description: 'Conveys authenticity and a lack of pretense, making the reader trust the speaker\'s intentions.',
        parameters: { authenticity: 'high', pretense: 'none', honesty: 'total' },
        tags: ['honest', 'genuine', 'authentic'],
        formality: 'low',
      },
      {
        key: 'humble',
        label: 'Humble',
        shortDescription: 'Modest and lacking arrogance.',
        summary: 'Modest, unassuming, and down-to-earth.',
        description: 'Downplays personal achievements and status to relate to the reader as an equal.',
        parameters: { ego: 'low', status: 'equal', posture: 'modest' },
        tags: ['modest', 'unassuming', 'grounded'],
        formality: 'low',
      },
      {
        key: 'grateful',
        label: 'Grateful',
        shortDescription: 'Expresses thanks and appreciation.',
        summary: 'Thankful and appreciative of help.',
        description: 'Warmly acknowledges the contributions or presence of others with specific and heartfelt thanks.',
        parameters: { thanks: 'expressed', appreciation: 'clear', warmth: 'high' },
        tags: ['thankful', 'appreciative', 'polite'],
        formality: 'variable',
      },
      {
        key: 'apologetic',
        label: 'Apologetic',
        shortDescription: 'Expresses regret and responsibility.',
        summary: 'Full of regret and taking responsibility.',
        description: 'Accepts fault and expresses sincere remorse for errors or inconveniences caused.',
        parameters: { regret: 'sincere', responsibility: 'accepted', repair: 'offered' },
        tags: ['sorry', 'regretful', 'humble'],
        formality: 'variable',
      },
      {
        key: 'respectful',
        label: 'Respectful',
        shortDescription: 'Shows deference and honor.',
        summary: 'Showing deference and high regard.',
        description: 'Uses polite language and honors the reader\'s time, status, or boundaries.',
        parameters: { deference: 'high', honor: 'shown', boundaries: 'respected' },
        tags: ['polite', 'deferential', 'considerate'],
        formality: 'high',
      },
      {
        key: 'warm',
        label: 'Warm',
        shortDescription: 'Friendly and affectionate manner.',
        summary: 'Friendly, affectionate, and kindly.',
        description: 'Creates a sense of closeness and comfort through affectionate language and positive sentiment.',
        parameters: { affection: 'moderate', distance: 'close', positivity: 'high' },
        tags: ['affectionate', 'kindly', 'cozy'],
        formality: 'low',
      },
      {
        key: 'kind',
        label: 'Kind',
        shortDescription: 'Benevolent and considerate.',
        summary: 'Benevolent, generous, and considerate.',
        description: 'Focuses on the well-being of the reader, ensuring the content is helpful and gentle.',
        parameters: { benevolence: 'high', harm: 'none', gentleness: 'active' },
        tags: ['benevolent', 'gentle', 'good'],
        formality: 'low',
      },
      {
        key: 'gentle',
        label: 'Gentle',
        shortDescription: 'Soft and mild in approach.',
        summary: 'Soft, mild, and tender approach.',
        description: 'Avoids harshness or aggression, delivering even difficult messages with a soft touch.',
        parameters: { harshness: 'none', volume: 'low', tenderness: 'high' },
        tags: ['soft', 'tender', 'mild'],
        formality: 'low',
      },
      {
        key: 'enthusiastic',
        label: 'Enthusiastic',
        shortDescription: 'High energy and eagerness.',
        summary: 'High energy and eager excitement.',
        description: 'Uses exclamation points and vibrant language to show intense interest and eagerness.',
        parameters: { energy: 'high', excitement: 'visible', pace: 'fast' },
        tags: ['excited', 'eager', 'energetic'],
        formality: 'low',
      },
      {
        key: 'passionate',
        label: 'Passionate',
        shortDescription: 'Intense and emotional conviction.',
        summary: 'Intense emotion and strong conviction.',
        description: 'Conveys strong feelings about a subject, convincing the reader of its importance through emotion.',
        parameters: { emotion: 'intense', conviction: 'strong', drive: 'emotional' },
        tags: ['intense', 'emotional', 'conviction'],
        formality: 'medium',
      },
      {
        key: 'excited',
        label: 'Excited',
        shortDescription: 'Shows great eagerness and anticipation.',
        summary: 'Eager anticipation and visible thrill.',
        description: 'Communicates a thrill about future events or topics, often using hyperbole.',
        parameters: { anticipation: 'high', thrill: 'visible', hyperbole: 'allowed' },
        tags: ['thrilled', 'anticipating', 'hyped'],
        formality: 'low',
      },
      {
        key: 'optimistic',
        label: 'Optimistic',
        shortDescription: 'Expects the best possible outcome.',
        summary: 'Hopeful and expecting the best.',
        description: 'Focuses on positive possibilities and future success, dismissing doubts.',
        parameters: { outlook: 'positive', doubt: 'low', hope: 'active' },
        tags: ['hopeful', 'positive', 'bright'],
        formality: 'medium',
      },
      {
        key: 'hopeful',
        label: 'Hopeful',
        shortDescription: 'Maintains a positive expectation.',
        summary: 'Looking forward with positive expectation.',
        description: 'Expresses a desire for a good outcome while acknowledging current difficulties.',
        parameters: { desire: 'good', realism: 'mixed', positivity: 'forward' },
        tags: ['positive', 'expectant', 'wishing'],
        formality: 'low',
      },
      {
        key: 'playful',
        label: 'Playful',
        shortDescription: 'Fun-loving and light-hearted.',
        summary: 'Fun-loving, light-hearted, and joking.',
        description: 'Uses humor, jokes, and a lighthearted attitude to make the content enjoyable.',
        parameters: { humor: 'high', seriousness: 'low', fun: 'goal' },
        tags: ['fun', 'joking', 'light'],
        formality: 'low',
      },
      {
        key: 'cheerful',
        label: 'Cheerful',
        shortDescription: 'Happy and positive demeanor.',
        summary: 'Happy, bubbly, and positive.',
        description: 'Consistently maintains a happy and sunny disposition throughout the text.',
        parameters: { mood: 'sunny', sadness: 'none', positivity: 'constant' },
        tags: ['happy', 'sunny', 'bubbly'],
        formality: 'low',
      },
      {
        key: 'whimsical',
        label: 'Whimsical',
        shortDescription: 'Playfully quaint or fanciful.',
        summary: 'Playfully quaint and magical fancy.',
        description: 'Uses whimsy, imagination, and a dreamy quality to create a sense of wonder.',
        parameters: { fancy: 'high', reality: 'bent', magic: 'subtle' },
        tags: ['fanciful', 'dreamy', 'magical'],
        formality: 'low',
      },
      {
        key: 'witty',
        label: 'Witty',
        shortDescription: 'Showy clever humor and intellect.',
        summary: 'Clever, humorous, and intellectually sharp.',
        description: 'Uses wordplay, irony, and clever phrasing to entertain and engage the reader.',
        parameters: { intellect: 'sharp', humor: 'clever', wordplay: 'used' },
        tags: ['clever', 'smart', 'funny'],
        formality: 'medium',
      },
      {
        key: 'sarcastic',
        label: 'Sarcastic',
        shortDescription: 'Uses irony to mock or convey contempt.',
        summary: 'Using irony to mock or scorn.',
        description: 'Says the opposite of what is meant, often with a biting or mocking edge.',
        parameters: { irony: 'heavy', intent: 'mock', bitterness: 'possible' },
        tags: ['ironic', 'mocking', 'biting'],
        formality: 'low',
      },
      {
        key: 'dry',
        label: 'Dry',
        shortDescription: 'Amusingly ironic or unconcerned.',
        summary: 'Amusingly ironic and unconcerned manner.',
        description: 'Delivers humor with a straight face, using understatement and a matter-of-fact delivery.',
        parameters: { delivery: 'flat', understatement: 'key', amusement: 'subtle' },
        tags: ['understated', 'ironic', 'deadpan'],
        formality: 'medium',
      },
      {
        key: 'deadpan',
        label: 'Deadpan',
        shortDescription: 'Humor with an impassive expression.',
        summary: 'Humor delivered with an impassive face.',
        description: 'Maintains a serious and emotionless tone while saying something absurd or funny.',
        parameters: { face: 'still', emotion: 'hidden', absurdity: 'high' },
        tags: ['impassive', 'serious', 'stoic'],
        formality: 'low',
      },
      {
        key: 'ironic',
        label: 'Ironic',
        shortDescription: 'Highlights contradictions between expectation and reality.',
        summary: 'Highlighting contradictions and unexpected outcomes.',
        description: 'Uses language that signifies the opposite of the literal meaning, often for satirical effect.',
        parameters: { meaning: 'opposite', expectation: 'subverted', awareness: 'high' },
        tags: ['contradictory', 'satirical', 'opposite'],
        formality: 'medium',
      },
      {
        key: 'cynical',
        label: 'Cynical',
        shortDescription: 'Believes people are motivated by self-interest.',
        summary: 'Distrusting motives and expecting the worst.',
        description: 'Uses negative language to suggest that human conduct is motivated purely by self-interest.',
        parameters: { trust: 'low', motives: 'questioned', negativity: 'high' },
        tags: ['distrustful', 'negative', 'skeptical'],
        formality: 'low',
      },
      {
        key: 'pessimistic',
        label: 'Pessimistic',
        shortDescription: 'Expects the worst possible outcome.',
        summary: 'Expecting the worst possible outcome.',
        description: 'Focuses on potential problems, failures, and negative aspects of a situation.',
        parameters: { outlook: 'negative', worry: 'high', success: 'doubted' },
        tags: ['negative', 'gloomy', 'hopeless'],
        formality: 'low',
      },
      {
        key: 'nostalgic',
        label: 'Nostalgic',
        shortDescription: 'Sentimental longing for the past.',
        summary: 'Sentimental longing for the past.',
        description: 'Evokes a sentimental yearning for the past using specific cultural references or soft language.',
        parameters: { time: 'past', sentiment: 'yearning', mood: 'wistful' },
        tags: ['past', 'wistful', 'memory'],
        formality: 'low',
      },
      {
        key: 'melancholic',
        label: 'Melancholic',
        shortDescription: 'Sad, pensive, and gentle gloom.',
        summary: 'Sad, pensive, and gentle gloom.',
        description: 'Conveys a persistent feeling of gentle sadness or depression without necessarily having a specific cause.',
        parameters: { mood: 'sad', energy: 'low', pensive: 'true' },
        tags: ['sad', 'pensive', 'gloomy'],
        formality: 'low',
      },
      {
        key: 'somber',
        label: 'Somber',
        shortDescription: 'Serious and dark in mood.',
        summary: 'Serious, dark, and solemn mood.',
        description: 'Maintains a heavy, serious tone suitable for tragic or solemn occasions.',
        parameters: { gravity: 'high', lightness: 'none', mood: 'heavy' },
        tags: ['serious', 'dark', 'tragic'],
        formality: 'high',
      },
      {
        key: 'urgent',
        label: 'Urgent',
        shortDescription: 'Requires immediate action or attention.',
        summary: 'Requiring immediate action or attention.',
        description: 'Uses short, punchy sentences and direct language to convey the need for speed.',
        parameters: { speed: 'critical', pacing: 'fast', action: 'now' },
        tags: ['critical', 'immediate', 'pressing'],
        formality: 'medium',
      },
      {
        key: 'alarmed',
        label: 'Alarmed',
        shortDescription: 'Shows fear or anxiety about a danger.',
        summary: 'Showing fear or anxiety about danger.',
        description: 'Communicates a sense of panic or immediate threat to the reader.',
        parameters: { panic: 'high', threat: 'immediate', calm: 'low' },
        tags: ['panicked', 'scared', 'threatened'],
        formality: 'low',
      },
      {
        key: 'concerned',
        label: 'Concerned',
        shortDescription: 'Worried about a specific issue.',
        summary: 'Worried and troubled by issues.',
        description: 'Expresses worry and anxiety regarding a specific problem or outcome.',
        parameters: { worry: 'active', anxiety: 'moderate', care: 'evident' },
        tags: ['worried', 'troubled', 'anxious'],
        formality: 'medium',
      },
      {
        key: 'soothing',
        label: 'Soothing',
        shortDescription: 'Calms and reduces anxiety.',
        summary: 'Calming, reducing anxiety and stress.',
        description: 'Uses rhythmic, soft, and gentle language to lower the reader\'s stress levels.',
        parameters: { rhythm: 'slow', volume: 'soft', stress: 'targeted' },
        tags: ['calming', 'relaxing', 'peaceful'],
        formality: 'low',
      },
    ],
  },
  {
    category: 'Style & Expression',
    tones: [
      {
        key: 'conversational',
        label: 'Conversational',
        shortDescription: 'Like a dialogue between friends.',
        summary: 'Like talking to a close friend.',
        description: 'Mimics the natural flow and vocabulary of a spoken conversation.',
        parameters: { flow: 'natural', grammar: 'spoken', vocabulary: 'everyday' },
        tags: ['chat', 'dialogue', 'natural'],
        formality: 'low',
      },
      {
        key: 'colloquial',
        label: 'Colloquial',
        shortDescription: 'Informal, everyday language specific to regions.',
        summary: 'Informal and regional everyday language.',
        description: 'Uses slang and idioms appropriate for casual, everyday speech in specific regions.',
        parameters: { slang: 'high', idioms: 'common', formality: 'low' },
        tags: ['slang', 'regional', 'informal'],
        formality: 'low',
      },
      {
        key: 'narrative',
        label: 'Narrative',
        shortDescription: 'Tells a story or recounts events.',
        summary: 'Telling a story or recounting events.',
        description: 'Structured as a story with a beginning, middle, and end, often using chronological order.',
        parameters: { structure: 'story', time: 'chronological', voice: 'storyteller' },
        tags: ['story', 'chronology', 'events'],
        formality: 'variable',
      },
      {
        key: 'storytelling',
        label: 'Storytelling',
        shortDescription: 'Engaging narrative techniques to captivate.',
        summary: 'Engaging narrative techniques to captivate.',
        description: 'Uses narrative hooks, character development, and plot to make a point entertainingly.',
        parameters: { engagement: 'high', characters: 'possible', plot: 'driven' },
        tags: ['engaging', 'plot', 'character'],
        formality: 'variable',
      },
      {
        key: 'descriptive',
        label: 'Descriptive',
        shortDescription: 'Paints a picture with words.',
        summary: 'Painting a detailed picture with words.',
        description: 'Focuses on adjectives and sensory details to create a vivid mental image.',
        parameters: { adjectives: 'many', senses: 'engaged', imagery: 'vivid' },
        tags: ['visual', 'sensory', 'detailed'],
        formality: 'medium',
      },
      {
        key: 'vivid',
        label: 'Vivid',
        shortDescription: 'Extremely clear and detailed imagery.',
        summary: 'Extremely clear and lively imagery.',
        description: 'Produces powerful mental images through intense and specific descriptive language.',
        parameters: { intensity: 'high', clarity: 'sharp', impact: 'strong' },
        tags: ['clear', 'intense', 'lively'],
        formality: 'medium',
      },
      {
        key: 'minimalist',
        label: 'Minimalist',
        shortDescription: 'Stripped down to the bare essentials.',
        summary: 'Stripped down to bare essentials.',
        description: 'Uses very few words, relying on the reader to infer meaning from sparse details.',
        parameters: { words: 'few', decoration: 'none', inference: 'high' },
        tags: ['simple', 'bare', 'clean'],
        formality: 'variable',
      },
      {
        key: 'concise',
        label: 'Concise',
        shortDescription: 'Brief and comprehensive expression.',
        summary: 'Brief but covering all needed points.',
        description: 'Conveys a lot of information in very few words without losing meaning.',
        parameters: { brevity: 'key', coverage: 'full', fluff: 'none' },
        tags: ['brief', 'efficient', 'lean'],
        formality: 'variable',
      },
      {
        key: 'succinct',
        label: 'Succinct',
        shortDescription: 'Clearly expressed in few words.',
        summary: 'Clearly expressed in very few words.',
        description: 'Keeps the expression tightly and briefly expressed, with no wasted words.',
        parameters: { tightness: 'high', waste: 'zero', precision: 'high' },
        tags: ['tight', 'brief', 'precise'],
        formality: 'variable',
      },
      {
        key: 'verbose',
        label: 'Verbose',
        shortDescription: 'Using more words than necessary.',
        summary: 'Using more words than needed.',
        description: 'Characterized by wordiness and an abundance of language, often considered repetitive.',
        parameters: { wordCount: 'high', brevity: 'low', repetition: 'possible' },
        tags: ['wordy', 'long-winded', 'repetitive'],
        formality: 'medium',
      },
      {
        key: 'eloquent',
        label: 'Eloquent',
        shortDescription: 'Fluent and persuasive in speaking/writing.',
        summary: 'Fluent and persuasive speaking or writing.',
        description: 'Uses beautiful and forceful language to persuade or move the audience effectively.',
        parameters: { beauty: 'high', force: 'strong', fluency: 'perfect' },
        tags: ['fluent', 'persuasive', 'beautiful'],
        formality: 'high',
      },
      {
        key: 'poetic',
        label: 'Poetic',
        shortDescription: 'Expressive and rhythmic like poetry.',
        summary: 'Expressive, rhythmic, and artistic language.',
        description: 'Uses rhythm, meter, and metaphorical language to evoke emotion and beauty.',
        parameters: { rhythm: 'yes', meter: 'possible', metaphor: 'rich' },
        tags: ['rhythm', 'art', 'beauty'],
        formality: 'medium',
      },
      {
        key: 'lyrical',
        label: 'Lyrical',
        shortDescription: 'Expressing deep emotion in song-like words.',
        summary: 'Expressing deep emotion artistically.',
        description: 'Uses highly emotional and expressive language reminiscent of song lyrics.',
        parameters: { emotion: 'deep', style: 'song-like', intensity: 'high' },
        tags: ['emotional', 'song', 'artistic'],
        formality: 'low',
      },
      {
        key: 'rhythmic',
        label: 'Rhythmic',
        shortDescription: 'Strong beat and cadence in words.',
        summary: 'Strong beat and flow to words.',
        description: 'Uses patterns of sound and stress to create a musical quality in the text.',
        parameters: { beat: 'strong', cadence: 'clear', flow: 'musical' },
        tags: ['beat', 'cadence', 'flow'],
        formality: 'variable',
      },
      {
        key: 'metaphorical',
        label: 'Metaphorical',
        shortDescription: 'Uses metaphors to describe subjects.',
        summary: 'Comparing subjects using direct metaphors.',
        description: 'Describes one thing by stating it is another, creating symbolic meaning.',
        parameters: { metaphor: 'primary', literal: 'no', meaning: 'symbolic' },
        tags: ['symbolic', 'comparison', 'abstract'],
        formality: 'variable',
      },
      {
        key: 'symbolic',
        label: 'Symbolic',
        shortDescription: 'Uses symbols to represent ideas.',
        summary: 'Using symbols to represent ideas.',
        description: 'Relies on symbols rather than direct literal descriptions to convey deeper meanings.',
        parameters: { symbols: 'primary', literal: 'secondary', depth: 'deep' },
        tags: ['symbol', 'deep', 'abstract'],
        formality: 'medium',
      },
      {
        key: 'abstract',
        label: 'Abstract',
        shortDescription: 'Deals with ideas rather than events.',
        summary: 'Dealing with ideas rather than events.',
        description: 'Focuses on theoretical concepts and general ideas rather than concrete examples.',
        parameters: { concreteness: 'low', theory: 'high', ideas: 'main' },
        tags: ['theoretical', 'conceptual', 'philosophical'],
        formality: 'high',
      },
      {
        key: 'literal',
        label: 'Literal',
        shortDescription: 'Taking words in their basic sense.',
        summary: 'Taking words in their basic sense.',
        description: 'Avoids metaphor, exaggeration, or embellishment, sticking to the factual meaning.',
        parameters: { metaphor: 'none', exaggeration: 'none', fact: 'strict' },
        tags: ['factual', 'plain', 'exact'],
        formality: 'medium',
      },
      {
        key: 'direct',
        label: 'Direct',
        shortDescription: 'Straight to the point.',
        summary: 'Straight to the point immediately.',
        description: 'Addresses the topic immediately without preamble, euphemism, or digression.',
        parameters: { preamble: 'none', digression: 'none', path: 'straight' },
        tags: ['straight', 'immediate', 'blunt'],
        formality: 'variable',
      },
      {
        key: 'indirect',
        label: 'Indirect',
        shortDescription: 'Approaching a subject in a roundabout way.',
        summary: 'Approaching the subject in roundabout ways.',
        description: 'Uses hints, suggestions, and circumlocution rather than stating the main point plainly.',
        parameters: { hints: 'yes', plainness: 'no', approach: 'soft' },
        tags: ['hinting', 'soft', 'euphemistic'],
        formality: 'variable',
      },
      {
        key: 'subtle',
        label: 'Subtle',
        shortDescription: 'Delicate and precise in meaning.',
        summary: 'Delicate and precise nuances.',
        description: 'Conveys meaning in a nuanced, understated way that requires attention to appreciate.',
        parameters: { nuance: 'high', volume: 'low', attention: 'required' },
        tags: ['nuanced', 'understated', 'delicate'],
        formality: 'variable',
      },
      {
        key: 'dramatic',
        label: 'Dramatic',
        shortDescription: 'Exciting, emotional, and unexpected.',
        summary: 'Exciting, emotional, and highly intense.',
        description: 'Uses夸张 and emotional intensity to create a theatrical effect.',
        parameters: { intensity: 'high', excitement: 'high', theater: 'yes' },
        tags: ['theatrical', 'exciting', 'intense'],
        formality: 'low',
      },
      {
        key: 'theatrical',
        label: 'Theatrical',
        shortDescription: 'Exaggerated and artificial like a play.',
        summary: 'Exaggerated and artificial like theater.',
        description: 'Uses heightened language and夸张 suited for stage performance and presentation.',
        parameters: { presentation: 'stage', exaggeration: 'high', realism: 'low' },
        tags: ['stage', 'performance', 'exaggerated'],
        formality: 'low',
      },
      {
        key: 'cinematic',
        label: 'Cinematic',
        shortDescription: 'Visual and sweeping like a movie.',
        summary: 'Visual, sweeping, and movie-like.',
        description: 'Describes scenes with a focus on visual composition and grand narrative arc.',
        parameters: { focus: 'visual', scope: 'grand', medium: 'film' },
        tags: ['film', 'visual', 'sweeping'],
        formality: 'medium',
      },
      {
        key: 'epic',
        label: 'Epic',
        shortDescription: 'Grand in scale and style.',
        summary: 'Grand in scale and heroic style.',
        description: 'Uses elevated language to describe heroic events of grand, historical proportions.',
        parameters: { scale: 'grand', style: 'heroic', elevation: 'high' },
        tags: ['grand', 'heroic', 'historical'],
        formality: 'high',
      },
      {
        key: 'mythic',
        label: 'Mythic',
        shortDescription: 'Resembling myths and legends.',
        summary: 'Resembling ancient myths and legends.',
        description: 'Uses archetypes and timeless storytelling styles reminiscent of ancient mythology.',
        parameters: { archetypes: 'yes', time: 'timeless', legends: 'like' },
        tags: ['legend', 'archetype', 'ancient'],
        formality: 'high',
      },
    ],
  },
  {
    category: 'Persuasive & Rhetorical',
    tones: [
      {
        key: 'persuasive',
        label: 'Persuasive',
        shortDescription: 'Intended to convince the reader.',
        summary: 'Intended to convince and sway opinion.',
        description: 'Uses logic, emotion, and credibility to change the reader\'s mind or action.',
        parameters: { logic: 'used', emotion: 'used', credibility: 'used' },
        tags: ['convincing', 'influence', 'argue'],
        formality: 'variable',
      },
      {
        key: 'convincing',
        label: 'Convincing',
        shortDescription: 'Capable of causing someone to believe.',
        summary: 'Causing someone to believe firmly.',
        description: 'Presents irrefutable arguments and evidence to leave no doubt in the reader\'s mind.',
        parameters: { doubt: 'removed', argument: 'strong', evidence: 'solid' },
        tags: ['credible', 'solid', 'firm'],
        formality: 'variable',
      },
      {
        key: 'compelling',
        label: 'Compelling',
        shortDescription: 'Evoking interest or attention powerfully.',
        summary: 'Evoking interest and attention powerfully.',
        description: 'Creates a narrative or argument so strong that the reader cannot stop reading.',
        parameters: { interest: 'high', unputdownable: 'yes', force: 'strong' },
        tags: ['gripping', 'powerful', 'magnetic'],
        formality: 'medium',
      },
      {
        key: 'motivational',
        label: 'Motivational',
        shortDescription: 'Provides a reason to act.',
        summary: 'Providing a strong reason to act.',
        description: 'Focuses on inspiring the reader to take positive action towards their goals.',
        parameters: { action: 'goal', inspiration: 'high', goals: 'focus' },
        tags: ['inspiring', 'action', 'goals'],
        formality: 'low',
      },
      {
        key: 'inspirational',
        label: 'Inspirational',
        shortDescription: 'Encourages creativity or new ideas.',
        summary: 'Encouraging creativity and new ideas.',
        description: 'Aims to uplift the reader\'s spirit and spark new ways of thinking.',
        parameters: { spirit: 'uplifted', creativity: 'sparked', newness: 'key' },
        tags: ['uplifting', 'creative', 'spirit'],
        formality: 'low',
      },
      {
        key: 'provocative',
        label: 'Provocative',
        shortDescription: 'Causing strong thought or reaction.',
        summary: 'Causing strong thought or angry reaction.',
        description: 'Intentionally stimulates a reaction, often by challenging established norms or beliefs.',
        parameters: { reaction: 'goal', challenge: 'strong', norms: 'targeted' },
        tags: ['challenging', 'stimulating', 'controversial'],
        formality: 'low',
      },
      {
        key: 'challenging',
        label: 'Challenging',
        shortDescription: 'Dares the reader to think differently.',
        summary: 'Daring the reader to think differently.',
        description: 'Confronts the reader\'s assumptions and forces them to reconsider their position.',
        parameters: { assumption: 'targeted', force: 'mental', dare: 'yes' },
        tags: ['confronting', 'daring', 'testing'],
        formality: 'variable',
      },
      {
        key: 'confrontational',
        label: 'Confrontational',
        shortDescription: 'Hostile and argumentative approach.',
        summary: 'Hostile, argumentative, and face-to-face.',
        description: 'Directly addresses problems or people in an aggressive and unyielding manner.',
        parameters: { aggression: 'high', avoidance: 'no', style: 'fight' },
        tags: ['hostile', 'aggressive', 'bold'],
        formality: 'low',
      },
      {
        key: 'assertive',
        label: 'Assertive',
        shortDescription: 'Confident and forceful behavior.',
        summary: 'Confident and forceful in behavior.',
        description: 'States needs and opinions clearly and confidently, without apologizing for them.',
        parameters: { confidence: 'high', apology: 'none', clarity: 'high' },
        tags: ['confident', 'strong', 'clear'],
        formality: 'medium',
      },
      {
        key: 'confident',
        label: 'Confident',
        shortDescription: 'Feeling or showing certainty.',
        summary: 'Feeling or showing total certainty.',
        description: 'Projects an air of absolute certainty and self-assurance in the message.',
        parameters: { certainty: 'total', assurance: 'projected', doubt: 'absent' },
        tags: ['sure', 'certain', 'assured'],
        formality: 'variable',
      },
      {
        key: 'bold',
        label: 'Bold',
        shortDescription: 'Showing willingness to take risks.',
        summary: 'Showing willingness to take risks.',
        description: 'Uses strong, fearless language that stands out and takes a definitive stance.',
        parameters: { risk: 'high', fear: 'none', stance: 'strong' },
        tags: ['fearless', 'brave', 'strong'],
        formality: 'variable',
      },
      {
        key: 'defiant',
        label: 'Defiant',
        shortDescription: 'Showing resistance or disobedience.',
        summary: 'Showing bold resistance and disobedience.',
        description: 'Openly resists authority or expectations, often with a sense of rebellious pride.',
        parameters: { resistance: 'open', authority: 'disobeyed', pride: 'high' },
        tags: ['rebellious', 'resistant', 'proud'],
        formality: 'low',
      },
      {
        key: 'rebellious',
        label: 'Rebellious',
        shortDescription: 'Opposing authority or control.',
        summary: 'Opposing authority and established control.',
        description: 'Actively questions and fights against the status quo or established rules.',
        parameters: { status: 'quo-fought', rules: 'broken', attitude: 'revolutionary' },
        tags: ['revolutionary', 'non-conformist', 'anti-establishment'],
        formality: 'low',
      },
      {
        key: 'tactful',
        label: 'Tactful',
        shortDescription: 'Adroit in dealing with others.',
        summary: 'Adroit, sensitive, and careful dealing.',
        description: 'Navigates difficult conversations with care to avoid hurting feelings or causing offense.',
        parameters: { sensitivity: 'high', offense: 'avoided', skill: 'social' },
        tags: ['sensitive', 'careful', 'social'],
        formality: 'high',
      },
      {
        key: 'non-confrontational',
        label: 'Non-Confrontational',
        shortDescription: 'Avoiding conflict or argument.',
        summary: 'Avoiding any conflict or argument.',
        description: 'Softens language and compromises to prevent disagreements or tension.',
        parameters: { conflict: 'avoided', tension: 'low', softness: 'high' },
        tags: ['peaceful', 'avoidant', 'soft'],
        formality: 'medium',
      },
      {
        key: 'mediating',
        label: 'Mediating',
        shortDescription: 'Intervening to bring agreement.',
        summary: 'Intervening to bring about agreement.',
        description: 'Uses neutral language to bridge the gap between two opposing viewpoints.',
        parameters: { neutrality: 'high', bridge: 'building', sides: 'all' },
        tags: ['neutral', 'bridge', 'peace'],
        formality: 'high',
      },
      {
        key: 'harmonious',
        label: 'Harmonious',
        shortDescription: 'Free from discord and conflict.',
        summary: 'Free from discord and open conflict.',
        description: 'Promotes agreement and cooperation, emphasizing points of unity rather than difference.',
        parameters: { discord: 'low', unity: 'high', cooperation: 'promoted' },
        tags: ['unified', 'agreeable', 'peaceful'],
        formality: 'medium',
      },
    ],
  },
  {
    category: 'Educational & Explanatory',
    tones: [
      {
        key: 'instructional',
        label: 'Instructional',
        shortDescription: 'Providing directions and instructions.',
        summary: 'Providing clear directions and instructions.',
        description: 'Focuses on the steps required to complete a specific task or process.',
        parameters: { steps: 'clear', task: 'focus', action: 'required' },
        tags: ['how-to', 'directions', 'steps'],
        formality: 'medium',
      },
      {
        key: 'tutorial',
        label: 'Tutorial',
        shortDescription: 'Step-by-step learning guide.',
        summary: 'Step-by-step learning and teaching guide.',
        description: 'Breaks down complex subjects into manageable lessons for a beginner.',
        parameters: { level: 'beginner', pace: 'slow', complexity: 'broken-down' },
        tags: ['learning', 'teaching', 'guide'],
        formality: 'medium',
      },
      {
        key: 'didactic',
        label: 'Didactic',
        shortDescription: 'Intended to teach or instruct.',
        summary: 'Intended to teach, often moralizing.',
        description: 'Educational but often with a moralizing or preachy undertone.',
        parameters: { teaching: 'intended', moral: 'likely', tone: 'preachy' },
        tags: ['moralizing', 'preachy', 'teaching'],
        formality: 'high',
      },
      {
        key: 'expository',
        label: 'Expository',
        shortDescription: 'Intended to explain or describe.',
        summary: 'Intended to explain, describe, and inform.',
        description: 'Provides a comprehensive explanation of a topic with facts and logical structure.',
        parameters: { explanation: 'comprehensive', facts: 'many', logic: 'structured' },
        tags: ['informative', 'explanatory', 'factual'],
        formality: 'high',
      },
      {
        key: 'explanatory',
        label: 'Explanatory',
        shortDescription: 'Making something clear or easy to understand.',
        summary: 'Making things clear and easy.',
        description: 'Clarifies complex ideas using simple language and analogies.',
        parameters: { clarity: 'goal', analogies: 'used', simplicity: 'key' },
        tags: ['clarifying', 'simple', 'analogy'],
        formality: 'medium',
      },
      {
        key: 'clarifying',
        label: 'Clarifying',
        shortDescription: 'Removing ambiguity and confusion.',
        summary: 'Removing ambiguity and clearing confusion.',
        description: 'Specifically addresses points of confusion to ensure the reader understands correctly.',
        parameters: { ambiguity: 'zero', confusion: 'target', focus: 'precision' },
        tags: ['precise', 'clear', 'defined'],
        formality: 'medium',
      },
      {
        key: 'scholarly',
        label: 'Scholarly',
        shortDescription: 'Involving learning or advanced knowledge.',
        summary: 'Involving advanced learning and knowledge.',
        description: 'Demonstrates deep knowledge and citation of academic sources within a formal register.',
        parameters: { knowledge: 'deep', sources: 'cited', register: 'formal' },
        tags: ['academic', 'learned', 'intellectual'],
        formality: 'high',
      },
      {
        key: 'research-based',
        label: 'Research-Based',
        shortDescription: 'Grounded in verifiable research.',
        summary: 'Grounded in verifiable and cited research.',
        description: 'Relies heavily on data and studies to back up every claim.',
        parameters: { data: 'primary', studies: 'cited', claims: 'backed' },
        tags: ['data', 'studies', 'evidence'],
        formality: 'high',
      },
      {
        key: 'analytical',
        label: 'Analytical',
        shortDescription: 'Using logical reasoning to examine.',
        summary: 'Using logical reasoning to examine.',
        description: 'Breaks down complex topics into smaller parts to understand how they work.',
        parameters: { logic: 'primary', breakdown: 'structural', understanding: 'deep' },
        tags: ['logical', 'breakdown', 'examine'],
        formality: 'high',
      },
      {
        key: 'critical',
        label: 'Critical',
        shortDescription: 'Expressing adverse or disapproving comments.',
        summary: 'Expressing adverse or disapproving judgments.',
        description: 'Evaluates merits and faults, often with a tendency to judge harshly.',
        parameters: { judgment: 'active', merits: 'weighed', faults: 'found' },
        tags: ['judgmental', 'evaluating', 'fault-finding'],
        formality: 'high',
      },
      {
        key: 'evaluative',
        label: 'Evaluative',
        shortDescription: 'Determining the significance or value.',
        summary: 'Determining the significance, worth, or value.',
        description: 'Assesses the value or quality of a subject against a set of criteria.',
        parameters: { criteria: 'set', value: 'assessed', judgment: 'measured' },
        tags: ['assessment', 'value', 'judgment'],
        formality: 'high',
      },
      {
        key: 'comparative',
        label: 'Comparative',
        shortDescription: 'Comparing similarities and differences.',
        summary: 'Comparing similarities and differences between items.',
        description: 'Examines two or more subjects to highlight how they are alike and different.',
        parameters: { subjects: 'multiple', likeness: 'highlighted', difference: 'highlighted' },
        tags: ['contrast', 'compare', 'difference'],
        formality: 'high',
      },
      {
        key: 'scientific',
        label: 'Scientific',
        shortDescription: 'Relating to science and systematic knowledge.',
        summary: 'Relating to science and systematic study.',
        description: 'Uses objective observation, measurement, and the scientific method to describe reality.',
        parameters: { method: 'scientific', objectivity: 'max', measurement: 'key' },
        tags: ['empirical', 'objective', 'systematic'],
        formality: 'high',
      },
      {
        key: 'empirical',
        label: 'Empirical',
        shortDescription: 'Based on observation and experience.',
        summary: 'Based on observation and experience.',
        description: 'Relies on practical experience and observable data rather than theory.',
        parameters: { theory: 'secondary', observation: 'primary', data: 'real' },
        tags: ['observation', 'experience', 'data'],
        formality: 'high',
      },
      {
        key: 'methodical',
        label: 'Methodical',
        shortDescription: 'Orderly and regular habits.',
        summary: 'Orderly, regular, and systematic procedure.',
        description: 'Approaches the subject in a slow, orderly, and systematic way.',
        parameters: { order: 'systematic', pace: 'slow', system: 'strict' },
        tags: ['systematic', 'orderly', 'procedure'],
        formality: 'high',
      },
      {
        key: 'systematic',
        label: 'Systematic',
        shortDescription: 'Done according to a fixed plan.',
        summary: 'Done according to a fixed plan.',
        description: 'Presents information in a logical, categorized, and structured system.',
        parameters: { logic: 'categorical', structure: 'fixed', plan: 'adhered' },
        tags: ['structured', 'categorical', 'logical'],
        formality: 'high',
      },
      {
        key: 'logical',
        label: 'Logical',
        shortDescription: 'Characterized by clear, sound reasoning.',
        summary: 'Characterized by clear, valid, reasoning.',
        description: 'Follows a chain of reasoning where the conclusion follows from the premises.',
        parameters: { reasoning: 'valid', conclusion: 'derived', flow: 'linear' },
        tags: ['reasoning', 'valid', 'sensible'],
        formality: 'high',
      },
      {
        key: 'rational',
        label: 'Rational',
        shortDescription: 'Based on reason rather than emotion.',
        summary: 'Based on reason, not emotion.',
        description: 'Suppresses emotional language in favor of clear-headed and reasonable arguments.',
        parameters: { emotion: 'suppressed', reason: 'primary', head: 'clear' },
        tags: ['reasonable', 'sane', 'clear-headed'],
        formality: 'high',
      },
      {
        key: 'evidence-based',
        label: 'Evidence-Based',
        shortDescription: 'Supported by concrete proof.',
        summary: 'Firmly supported by concrete proof.',
        description: 'Anchors every statement in verifiable facts and documented evidence.',
        parameters: { proof: 'required', facts: 'verifiable', documentation: 'cited' },
        tags: ['proof', 'facts', 'supported'],
        formality: 'high',
      },
    ],
  },
  {
    category: 'Creative & Artistic',
    tones: [
      {
        key: 'artistic',
        label: 'Artistic',
        shortDescription: 'Showing creative skill and imagination.',
        summary: 'Showing creative skill and imagination.',
        description: 'Prioritizes aesthetics and creative expression over strict utility or clarity.',
        parameters: { aesthetics: 'priority', expression: 'creative', utility: 'secondary' },
        tags: ['creative', 'aesthetic', 'imagination'],
        formality: 'low',
      },
      {
        key: 'imaginative',
        label: 'Imaginative',
        shortDescription: 'Creative and original.',
        summary: 'Creative, original, and full of invention.',
        description: 'Uses novel ideas and concepts to create something new and unexpected.',
        parameters: { novelty: 'high', invention: 'key', originality: 'high' },
        tags: ['novel', 'original', 'inventive'],
        formality: 'low',
      },
      {
        key: 'experimental',
        label: 'Experimental',
        shortDescription: 'Trying new methods or techniques.',
        summary: 'Trying new methods and techniques.',
        description: 'Breaks standard rules of writing or communication to see what happens.',
        parameters: { rules: 'broken', newness: 'goal', risk: 'high' },
        tags: ['new', 'untested', 'risky'],
        formality: 'low',
      },
      {
        key: 'avant-garde',
        label: 'Avant-Garde',
        shortDescription: 'New and experimental ideas.',
        summary: 'New, experimental, and innovative ideas.',
        description: 'Pushes the boundaries of what is considered acceptable or normal in art.',
        parameters: { boundaries: 'pushed', normal: 'rejected', innovation: 'extreme' },
        tags: ['innovative', 'boundary-pushing', 'edgy'],
        formality: 'low',
      },
      {
        key: 'surreal',
        label: 'Surreal',
        shortDescription: 'Dreamlike and bizarre qualities.',
        summary: 'Dreamlike, bizarre, and unreal qualities.',
        description: 'Juxtaposes unrelated elements to create a strange, dream-like effect.',
        parameters: { reality: 'suspended', dream: 'logic', juxtaposition: 'strange' },
        tags: ['dream', 'strange', 'unreal'],
        formality: 'low',
      },
      {
        key: 'dreamlike',
        label: 'Dreamlike',
        shortDescription: 'Resembling a dream in quality.',
        summary: 'Resembling a dream in quality.',
        description: 'Uses soft, blurry, and flowing language to mimic the feeling of a dream.',
        parameters: { focus: 'soft', edges: 'blurred', flow: 'liquid' },
        tags: ['dreamy', 'flowing', 'soft'],
        formality: 'low',
      },
      {
        key: 'fantastical',
        label: 'Fantastical',
        shortDescription: 'Bizarre and imaginary elements.',
        summary: 'Bizarre, imaginary, and magical elements.',
        description: 'Incorporates magic and impossible things as if they were real.',
        parameters: { magic: 'real', impossible: 'possible', reality: 'escaped' },
        tags: ['magic', 'fantasy', 'impossible'],
        formality: 'low',
      },
      {
        key: 'futuristic',
        label: 'Futuristic',
        shortDescription: 'Imagining the future.',
        summary: 'Imagining the future and technology.',
        description: 'Uses language and concepts associated with advanced technology and sci-fi settings.',
        parameters: { time: 'future', tech: 'high', setting: 'sci-fi' },
        tags: ['sci-fi', 'tech', 'tomorrow'],
        formality: 'variable',
      },
      {
        key: 'retro',
        label: 'Retro',
        shortDescription: 'Imitating a style from the past.',
        summary: 'Imitating a style from the past.',
        description: 'Intentionally mimics the aesthetic and slang of a specific past decade.',
        parameters: { time: 'past', style: 'mimicked', authenticity: 'high' },
        tags: ['past', 'vintage', 'old-school'],
        formality: 'low',
      },
      {
        key: 'vintage',
        label: 'Vintage',
        shortDescription: 'Classic, old-fashioned, and high quality.',
        summary: 'Classic, old-fashioned, and high quality.',
        description: 'Evokes the charm and elegance of a bygone era with polished language.',
        parameters: { era: 'bygone', elegance: 'high', charm: 'key' },
        tags: ['classic', 'old', 'elegant'],
        formality: 'medium',
      },
      {
        key: 'quirky',
        label: 'Quirky',
        shortDescription: 'Unusual and attractive character.',
        summary: 'Unusual, attractive, and odd character.',
        description: 'Uses idiosyncratic language and surprising choices to create a unique personality.',
        parameters: { oddness: 'light', uniqueness: 'high', character: 'strong' },
        tags: ['odd', 'unique', 'character'],
        formality: 'low',
      },
      {
        key: 'eccentric',
        label: 'Eccentric',
        shortDescription: 'Unconventional and strange behavior.',
        summary: 'Unconventional and slightly strange behavior.',
        description: 'Deviates significantly from the norm in a way that is intriguing or baffling.',
        parameters: { norm: 'deviated', strangeness: 'high', intrigue: 'high' },
        tags: ['strange', 'weird', 'baffling'],
        formality: 'low',
      },
      {
        key: 'unconventional',
        label: 'Unconventional',
        shortDescription: 'Not based on conformity.',
        summary: 'Not based on what is usual.',
        description: 'Refuses to follow standard templates or expectations in communication.',
        parameters: { conformity: 'refused', template: 'broken', expectations: 'subverted' },
        tags: ['non-conformist', 'different', 'unique'],
        formality: 'low',
      },
    ],
  },
  {
    category: 'Journalistic & Media',
    tones: [
      {
        key: 'journalistic',
        label: 'Journalistic',
        shortDescription: 'Relating to journalism or reporters.',
        summary: 'Relating to the work of journalists.',
        description: 'Adheres to the principles of reporting: who, what, where, when, why, and how.',
        parameters: { principles: '5ws', reporting: 'standard', bias: 'minimal' },
        tags: ['reporting', 'news', 'factual'],
        formality: 'high',
      },
      {
        key: 'newsy',
        label: 'Newsy',
        shortDescription: 'Full of or interested in news.',
        summary: 'Full of interesting current news.',
        description: 'Conveys the feeling of a fast-paced news update, focusing on current events.',
        parameters: { pace: 'fast', events: 'current', updates: 'frequent' },
        tags: ['current', 'update', 'fast'],
        formality: 'medium',
      },
      {
        key: 'investigative',
        label: 'Investigative',
        shortDescription: 'In-depth research to uncover facts.',
        summary: 'Deep research to uncover facts.',
        description: 'Uses persistent questioning and deep digging to reveal hidden truths.',
        parameters: { digging: 'deep', truth: 'hidden', persistence: 'high' },
        tags: ['digging', 'truth', 'persistence'],
        formality: 'high',
      },
      {
        key: 'expose',
        label: 'Exposé',
        shortDescription: 'Revealing shocking or scandalous facts.',
        summary: 'Revealing shocking and scandalous facts.',
        description: 'Presents secret or scandalous information to the public in a dramatic way.',
        parameters: { shock: 'high', secret: 'revealed', drama: 'high' },
        tags: ['scandal', 'secret', 'shock'],
        formality: 'high',
      },
      {
        key: 'editorial',
        label: 'Editorial',
        shortDescription: 'Reflecting the opinion of the editor.',
        summary: 'Reflecting the opinion of the publisher.',
        description: 'Expresses a subjective opinion rather than objective fact, typical of op-eds.',
        parameters: { opinion: 'primary', fact: 'supporting', voice: 'institutional' },
        tags: ['opinion', 'subjective', 'institutional'],
        formality: 'high',
      },
      {
        key: 'opinionated',
        label: 'Opinionated',
        shortDescription: 'Conceitedly asserting opinions as facts.',
        summary: 'Asserting opinions strongly as facts.',
        description: 'Does not shy away from taking a strong, personal stance on the subject.',
        parameters: { stance: 'strong', personal: 'yes', neutrality: 'no' },
        tags: ['biased', 'strong', 'personal'],
        formality: 'medium',
      },
      {
        key: 'balanced',
        label: 'Balanced',
        shortDescription: 'Giving equal attention to all sides.',
        summary: 'Giving equal attention to all sides.',
        description: 'Presents multiple viewpoints fairly without favoring one over the others.',
        parameters: { viewpoints: 'multiple', fairness: 'high', favor: 'none' },
        tags: ['fair', 'multiple', 'equal'],
        formality: 'high',
      },
      {
        key: 'unbiased',
        label: 'Unbiased',
        shortDescription: 'Showing no prejudice for or against.',
        summary: 'Showing no prejudice for or against.',
        description: 'Strives for complete objectivity, avoiding personal feelings or preferences.',
        parameters: { prejudice: 'none', objectivity: 'total', feelings: 'removed' },
        tags: ['objective', 'neutral', 'fair'],
        formality: 'high',
      },
      {
        key: 'sensational',
        label: 'Sensational',
        shortDescription: 'Creating interest and excitement.',
        summary: 'Creating great public interest and excitement.',
        description: 'Uses夸张 language to provoke excitement or shock rather than to inform.',
        parameters: { shock: 'goal', excitement: 'high', info: 'secondary' },
        tags: ['shock', 'excitement', 'exaggerated'],
        formality: 'low',
      },
      {
        key: 'clickbaity',
        label: 'Clickbaity',
        shortDescription: 'Designed to attract attention for clicks.',
        summary: 'Designed to attract clicks and attention.',
        description: 'Uses curiosity gaps and emotional triggers to trick users into clicking a link.',
        parameters: { curiosity: 'gap', trigger: 'emotional', click: 'goal' },
        tags: ['marketing', 'curiosity', 'trick'],
        formality: 'low',
      },
      {
        key: 'tabloid',
        label: 'Tabloid',
        shortDescription: 'Sensational and lurid reporting.',
        summary: 'Sensational, lurid, and popular reporting.',
        description: 'Focuses on scandals, celebrities, and emotional appeals rather than hard news.',
        parameters: { scandal: 'focus', celebrity: 'high', emotion: 'primary' },
        tags: ['scandal', 'celebrity', 'gossip'],
        formality: 'low',
      },
      {
        key: 'documentary-style',
        label: 'Documentary-Style',
        shortDescription: 'Informative and factual narrative.',
        summary: 'Informative, factual, and narrative style.',
        description: 'Combines factual reporting with narrative storytelling techniques to educate.',
        parameters: { facts: 'high', narrative: 'used', education: 'goal' },
        tags: ['factual', 'narrative', 'education'],
        formality: 'high',
      },
    ],
  },
  {
    category: 'Technical & Specialized',
    tones: [
      {
        key: 'engineering',
        label: 'Engineering',
        shortDescription: 'Practical application of science and math.',
        summary: 'Practical application of science and math.',
        description: 'Focuses on systems, efficiency, and technical constraints with precise terminology.',
        parameters: { focus: 'systems', efficiency: 'key', terminology: 'precise' },
        tags: ['systems', 'efficiency', 'technical'],
        formality: 'high',
      },
      {
        key: 'developer-focused',
        label: 'Developer-Focused',
        shortDescription: 'Tailored for software programmers.',
        summary: 'Tailored specifically for software programmers.',
        description: 'Assumes knowledge of coding concepts and syntax, skipping basic explanations.',
        parameters: { audience: 'coders', basics: 'skipped', syntax: 'known' },
        tags: ['coding', 'programming', 'syntax'],
        formality: 'low',
      },
      {
        key: 'code-centric',
        label: 'Code-Centric',
        shortDescription: 'Focusing primarily on code examples.',
        summary: 'Focusing primarily on code examples.',
        description: 'Uses code snippets as the primary method of explanation, with minimal prose.',
        parameters: { code: 'primary', prose: 'minimal', examples: 'many' },
        tags: ['code', 'examples', 'snippets'],
        formality: 'variable',
      },
      {
        key: 'architectural',
        label: 'Architectural',
        shortDescription: 'High-level structural design of systems.',
        summary: 'High-level structural design of systems.',
        description: 'Discusses the overall structure, patterns, and relationships within a system.',
        parameters: { level: 'high', structure: 'focus', patterns: 'discussed' },
        tags: ['structure', 'design', 'patterns'],
        formality: 'high',
      },
      {
        key: 'systemic',
        label: 'Systemic',
        shortDescription: 'Relating to a system as a whole.',
        summary: 'Relating to a system as whole.',
        description: 'Considers the entire system and its interdependencies rather than individual parts.',
        parameters: { scope: 'whole', parts: 'interconnected', view: 'holistic' },
        tags: ['holistic', 'whole', 'interconnected'],
        formality: 'high',
      },
      {
        key: 'diagnostic',
        label: 'Diagnostic',
        shortDescription: 'Identifying the nature of a problem.',
        summary: 'Identifying the nature of problems.',
        description: 'Analyzes symptoms and errors to pinpoint the root cause of a failure.',
        parameters: { symptoms: 'analyzed', cause: 'found', failure: 'target' },
        tags: ['debugging', 'analysis', 'problem-solving'],
        formality: 'high',
      },
      {
        key: 'troubleshooting',
        label: 'Troubleshooting',
        shortDescription: 'Solving technical problems systematically.',
        summary: 'Solving technical problems systematically.',
        description: 'Provides a stepwise approach to fixing specific issues or errors.',
        parameters: { approach: 'stepwise', issue: 'specific', fix: 'provided' },
        tags: ['fixing', 'steps', 'issues'],
        formality: 'medium',
      },
      {
        key: 'how-to',
        label: 'How-To',
        shortDescription: 'Practical instructions on doing something.',
        summary: 'Practical instructions on doing something.',
        description: 'Gives actionable steps to achieve a specific result.',
        parameters: { action: 'specific', steps: 'actionable', result: 'clear' },
        tags: ['guide', 'steps', 'actionable'],
        formality: 'low',
      },
      {
        key: 'step-by-step',
        label: 'Step-by-Step',
        shortDescription: 'Sequential instructions.',
        summary: 'Sequential and ordered instructions.',
        description: 'Breaks down a process into a strictly ordered sequence of actions.',
        parameters: { order: 'strict', sequence: 'linear', actions: 'atomic' },
        tags: ['ordered', 'linear', 'sequential'],
        formality: 'low',
      },
      {
        key: 'api-style',
        label: 'API-Style',
        shortDescription: 'Formatted like API documentation.',
        summary: 'Formatted like technical API documentation.',
        description: 'Uses structured blocks for endpoints, parameters, and responses typical of API docs.',
        parameters: { format: 'structured', blocks: 'technical', content: 'reference' },
        tags: ['api', 'reference', 'structured'],
        formality: 'high',
      },
      {
        key: 'cli-like',
        label: 'CLI-Like',
        shortDescription: 'Mimicking command line interface output.',
        summary: 'Mimicking command line interface output.',
        description: 'Uses terse text, flags, and terminal-like formatting.',
        parameters: { brevity: 'extreme', formatting: 'terminal', flags: 'used' },
        tags: ['terminal', 'flags', 'terse'],
        formality: 'low',
      },
    ],
  },
  {
    category: 'Audience-Oriented',
    tones: [
      {
        key: 'youthful',
        label: 'Youthful',
        shortDescription: 'Full of energy and young spirit.',
        summary: 'Full of energy and young spirit.',
        description: 'Uses high energy, slang, and references relevant to a younger demographic.',
        parameters: { energy: 'high', slang: 'current', relevance: 'youth' },
        tags: ['young', 'energy', 'slang'],
        formality: 'low',
      },
      {
        key: 'teen-friendly',
        label: 'Teen-Friendly',
        shortDescription: 'Appropriate and engaging for teenagers.',
        summary: 'Appropriate and engaging for teenagers.',
        description: 'Strikes a balance between adult concepts and teen culture without being patronizing.',
        parameters: { culture: 'teen', patronizing: 'no', concepts: 'accessible' },
        tags: ['teen', 'accessible', 'culture'],
        formality: 'low',
      },
      {
        key: 'childlike',
        label: 'Childlike',
        shortDescription: 'Resembling a child in quality.',
        summary: 'Resembling a child in quality.',
        description: 'Uses simple words, wonder, and innocence typical of young children.',
        parameters: { words: 'simple', wonder: 'high', innocence: 'pure' },
        tags: ['innocent', 'simple', 'wonder'],
        formality: 'low',
      },
      {
        key: 'parental',
        label: 'Parental',
        shortDescription: 'Caring and authoritative like a parent.',
        summary: 'Caring, protective, and guiding tone.',
        description: 'Offers guidance with a mix of authority and deep care for the well-being.',
        parameters: { authority: 'high', care: 'deep', guidance: 'primary' },
        tags: ['caring', 'authority', 'guide'],
        formality: 'medium',
      },
      {
        key: 'elderly-appropriate',
        label: 'Elderly-Appropriate',
        shortDescription: 'Respectful and clear for older adults.',
        summary: 'Respectful, clear, and large text.',
        description: 'Uses respectful language, avoids slang, and emphasizes clarity and patience.',
        parameters: { respect: 'high', slang: 'avoided', clarity: 'max' },
        tags: ['respectful', 'clear', 'patient'],
        formality: 'medium',
      },
      {
        key: 'inclusive',
        label: 'Inclusive',
        shortDescription: 'Not excluding any groups.',
        summary: 'Not excluding any groups or people.',
        description: 'Uses language that welcomes people of all backgrounds and abilities.',
        parameters: { exclusion: 'none', welcome: 'all', diversity: 'celebrated' },
        tags: ['diverse', 'welcoming', 'accessible'],
        formality: 'medium',
      },
      {
        key: 'accessible',
        label: 'Accessible',
        shortDescription: 'Easily understood by all.',
        summary: 'Easily understood by everyone.',
        description: 'Simplifies complex concepts so that anyone, regardless of background, can understand.',
        parameters: { complexity: 'reduced', background: 'any', understanding: 'goal' },
        tags: ['simple', 'understandable', 'easy'],
        formality: 'medium',
      },
      {
        key: 'culturally-sensitive',
        label: 'Culturally-Sensitive',
        shortDescription: 'Aware of cultural differences.',
        summary: 'Aware of and respecting cultural differences.',
        description: 'Avoids stereotypes and acknowledges cultural nuances respectfully.',
        parameters: { stereotypes: 'avoided', nuances: 'respected', awareness: 'high' },
        tags: ['culture', 'respect', 'awareness'],
        formality: 'high',
      },
      {
        key: 'globally-aware',
        label: 'Globally-Aware',
        shortDescription: 'Understanding international issues and perspectives.',
        summary: 'Understanding international issues and perspectives.',
        description: 'Frames content with an understanding of global interconnectedness and diverse viewpoints.',
        parameters: { scope: 'global', viewpoint: 'diverse', connection: 'international' },
        tags: ['international', 'world', 'diverse'],
        formality: 'high',
      },
      {
        key: 'localized',
        label: 'Localized',
        shortDescription: 'Adapted to a specific locale.',
        summary: 'Adapted specifically for a local area.',
        description: 'Uses slang, references, and currency relevant to a specific geographic location.',
        parameters: { references: 'local', slang: 'regional', currency: 'local' },
        tags: ['local', 'regional', 'specific'],
        formality: 'variable',
      },
      {
        key: 'mentoring',
        label: 'Mentoring',
        shortDescription: 'Advising and training a less experienced person.',
        summary: 'Advising a less experienced learner.',
        description: 'Shares wisdom and experience to foster the growth of the reader.',
        parameters: { wisdom: 'shared', experience: 'source', growth: 'goal' },
        tags: ['advice', 'wisdom', 'growth'],
        formality: 'medium',
      },
      {
        key: 'coaching',
        label: 'Coaching',
        shortDescription: 'Directing and instructing a team.',
        summary: 'Directing and instructing for improvement.',
        description: 'Focuses on performance improvement and skill development through feedback and motivation.',
        parameters: { performance: 'focus', skill: 'build', feedback: 'active' },
        tags: ['feedback', 'improvement', 'skill'],
        formality: 'medium',
      },
      {
        key: 'peer-to-peer',
        label: 'Peer-to-Peer',
        shortDescription: 'Between people of equal standing.',
        summary: 'Communication between equals and colleagues.',
        description: 'Uses a collaborative and equal tone, avoiding hierarchy or condescension.',
        parameters: { hierarchy: 'flat', equality: 'key', collaboration: 'yes' },
        tags: ['equal', 'collaborative', 'flat'],
        formality: 'medium',
      },
      {
        key: 'collegial',
        label: 'Collegial',
        shortDescription: 'Relating to colleagues or college.',
        summary: 'Relating to friendly colleagues together.',
        description: 'Friendly and cooperative, typical of interaction between professional colleagues.',
        parameters: { friendliness: 'high', cooperation: 'yes', professionalism: 'kept' },
        tags: ['colleague', 'cooperative', 'friendly'],
        formality: 'high',
      },
      {
        key: 'academic-peer',
        label: 'Academic-Peer',
        shortDescription: 'Between scholars in the same field.',
        summary: 'Between scholars in the same field.',
        description: 'Assumes a high level of shared knowledge and uses specialized terminology freely.',
        parameters: { knowledge: 'shared', jargon: 'high', level: 'expert' },
        tags: ['scholar', 'expert', 'jargon'],
        formality: 'high',
      },
      {
        key: 'student-friendly',
        label: 'Student-Friendly',
        shortDescription: 'Encouraging and clear for learners.',
        summary: 'Encouraging and clear for learners.',
        description: 'Uses supportive language and clear explanations to help students learn.',
        parameters: { support: 'high', clarity: 'high', encouragement: 'frequent' },
        tags: ['learning', 'support', 'clear'],
        formality: 'medium',
      },
    ],
  },
  {
    category: 'Brand & Marketing',
    tones: [
      {
        key: 'brand-aligned',
        label: 'Brand-Aligned',
        shortDescription: 'Consistent with a specific brand identity.',
        summary: 'Consistent with the specific brand identity.',
        description: 'Strictly adheres to the voice, vocabulary, and values defined by a specific brand.',
        parameters: { identity: 'specific', adherence: 'strict', voice: 'fixed' },
        tags: ['brand', 'identity', 'voice'],
        formality: 'variable',
      },
      {
        key: 'on-message',
        label: 'On-Message',
        shortDescription: 'Focusing on the key talking points.',
        summary: 'Focusing on key talking points.',
        description: 'Keeps the communication focused strictly on the intended core message or strategy.',
        parameters: { focus: 'core', strategy: 'adhered', drift: 'none' },
        tags: ['focus', 'strategy', 'core'],
        formality: 'variable',
      },
      {
        key: 'premium',
        label: 'Premium',
        shortDescription: 'High quality and exclusive feel.',
        summary: 'High quality, expensive, and exclusive.',
        description: 'Uses sophisticated language and an elegant demeanor to signify high value and exclusivity.',
        parameters: { quality: 'high', value: 'luxury', elegance: 'high' },
        tags: ['luxury', 'expensive', 'high-end'],
        formality: 'high',
      },
      {
        key: 'luxury',
        label: 'Luxury',
        shortDescription: 'Indulgent and expensive enjoyment.',
        summary: 'Indulgent, expensive, and elegant enjoyment.',
        description: 'Evokes a sense of indulgence, comfort, and superior quality.',
        parameters: { indulgence: 'key', comfort: 'high', superior: 'yes' },
        tags: ['indulgent', 'comfort', 'superior'],
        formality: 'high',
      },
      {
        key: 'minimal-brand',
        label: 'Minimal-Brand',
        shortDescription: 'Understated and clean brand presence.',
        summary: 'Understated, clean, and subtle brand.',
        description: 'Conveys the brand message quietly and subtly without aggressive logos or sales tactics.',
        parameters: { volume: 'low', subtlety: 'high', branding: 'quiet' },
        tags: ['understated', 'clean', 'subtle'],
        formality: 'medium',
      },
      {
        key: 'vibrant',
        label: 'Vibrant',
        shortDescription: 'Full of energy and life.',
        summary: 'Full of energy, life, and color.',
        description: 'Uses bright, energetic language and an enthusiastic tone to create excitement.',
        parameters: { energy: 'bright', life: 'high', excitement: 'colorful' },
        tags: ['energetic', 'bright', 'colorful'],
        formality: 'low',
      },
      {
        key: 'trustworthy',
        label: 'Trustworthy',
        shortDescription: 'Able to be relied on as honest.',
        summary: 'Reliable, honest, and truthful.',
        description: 'Uses consistent, transparent, and honest language to build a relationship of trust.',
        parameters: { consistency: 'high', transparency: 'key', honesty: 'total' },
        tags: ['reliable', 'honest', 'transparent'],
        formality: 'high',
      },
      {
        key: 'authentic',
        label: 'Authentic',
        shortDescription: 'Genuine and real.',
        summary: 'Genuine, real, and true to self.',
        description: 'Avoids marketing fluff to sound like a real person speaking honestly.',
        parameters: { fluff: 'none', realness: 'high', honesty: 'personal' },
        tags: ['real', 'honest', 'personal'],
        formality: 'low',
      },
      {
        key: 'relatable',
        label: 'Relatable',
        shortDescription: 'Easy to understand and empathize with.',
        summary: 'Easy to understand and empathize with.',
        description: 'Uses shared experiences and common language to make the reader feel understood.',
        parameters: { shared: 'experiences', common: 'language', understood: 'feeling' },
        tags: ['empathy', 'common', 'shared'],
        formality: 'low',
      },
      {
        key: 'aspirational',
        label: 'Aspirational',
        shortDescription: 'Having a strong desire to achieve.',
        summary: 'Inspiring a desire to achieve more.',
        description: 'Paints a picture of a better future or lifestyle that the reader wants.',
        parameters: { future: 'better', desire: 'create', lifestyle: 'ideal' },
        tags: ['inspiring', 'future', 'goals'],
        formality: 'medium',
      },
      {
        key: 'disruptive',
        label: 'Disruptive',
        shortDescription: 'Causing radical change in the industry.',
        summary: 'Causing radical and revolutionary change.',
        description: 'Challenges the status quo aggressively to position the brand as an innovator.',
        parameters: { status: 'challenged', aggression: 'high', innovation: 'claim' },
        tags: ['revolutionary', 'challenger', 'innovation'],
        formality: 'low',
      },
      {
        key: 'innovative',
        label: 'Innovative',
        shortDescription: 'Featuring new methods or ideas.',
        summary: 'Featuring new, advanced, and creative methods.',
        description: 'Highlights novelty, progress, and cutting-edge technology or thinking.',
        parameters: { novelty: 'key', progress: 'highlighted', edge: 'cutting' },
        tags: ['new', 'creative', 'advanced'],
        formality: 'medium',
      },
      {
        key: 'customer-centric',
        label: 'Customer-Centric',
        shortDescription: 'Focusing primarily on customer needs.',
        summary: 'Focusing primarily on customer needs.',
        description: 'Prioritizes the needs and satisfaction of the customer above all else.',
        parameters: { customer: 'priority', needs: 'focus', satisfaction: 'goal' },
        tags: ['customer', 'service', 'needs'],
        formality: 'medium',
      },
      {
        key: 'user-first',
        label: 'User-First',
        shortDescription: 'Prioritizing the user experience.',
        summary: 'Prioritizing the user experience above all.',
        description: 'Designs the message to be most helpful and usable for the end user.',
        parameters: { user: 'main', experience: 'priority', helpfulness: 'max' },
        tags: ['ux', 'user', 'helpful'],
        formality: 'medium',
      },
      {
        key: 'solution-oriented',
        label: 'Solution-Oriented',
        shortDescription: 'Focusing on answers rather than problems.',
        summary: 'Focusing on answers, not problems.',
        description: 'Moves quickly from stating a problem to presenting the solution.',
        parameters: { problem: 'brief', solution: 'detailed', action: 'fix' },
        tags: ['answers', 'fixes', 'solving'],
        formality: 'medium',
      },
      {
        key: 'benefit-driven',
        label: 'Benefit-Driven',
        shortDescription: 'Highlighting the advantages to the user.',
        summary: 'Highlighting advantages to the user.',
        description: 'Focuses text on what the user gains rather than just features.',
        parameters: { gain: 'focus', features: 'secondary', advantage: 'highlighted' },
        tags: ['advantage', 'gain', 'value'],
        formality: 'medium',
      },
    ],
  },
  {
    category: 'Mood & Atmosphere',
    tones: [
      {
        key: 'calm',
        label: 'Calm',
        shortDescription: 'Not showing or feeling agitation.',
        summary: 'Not showing or feeling agitation.',
        description: 'Uses steady, rhythmic language to project tranquility and lack of stress.',
        parameters: { stress: 'none', rhythm: 'steady', tranquility: 'high' },
        tags: ['peaceful', 'tranquil', 'steady'],
        formality: 'low',
      },
      {
        key: 'peaceful',
        label: 'Peaceful',
        shortDescription: 'Free from disturbance.',
        summary: 'Free from disturbance and war.',
        description: 'Evokes a sense of harmony and lack of conflict.',
        parameters: { conflict: 'none', harmony: 'high', disturbance: 'none' },
        tags: ['harmony', 'quiet', 'serene'],
        formality: 'low',
      },
      {
        key: 'serene',
        label: 'Serene',
        shortDescription: 'Calm and peaceful and untroubled.',
        summary: 'Calm, peaceful, and untroubled.',
        description: 'Conveys a lofty, spiritual sense of peace and clearness.',
        parameters: { peace: 'lofty', clearness: 'high', trouble: 'none' },
        tags: ['clear', 'untroubled', 'lofty'],
        formality: 'low',
      },
      {
        key: 'tense',
        label: 'Tense',
        shortDescription: 'Showing nervousness or strain.',
        summary: 'Showing nervousness, anxiety, or strain.',
        description: 'Uses short, clipped sentences and high-stakes vocabulary to create anxiety.',
        parameters: { anxiety: 'high', clipping: 'yes', stakes: 'high' },
        tags: ['anxious', 'strained', 'tight'],
        formality: 'low',
      },
      {
        key: 'suspenseful',
        label: 'Suspenseful',
        shortDescription: 'Arousing excited expectation or uncertainty.',
        summary: 'Arousing excited expectation and uncertainty.',
        description: 'Withholds information or slows the pace to make the reader wait for the answer.',
        parameters: { info: 'withheld', pace: 'slow', wait: 'forced' },
        tags: ['waiting', 'uncertainty', 'excitement'],
        formality: 'low',
      },
      {
        key: 'mysterious',
        label: 'Mysterious',
        shortDescription: 'Difficult or impossible to understand.',
        summary: 'Difficult or impossible to understand.',
        description: 'Uses vague hints and obscured facts to provoke curiosity and confusion.',
        parameters: { hints: 'vague', facts: 'obscured', curiosity: 'provoked' },
        tags: ['secret', 'vague', 'puzzle'],
        formality: 'low',
      },
      {
        key: 'eerie',
        label: 'Eerie',
        shortDescription: 'Strange and frightening.',
        summary: 'Strange, frightening, and scary atmosphere.',
        description: 'Creates a sense of creepiness and supernatural unease through subtle details.',
        parameters: { creepiness: 'high', supernatural: 'hinted', details: 'subtle' },
        tags: ['creepy', 'scary', 'spooky'],
        formality: 'low',
      },
      {
        key: 'celebratory',
        label: 'Celebratory',
        shortDescription: 'Celebrating a happy event or day.',
        summary: 'Celebrating a happy event or day.',
        description: 'Uses exclamations, positive adjectives, and communal language to mark a happy occasion.',
        parameters: { exclamation: 'high', positivity: 'high', community: 'focus' },
        tags: ['happy', 'party', 'event'],
        formality: 'low',
      },
      {
        key: 'festive',
        label: 'Festive',
        shortDescription: 'Relating to a celebration.',
        summary: 'Relating to a joyful celebration.',
        description: 'Evokes the specific atmosphere and traditions of a holiday or festival.',
        parameters: { tradition: 'evoked', holiday: 'specific', joy: 'collective' },
        tags: ['holiday', 'tradition', 'joy'],
        formality: 'low',
      },
      {
        key: 'solemn',
        label: 'Solemn',
        shortDescription: 'Not cheerful or smiling; serious.',
        summary: 'Serious, not cheerful, and dignified.',
        description: 'Uses grave and serious language to mark an important or sad occasion.',
        parameters: { gravity: 'high', cheer: 'none', occasion: 'serious' },
        tags: ['serious', 'grave', 'dignified'],
        formality: 'high',
      },
      {
        key: 'ceremonial',
        label: 'Ceremonial',
        shortDescription: 'Relating to a ceremony.',
        summary: 'Relating to a formal ceremony.',
        description: 'Uses rigid, formal structures and flowery language suitable for rites of passage.',
        parameters: { rigidity: 'high', formality: 'max', rite: 'passage' },
        tags: ['rite', 'formal', 'ritual'],
        formality: 'high',
      },
      {
        key: 'ritualistic',
        label: 'Ritualistic',
        shortDescription: 'Following a strict pattern.',
        summary: 'Following a strict, repetitive pattern.',
        description: 'Repeats specific phrases or structures to induce a trance-like or traditional state.',
        parameters: { pattern: 'strict', repetition: 'high', tradition: 'followed' },
        tags: ['repetition', 'pattern', 'tradition'],
        formality: 'variable',
      },
      {
        key: 'meditative',
        label: 'Meditative',
        shortDescription: 'Involving deep thought or contemplation.',
        summary: 'Involving deep thought and contemplation.',
        description: 'Uses slow, rhythmic, and abstract language to induce a state of reflection.',
        parameters: { thought: 'deep', speed: 'slow', reflection: 'goal' },
        tags: ['reflection', 'contemplation', 'slow'],
        formality: 'low',
      },
    ],
  },
];

/**
 * A constant array representing predefined tone categories or styles, typically used to categorize communication styles, design elements, or other thematic classifications.
 * @example ["formal", "casual"]
 * @developerNotes This array is extensible and should remain consistent with the project's terminology and use cases (e.g., "professional" vs "informal" if needed).
 */
export const TONES: string[] = [...new Set(TONES_GROUPED.reduce((acc: string[], group) => {
  acc.push(...group.tones.map(x => x.key));
  return acc;
}, []))];
